### PR TITLE
fix(NewMessage): make silent chat button appearance more obvious

### LINKED ISSUE #12008: send without notification is not obvious enough
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Attempting to send messages via "Send without notification" no longer works.
ERR... wait, is this now a toggle?

## Steps to reproduce
1. type message
2. select "Send without notification"
3. message does not send (previously it would send when you selected "Send without notification"

### Expected behaviour
The message sends, silently for the recipient.

### Actual behaviour
Now the option toggles to "Send with notification" but the user only discovers the behaviour change if selecting the `...` menu again?

image

Suggest:
* either the behaviour return to previous behaviour
* or have an indicator appear that message notification silence is now enabled.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
- Nextcloud Server version 29.0.0 RC2
- Nextcloud Talk version 19.0.0-rc.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
NixOS/Linux

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
124.0.1

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)
- Nextcloud Server version 29.0.0 RC2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #12008
  * Same appearance as for filters in LeftSidebar
  * Less text changes, to describe only ENABLED behavior

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
imageimage | imageimage

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by nickvergessen** [comment]
I would go with a https://nextcloud-vue-components.netlify.app/#/Components/NcCheckboxRadioSwitch `Standard Switch` to make it more clear, but then we don't have the space/place for the bell icon anymore

File: src/components/NewMessage/NewMessage.vue [hunk 1]
```diff
@@ -142,12 +142,12 @@
 			<template v-else>
 				<NcActions v-if="!broadcast" :container="container" force-menu>
 					<NcActionButton close-after-click
+						:model-value="silentChat"
 						:name="silentSendLabel"
 						@click="toggleSilentChat">
 						{{ silentSendInfo }}
 						<template #icon>
-							<BellIcon v-if="silentChat" :size="16" />
```
Comment (DorraJaouad) [inline src/components/NewMessage/NewMessage.vue:149]: lint: remove the icon from import and from components

**Review by DorraJaouad — DISMISSED** [review]
Better approach 👍🏻. Until a new icon with small audio off on bottom right comes out
like this https://pictogrammers.com/library/mdi/icon/send-check/

**Comment by Antreesy** [comment]
> NcCheckboxRadioSwitch

Not supported by NcActions menu at the moment, so either this, or we might need to improvise

**Comment by DorraJaouad** [comment]
> or we might need to improvise

If we are doing this, let's hard-code the send icon by adding the [ bell](https://pictogrammers.com/library/mdi/icon/bell-off-outline/) to the bottom right with styles ?

**Comment by Antreesy** [comment]
> > or we might need to improvise
> 
> If we are doing this, let's hard-code the send icon by adding the [ bell](https://pictogrammers.com/library/mdi/icon/bell-off-outline/) to the bottom right with styles ?

Something like this? 
image

I'd go with adding it to missingMdiIcons, as we did before

**Comment by DorraJaouad** [comment]
or this https://pictogrammers.com/library/mdi/icon/bell-off-outline/

and maybe increase the size a bit.

**Comment by nickvergessen** [comment]
How about only doing these simple 3 lines:
```diff
diff --git a/src/components/NewMessage/NewMessage.vue b/src/components/NewMessage/NewMessage.vue
index 4b1e45c25..b1523e694 100644
--- a/src/components/NewMessage/NewMessage.vue
+++ b/src/components/NewMessage/NewMessage.vue
@@ -141,6 +141,9 @@
                        <!-- Send buttons -->
                        <template v-else>
                                <NcActions v-if="!broadcast" :container="container" force-menu>
+                                       <template #icon>
+                                               <BellOffIcon v-if="silentChat" :size="16" />
+                                       </template>
                                        <NcActionButton close-after-click
                                                :name="silentSendLabel"
                                                @click="toggleSilentChat">
```

Normal | Silent
---|---
Bildschirmfoto vom 2024-04-15 14-40-45 | Bildschirmfoto vom 2024-04-15 14-40-49

**Comment by nickvergessen** [comment]
Could then even keep the normal send-icon to reduce complexity

**Comment by Antreesy** [comment]
> How about only doing these simple 3 lines 

If that wasn't a previous requirement to force three-dot there, that sounds like a better option for now

**Review by jancborchardt — COMMENTED** [review]
Suggestion by @nickvergessen sounds good to me, also with keeping the send icon normal (not outline) to reduce complexity as the bell-off icon is already indicating it.

**Review by nickvergessen — APPROVED** [review]
