### PR TITLE
fix(SPLIT): correctly pick the adequate message layout for temporary message

### LINKED ISSUE #16594: [SPLIT VIEW] Jump when short messages are sent
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. enable split view
2. send a short message in any conversation

### Expected behaviour
Message should appear and stay consistent height

### Actual behaviour
loading spinner causes increased height for a brief moment, and when the message is sent the height reduces and causes the rest of the messages to jump 

https://github.com/user-attachments/assets/e7c77e3b-3409-472d-b01b-54074cafdd82

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #16594 

### 🖼️ Screenshots / Screencasts

🏡 After

2026-01-09_10h37_19

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue [hunk 1]
```diff
@@ -314,7 +314,7 @@ export default {
 			return this.message.message.length <= 20 // FIXME: magic number
 				&& !this.message.parent
 				&& !this.isThreadStarterMessage
-				&& this.message.messageParameters.length === 0
+				&& !this.message.messageParameters.length
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessageItem.vue]: This should be `Object.keys(this.message.messageParameters).length === 0`, as messageParameters could be either empty array `[ ]` or an object with data `{ mention-user: { } }`

For temporary messages it falls back to:
```
const messageParameters: ChatMessage['messageParameters'] = {}
```

If we implement fake parameters (e.g. parse mentions from autocomplete), that would be working just fine
