### PR TITLE
Fix(ParticipantsList): Update list when needed

### LINKED ISSUE #10677: Participants count in call inaccurate
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. be in a call with many participants
2. note the total participants number active in the call is incorrect
3.

### Expected behaviour
Call participant count should reflect actual participant count

### Actual behaviour
Here, the participant count (top bar, beside call duration counter) is 3, but clearly there are more participants

273933036-014a6141-267a-4a0e-8367-eb29750e4542

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no
no

**Camera available:** yes/no
no

**Operating system:** Windows/Ubuntu/...
Linux/openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
118.01

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

cloud.nextcloud.com

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10677
The list is always updated unless the participants tab is inactive and there is no call. 

### 🚧 Tasks

- [ ] Code review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/mixins/getParticipants.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ const getParticipants = {
 		},
 
 		debounceUpdateParticipants() {
-			if (!this.isActive) {
+			if (!this.isActive && !this.isInCall) {
```
Comment (nickvergessen) [inline src/mixins/getParticipants.js:82]: but also the `!this.isActive` is problematic.
Should we store the timestamp of the last refresh and in a watcher on `isActive` compare and in case it's "30+ seconds" trigger an update?

Comment (DorraJaouad) [reply src/mixins/getParticipants.js:82]: Changes can happen within 30s and thus they won't be reflected. 
Always triggering an update when isActive becomes true would be better as no actual update happened when the tab is inactive ?

Comment (nickvergessen) [reply src/mixins/getParticipants.js:83]: Looks perfect now!

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Time to fixup
