### PR TITLE
fix(SetContacts ): Remove unnecessary scroll

### LINKED ISSUE #10755: ContactSelectionBubble causes unnecessary scroll
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start to create new conversation
2. Go to the screen with participants selection
3. Add some people

### Expected behaviour
image

### Actual behaviour
image

## Talk app

**Talk app version:** ?? (styles are untouched since March 2020)

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10755

Close Button has height 44px in `ContactSelectionBubble` whereas selected contacts div goes lower ( 40.8px), causing the extra scroll. 

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image  | image  |

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by Antreesy** [comment]
Still issue with 2 lines and more:
image

I remember the issue with 44px, yes =) How about we get rid of NcButton, and put a click event on a whole component?

**Comment by DorraJaouad** [comment]
> Still issue with 2 lines and more:

I thought it is expected with more then one line 

> How about we get rid of NcButton, and put a click event on a whole component?
Hmm, wouldn't that be confusing for the user ?

**Comment by Antreesy** [comment]
> I thought it is expected with more then one line

max-height is 90+px, so 2 lines should be shown without scroll

> Hmm, wouldn't that be confusing for the user ?

I thought we have the same behavior for NcSelect chips as an example, but they have it separately... maybe force a height of NcButton to 22px?

File: src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue [hunk 1]
```diff
@@ -295,5 +296,9 @@ export default {
 	flex: 0 240px;
 	flex: 1 0 auto;
 	align-content: flex-start;
+
+	&__bubble {
+		overflow: hidden;
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue:301]: I think, we could put these styles directly to the component. It's local, so there is nothing to upstream =) 

https://github.com/nextcloud/spreed/blob/main/src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue#L98
