### PR TITLE
fix(LeftSidebar): Disable blur event in order to click on a conversation

### LINKED ISSUE #10734: Filtered conversation -> click on search -> see all -> click on one does ont work
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. apply a filter, e.g. unread, see only 2 conversation
2. click on "search" to see all recent ones
3. click on one

### Expected behaviour
go to it

### Actual behaviour
nothing happens

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10734

### 🖼️ Screenshots / Screencasts

 🏚️ Before  

https://github.com/nextcloud/spreed/assets/84044328/ab3105d8-1aca-492d-adc2-bbe606fe1031   

🏡 After 

   

https://github.com/nextcloud/spreed/assets/84044328/7273a193-46d8-45c7-a7e7-dbe9fc287b92

### 🚧 Tasks

- [ ] Code review
- [ ] Visual review
### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/LeftSidebar/LeftSidebar.vue [hunk 1]
```diff
@@ -142,7 +142,8 @@
 								:conversations="filteredConversationsList"
 								:loading="!initialisedConversations"
 								class="scroller h-100"
-								@scroll.native="debounceHandleScroll" />
+								@scroll.native="debounceHandleScroll"
+								@item-clicked="abortSearch" />
```
Comment (Antreesy) [inline src/components/LeftSidebar/LeftSidebar.vue:146]: I'd listen instead of `<Conversation @click="abortSearch" />` here:

LeftSidebar => `onRouteChange()` =>  `if (to.name === 'conversation')` => `this.abortSearch()`

File: src/components/LeftSidebar/SearchBox/SearchBox.vue [hunk 2]
```diff
@@ -136,16 +136,23 @@ export default {
...
-			} else {
-				this.$emit('blur', event)
-				if (this.value === '') {
-					this.$emit('update:is-focused', false)
-				}
+				return
+			}
+			// Blur triggered by clicking on a conversation item
+			const list = document.querySelector('.left-sidebar__list')
+			if (list && list.contains(event.relatedTarget)) {
```
Comment (Antreesy) [inline src/components/LeftSidebar/SearchBox/SearchBox.vue:149]: list can be a ref, passed as a prop (to not use native JS selectors - can break as depends on class):

```vue
<SearchBox :list="list" />
...
<li ref="list" class="left-sidebar__list">
...
setup() {
  const list = ref(null)
  return { list }
}
```

```suggestion
			if (list?.contains(event.relatedTarget)) {
```

**Review by Antreesy — APPROVED** [review]
