### PR TITLE
fix: use body element if not the fullscreen

### LINKED ISSUE #8709: Device preview prevents call from starting while editing document
Hello devs.

Here is my problem. When opening a never before opened document and enter the chat for that very document via sidebar I cannot start a call because obviousely talk tries to open the device preview window. It works if I go back to talk and disable the "always show preview screen before joining a call in this conversation". Then starting a call works while having the document open.

I was thinking, maybe pop-up windows are disabled in the browser but it shouldn't work then in the talk app, right?

Question: Is it possible to disable the device preview globally?

## Steps to reproduce
1. open a document
2. start a call
3. nothing happens

### Expected behaviour
video call should start

### Actual behaviour
video call does not start

## Talk app

**Talk app version:** 15.0.3

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 22.0.4

**Browser name:** Firefox 109.1 / Chromium

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1

**Nextcloud Version:** 25.0.3

### LINKED ISSUE #9626: File upload dialogue inaccessible when image preview is open during call
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. participate in active call
2. open preview of any previously shared image in chat
3. drag file into chat to upload

### Expected behaviour
Dialogue appears and one is able to confirm the upload.

### Actual behaviour
Confirmation dialogue for upload is hidden behind open preview window and thus not accessible.

## Browser
**Operating system:** Fedora Linux 38

**Browser name:** Firefox

**Browser version:** 113.0

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #8709
* Fix #9626
* Replaces #9792

Should be safe to use a `body` element while you're not in the fullscreen (as tested with ViewerOverlayCallView).
Also as long as we won't register a fullscreen state in sidebar (for Files page, for example), modal will end up in `body`, so above the Viewer embedded

>[!WARNING]
>Behaviour change: as NcModal component has more reasons against being re-mounted, then pros, hotkey 'F' to toggle Fulscreen mode is now disabled when any modal is open https://github.com/nextcloud/spreed/pull/11222/commits/368e43ab158577f367fc7b2a94543c443e7afa50

### 🖼️ Screenshots / Screencasts

| 🖼️  Window frame | 🏞️ Fullscreen |
|------------|----------|
| Files Sidebar          | -        |
Screenshot from 2023-12-13 14-38-32 | Screenshot from 2023-12-13 14-38-55
Screenshot from 2023-12-13 14-38-22 | Screenshot from 2023-12-13 14-38-46
| Talk main app | - |
Screenshot from 2023-12-13 14-36-49 | Screenshot from 2023-12-13 14-37-17
Screenshot from 2023-12-13 14-36-26 | Screenshot from 2023-12-13 14-36-03
Screenshot from 2023-12-13 14-34-50 | Screenshot from 2023-12-13 14-35-02

### 🚧 Tasks

- [ ] Check possible drawbacks?

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]

**Review by DorraJaouad — COMMENTED** [review]
2 things to check : 
* Event propagation where modals are involved ( like @event or v-on )
* CSS dependency ( using :deep to affect a modal style), as the modal may be out of scope.

Otherwise, should be fine.

**Comment by Antreesy** [comment]
> * CSS dependence ( using :deep to affect a modal style), as the modal may be out of scope.

Elements inside `#content-vue` have inherited `box-sizing: border-box`.
Others attached to body - depends in each case

**Comment by Antreesy** [comment]
Fixed for NewMessage in ChatView:

It provides container to children components (EmojiPicker, autocomplete, NcActions) when mounted, and won't update anymore.
So we need to listen to fullscreen change and re-mount component accordingly

**Comment by Antreesy** [comment]
Found a drawback: if you go to Fullscreen with open modal/popover, it will stay attached to the `body` element, thus won't be visible. Freshly opened modals works fine, as they get an actual container value before being mounted
Possible solution: attach `:key="container"` to each modal :eyes:

**Comment by DorraJaouad** [comment]
> Possible solution: attach :key="container" to each modal 

As it is causing re-render only when container changes, sounds like a good solution.

**Comment by Antreesy** [comment]
NcActions works fine, as they're re-rendered and re-mounted each time the container is changed
Looks like this function is triggered each time: https://vuejs.org/api/options-rendering.html#render

https://github.com/nextcloud-libraries/nextcloud-vue/blob/ebbe5c689959fc6470ab79352fd8126d3b98aec2/src/components/NcActions/NcActions.vue#L1215-L1221

File: src/components/TopBar/TopBarMenu.vue [hunk 1]
```diff
@@ -391,6 +391,14 @@ export default {
 		},
 
 		toggleFullscreen() {
+			// Don't toggle fullscreen if there is an open modal
+			if (Array.from(document.body.childNodes).filter(child => {
+				return child.nodeName === 'DIV' && child.classList.contains('modal-mask')
+					&& window.getComputedStyle(child).display !== 'none'
```
Comment (DorraJaouad) [inline src/components/TopBar/TopBarMenu.vue:397]: Looks really non-Vue way because we should tend to query the virtual DOM instead but as modals are now rendered outside Vue hierarchy, this is the shortest way to check their presence.

Comment (DorraJaouad) [reply src/components/TopBar/TopBarMenu.vue:397]: Not sure, but maybe also add a hint why "F" shortkey is not toggling full screen ?

**Review by DorraJaouad — APPROVED** [review]
Nothing is blocking, can't find another drawback.

File: src/components/TopBar/TopBarMenu.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/TopBar/TopBarMenu.vue:397]: Like "showWarning" toast?

Comment (DorraJaouad) [reply src/components/TopBar/TopBarMenu.vue:397]: Exactly

**Review by DorraJaouad — APPROVED** [review]
Approved again

**Comment by DorraJaouad** [comment]
Fixup squash and rebased

**Comment by DorraJaouad** [comment]
@nickvergessen backport to stable27 and stable26 ?

**Comment by nickvergessen** [comment]
My take would be no 🤔

**Comment by nickvergessen** [comment]
@DorraJaouad ^ can you take care of the backport while Maksim is out?
