### PR TITLE
fix(chatManager): Expire unread cache on message delete

### LINKED ISSUE #13286: Unread mention notification does not go away if the message in question has been deleted
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Login as one user, send a direct message to another user.
2. Delete the message.
3. Login as the other user, see the unread mention button
4. Click the button - conversation scrolls down but no unread messages visible.
5. Reload the page - unread mention button still there.

### Expected behaviour
Either the unread mention button should not show
or it should disappear after the scrolling and opening the conversation with the deleted message for the first time.

### Actual behaviour
The unread mention only went away after staying in the conversation in question for a prolonged time (to take a screenshot).

## Talk app

on cloud.nextcloud.com

**Talk app version:** 20.0.0-rc4

## Browser

Firefox

### Browser log
grafik
grafik

## Server configuration

cloud.nextcloud.com

### PR DESCRIPTION
**Pull request by Souptik2001**
### ☑️ Resolves

* Fix #13286 

## Demo -

Before

Just as with the screencast below, the difference is that the unread message doesn't disappear even after refreshing the page.

After

https://github.com/user-attachments/assets/390a6902-f6d7-4aa7-990c-bdab5d7e0995

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [ ] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

---

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Chat/ChatManager.php [hunk 1]
```diff
@@ -521,6 +521,8 @@ public function deleteMessage(Room $chat, IComment $comment, Participant $partic
 
 		$this->referenceManager->invalidateCache($chat->getToken());
 
+		$this->unreadCountCache->clear($chat->getId() . '-');
```
Comment (Souptik2001) [inline lib/Chat/ChatManager.php:524]: Seems like we just had to bust the unread cache on the delete message action. I checked to see if there will be any regression issues due to this seems like no.

As `true` is passed over here -

https://github.com/nextcloud/spreed/pull/13355/files#diff-3f8970573742fb41e3bee92a0f7b7fae33e60043734bcd1171095991c031a6aeR535

therefore the cache is not bust in the `addSystemMessage` function.

**Review by nickvergessen — APPROVED** [review]
