### PR TITLE
Fix empty guest display name

### LINKED ISSUE #817: Guest name empty
Guest name empty in chat when no name has been set.
screen shot 2018-04-26 at 13 00 49

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #817 
After this change https://github.com/nextcloud/spreed/pull/807 we should not check any more for null values.

### CODE REVIEW

File: js/views/chatview.js [hunk 1]
```diff
@@ -321,7 +321,7 @@
 
 			var actorDisplayName = commentModel.get('actorDisplayName');
 			if (commentModel.get('actorType') === 'guests' &&
-				actorDisplayName === null) {
+				actorDisplayName === "") {
```
Comment (nickvergessen) [inline js/views/chatview.js]: single quotes

Comment (Ivansss) [reply js/views/chatview.js]: done 👍
