### PR TITLE
fix(messagesStore) - clean conversation history for participants in call

### LINKED ISSUE #10298: delete chat messages - still visible to 3rd party despite `cleared the history..` indicator
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a rich, 2+ sided text conversation w many messages.
2. User1 (w privileges) chooses to **Delete chat messages - Permanently Delete all messages in this conversation!"
image

3. User2 sees "User1 cleared the history of the conversation", yet no messages are cleared or deleted - all messages remain visible.

### Expected behaviour
Expect all messages for User2 to vanish immediately following User1 choosing to delete all chat messages.

### Actual behaviour
User2 sees "User1 cleared the history of the conversation", yet no messages are cleared or deleted - all messages remain visible.
**EVEN IF** the conversation is reloaded (i.e. within Talk, move to a different conversation, then return). 
Only once User2 moves away from Talk (either selecting a different Nextcloud app, or reloads the page) do the messages vanish.

image

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.0-rc.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
Linux openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
116.0.2

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

Nextcloud's internal tech preview instance 😎 
Nextcloud Hub 6 (27.1.0 beta 2)

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #10298

Solution might be a bit overkill, so here are some explanations:
* System message `history_cleared` will be the first one in conversation by definition, so only previous messages should be cleared
* Depending on internet connection, or after conversation switching - there could be a new messages after clearing, so we can't purge the whole room, because it also could clear new ones.
* When scroll to the top and fetch - system message will be last processed and first known, so no mutations should occur

### 🖼️ Screenshots

[clear-history.webm](https://github.com/nextcloud/spreed/assets/93392545/1e1c1d82-0715-4906-8e0e-30a6807764f2)

### 🚧 Tasks

- [ ] Code review

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/store/messagesStore.js [hunk 1]
```diff
@@ -515,6 +540,13 @@ const actions = {
 			})
 		}
 
+		if (message.systemMessage === 'history_cleared') {
```
Comment (nickvergessen) [inline src/store/messagesStore.js:543]: but what if you just scrolled back in the history until this message, it would drop all chat messages?

Comment (nickvergessen) [reply src/store/messagesStore.js:543]: basically we should only clear older messages

Comment (nickvergessen) [reply src/store/messagesStore.js:543]: Ah, already the case

**Review by nickvergessen — APPROVED** [review]

**Review by DorraJaouad — APPROVED** [review]
Tested ✅
