### PR TITLE
fix(SpeakingWhileMutedWarner): show warning in the popup

### LINKED ISSUE #14029: Make 'speak while muted' a tooltip again
... This used to be a tooltip pointing nicely to the mute/unmute button, would that be possible to do again?
Alternatively, we can shorten the text and include a button:

> You seem to be talking while muted [Unmute]

_Originally posted by @jancborchardt in https://github.com/nextcloud/spreed/pull/14023#pullrequestreview-2514102786_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #14029

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### TODO 
- [x] add timeout to fade notification/popup (if microphone noise is static)
- [x] move visual logic to LocalAudio*
- [x] Check for obstructions (to not show popover above other elements)

### 🏁 Checklist

- [x] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [x] 🖌️ Design was reviewed, approved or inspired by the design team

### CODE REVIEW

File: src/components/TopBar/TopBarMediaControls.vue [hunk 1]
```diff
@@ -43,10 +43,22 @@
...
+			<template #trigger>
+				<LocalAudioControlButton :token="token"
+					:conversation="conversation"
+					:model="model"
+					type="tertiary" />
+			</template>
+			<div class="hint">
+				<span>{{ speakingWhileMutedWarner?.message }}</span>
+			</div>
+		</NcPopover>
```
[the remark this answers is not in the document]
Comment (DorraJaouad) [reply src/components/TopBar/TopBarMediaControls.vue:61]: image

Yeah, we need to prevent showing when there is Media settings, viewer, Poll voting, New coversation modal, conversation/talk settings, poll drafts modal, shared Items modal -> any modal we can open when we are on Talk :)

File: src/utils/webrtc/SpeakingWhileMutedWarner.js [hunk 2]
```diff
@@ -71,40 +72,30 @@ SpeakingWhileMutedWarner.prototype = {
...
-			timeout: TOAST_PERMANENT_TIMEOUT,
-			onClick: () => {
-				this._toast.hideToast()
-			},
-			onRemove: () => {
-				this._toast = null
-			}
-		})
+		this.showPopup = true
 	},
```
Comment (DorraJaouad) [inline src/utils/webrtc/SpeakingWhileMutedWarner.js:96]: No need for this as a function anymore, just use `this.showPopup = true` directly

File: src/utils/webrtc/SpeakingWhileMutedWarner.js [hunk 3]
```diff
@@ -3,37 +3,38 @@
...
+ * @param {object} LocalMediaModel the model that emits "speakingWhileMuted"
+ * events.
+ */
 export default function SpeakingWhileMutedWarner(LocalMediaModel) {
 	this._model = LocalMediaModel
-	this._toast = null
+
+	/** Public properties to use in Vue components */
+	this.message = t('spreed', 'You seem to be talking while muted, please unmute yourself for others to hear you')
+	this.showPopup = null
```
Comment (DorraJaouad) [inline src/utils/webrtc/SpeakingWhileMutedWarner.js:37]: Why do we need 3 separate states (`null`, `false`, `true`)? there is no functional difference between null and false.

File: src/components/TopBar/TopBarMediaControls.vue [hunk 4]
```diff
@@ -43,10 +43,22 @@
 			</NcPopover>
 		</div>
 
-		<LocalAudioControlButton :token="token"
-			:conversation="conversation"
-			:model="model"
-			type="tertiary" />
+		<NcPopover :boundary="boundaryElement"
+			:show-triggers="[]"
+			:hide-triggers="['click']"
```
Comment (DorraJaouad) [inline src/components/TopBar/TopBarMediaControls.vue:48]: Maybe also timeout trigger? For example, if your background is always noisy, it will remain there until you click :(

File: src/utils/webrtc/SpeakingWhileMutedWarner.js [hunk 5]
```diff
@@ -150,15 +142,19 @@ SpeakingWhileMutedWarner.prototype = {
 	_hideWarning() {
```
Comment (Antreesy) [inline src/utils/webrtc/SpeakingWhileMutedWarner.js:142]: Should be called on `destroy()`

**Review by DorraJaouad — APPROVED** [review]
Tested

**Comment by Antreesy** [comment]
removed `{ deep: true }` form watcher
