### PR TITLE
Fix selecting the own screen in the gridview

### LINKED ISSUE #5861: Screenshare controls/flows not working as expected
## Steps to reproduce (scenario 1)
1. Start a call (single user)
2. Share your screen (you see it)
3. Swich to grid view (it's hidden)
4. Open the screenshare menu
5. Click on "Show your screen"

### Expected behaviour
You see your screen

### Actual behaviour
Nothing

## Steps to reproduce (scenario 2)
1. Start a call (single user)
2. Share your screen (you see it)
3. Join with user 2
4. Also share the screen (everyone sees the own screen)
5. As user 2 unshare the screen

### Expected behaviour
Everyone sees screen of user 1

### Actual behaviour
user 1 sees the grid view (although they saw their own screen before)
user 2 sees the screen of user 1 but the bottom row is not collapsed

## Talk app

**Talk app version:** 4974b3d1f7e0bb444dabea963db97e3fb860135f

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5861 

## Steps to reproduce (scenario 1)
1. Start a call (single user)
2. Share your screen (you see it)
3. Swich to grid view (it's hidden)
4. Open the screenshare menu
5. Click on "Show your screen"

### Expected behaviour
You see your screen

### Actual behaviour
Nothing

## Steps to reproduce (scenario 2)
1. Start a call (single user)
2. Share your screen (you see it)
3. Join with user 2
4. Also share the screen (everyone sees the own screen)
5. As user 2 unshare the screen

### Expected behaviour
Everyone sees screen of user 1

### Actual behaviour
user 1 sees the grid view (although they saw their own screen before)
user 2 sees the screen of user 1 but the bottom row is not collapsed

## Talk app

**Talk app version:** 4974b3d1f7e0bb444dabea963db97e3fb860135f

### CODE REVIEW

**Comment by PVince81** [comment]
@nickvergessen this one also looks suspicious: https://github.com/nextcloud/spreed/blob/bugfix/5861/allow-selecting-own-screen-again/src/components/CallView/CallView.vue#L38

File: src/components/CallView/shared/LocalVideo.vue [hunk 1]
```diff
@@ -314,6 +314,10 @@ export default {
 			this.$store.dispatch('selectedVideoPeerId', null)
 			this.$store.dispatch('stopPresentation')
 		},
+
+		switchScreenToId(id) {
+			this.$emit('switch-screen-to-id', id)
```
Comment (PVince81) [inline src/components/CallView/shared/LocalVideo.vue:319]: some day we'll move this to the store so we don't have to pass it around everywhere :city_sunset:

**Review by PVince81 — APPROVED** [review]
:+1:
