### PR TITLE
fix(Participant): remove unneeded separator

### LINKED ISSUE #12922: Unneeded separator in the participant menu
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

image

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #12922

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/RightSidebar/Participants/Participant.vue [hunk 1]
```diff
@@ -222,9 +222,10 @@
 				</NcActionButton>
 			</template>
 
+			<NcActionSeparator v-if="showPermissionsOptions && canBeModerated && isPhoneActor" />
```
Comment (nickvergessen) [inline src/components/RightSidebar/Participants/Participant.vue:225]:
```suggestion
			<NcActionSeparator v-if="canBeModerated && isPhoneActor && showPermissionsOptions" />
```

so it's again "first block && second block"?

**Review by nickvergessen — APPROVED** [review]

File: src/components/RightSidebar/Participants/Participant.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/components/RightSidebar/Participants/Participant.vue:225]: Both directions are the same and clear ?
