### PR TITLE
Hide the talk dashboard widget when the user is not allowed to use talk

### LINKED ISSUE #8232: Do not show Talk widget in dashboard if Talk is disabled for the user
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
When Talk is disabled for a user the Talk widget should not be shown in the dashboard (and it should not be possible to add it either if it was not added already), as the widget never ends loading (and even if it did it would not be possible to open the conversations).

Probably [registering the widget](https://github.com/nextcloud/spreed/blob/23672d4d9d7872757da509baacc74ebd6b2dcc76/lib/AppInfo/Application.php#L147) could be guarded with something like https://github.com/nextcloud/spreed/pull/8231/commits/828aac8982947098ac4fc045f0c1bb107fdad5bc, but maybe there are better/cleaner alternatives, I do not know.

## Steps to reproduce

- Open Talk settings
- Restrict Talk to be used only by certain group
- Log in as a user not in that group
- If not opened by default, open the Dashboard

### Expected behaviour

The `Talk mentions` widget is not shown in the dashboard, nor in the list of available widgets to customize the dashboard

### Actual behaviour

The `Talk mentions` widget is shown in the dashboard and in the list of available widgets to customize the dashboard

### PR DESCRIPTION
**Pull request by nickvergessen**
Currently using a dirty way so we can backport

Fix #8232

### CODE REVIEW

**Comment by nickvergessen** [comment]
Actually this breaks completely due to a bug in the manager:
* https://github.com/nextcloud/server/pull/34831

So we can only do this when 25.0.1 is out and only backport it to stable25

The correct way forward will be possible with a new API in 26+
* https://github.com/nextcloud/server/pull/34832

**Review by danxuliu — APPROVED** [review]
Tested and works :+1: 

However, is https://github.com/nextcloud/server/pull/34831 really needed? As all the exceptions were already caught if loading a widget failed it should not stop the loop over the following widgets. Adding the `continue`s prevent each iteration of the loop to still try further steps on the widget that failed, and therefore avoid further log messages about not being able to load that widget, but it should not affect the following iterations/widgets.

Am I missing something? I tried also with this PR but without https://github.com/nextcloud/server/pull/34831 and the user status widget, which is loaded after Talk mentions, was shown as expected.

**Comment by nickvergessen** [comment]
Oh right, I missed that it catches throwable. So yeah should be fine backporting. Will just spam the logs with error logs of legit normal usecases.

**Comment by nickvergessen** [comment]
So let's merge this then

File: lib/Dashboard/TalkWidget.php [hunk 1]
```diff
@@ -50,12 +54,21 @@ class TalkWidget implements IAPIWidget, IIconWidget, IButtonWidget, IOptionWidge
...
 		IURLGenerator $url,
 		IL10N $l10n,
 		Manager $manager,
 		ParticipantService $participantService,
 		MessageParser $messageParser
 	) {
+		$user = $userSession->getUser();
+		if ($user instanceof IUser && $talkConfig->isDisabledForUser($user)) {
+			// This is dirty and will log everytime a user opens the dashboard or requests the api,
+			// so we should look for a different solution in the server.
```
Comment (vitormattos) [inline lib/Dashboard/TalkWidget.php:68]:
```suggestion
			// @todo This is dirty and will log everytime a user opens the dashboard or requests the api,
			// so we should look for a different solution in the server.
```

Comment (nickvergessen) [reply lib/Dashboard/TalkWidget.php:68]: PR with Api is already there, so once it is reviewed an in we can immediately drop this here again: https://github.com/nextcloud/server/pull/34832

Comment (vitormattos) [reply lib/Dashboard/TalkWidget.php:68]: Is the action to remove this is a to-do, not?

Comment (nickvergessen) [reply lib/Dashboard/TalkWidget.php:68]: Yes should be, but is adding the `@todo` worth the energy to run 2h of CI?
You could instead approve the server PR and if daniel agrees as well we have the 2 thumbs up and we can merge the server PR and I can make the follow up PR to use the correct interface instead of commiting the todo here?

**Review by vitormattos — APPROVED** [review]
