### PR TITLE
fix(ConversationSettings): hide ban section in note to self

### LINKED ISSUE #12880: Hide ban section in settings of Note-to-self
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Maybe there are more special rooms we forgot?

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #12880

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]

File: src/components/ConversationSettings/ConversationSettingsDialog.vue [hunk 1]
```diff
@@ -210,6 +210,7 @@ export default {
 			return this.selfIsOwnerOrModerator
 				&& this.conversation.type !== CONVERSATION.TYPE.ONE_TO_ONE
 				&& this.conversation.type !== CONVERSATION.TYPE.ONE_TO_ONE_FORMER
+				&& this.conversation.type !== CONVERSATION.TYPE.NOTE_TO_SELF
```
Comment (nickvergessen) [inline src/components/ConversationSettings/ConversationSettingsDialog.vue:213]: Let's only allow it in the supported types explicitly
```suggestion
				&& (this.conversation.type === CONVERSATION.TYPE.GROUP
					|| this.conversation.type === CONVERSATION.TYPE.PUBLIC)
```

**Review by nickvergessen — APPROVED** [review]
