### PR TITLE
fix(pin-message): polish styles

### LINKED ISSUE #16775: Pinned messages are not visible enough somehow
List | Bubble
---|---
Image | Image
😐 Float is some what, but not very good visible in "list" layout, as everything is white | 😿 The white floating bubble is even less visible and feels less important than the colored messages
😸 The actual message has a nice primary-based background and a primary pin | 😿 The actual message has a primary pin

---

Quick fix options:
- Add a primary bar like on quotes to the pinned box
- Or full primary boarder
- Make the background primary-based like in the actual chat message in list view
- There should be a small indicator if the message contains an attachment

cc @nimishavijay

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #16775 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image |  image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [ ] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesList.vue [hunk 1]
```diff
@@ -1294,14 +1293,15 @@ export default {
 
 .message__pinned {
 	position: sticky;
-	top: var(--default-grid-baseline);
+	top: 0;
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue]: IMO this needs some gap to maintain the floating effect, especially with the shadow now. It's also kept on Nimisha's screenshots

0px | 4px
-- | --
Image | Image

Also sticky avatars shoudl be adjusted to that height

File: src/components/MessagesList/MessagesList.vue [hunk 2]
```diff
@@ -1294,14 +1293,15 @@ export default {
...
 	margin-inline: auto;
-	width: 86%;
-	max-width: calc($messages-list-max-width * 0.86);
+	max-width: $messages-list-max-width;
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue]: Same here, or it sticks to the sides:


```suggestion
	max-width: min(calc(100% - 2 * var(--default-grid-baseline)), $messages-list-max-width);
```

File: src/assets/variables.scss [hunk 3]
```diff
@@ -16,6 +16,9 @@ $messages-info-width: calc(8ch + var(--clickable-area-small, 24px) + 4 * var(--d
 $messages-list-max-width: calc($messages-avatar-width + $messages-text-max-width + 2 * var(--default-grid-baseline) + $messages-info-width);
 $messages-input-max-width: calc($messages-list-max-width - 100px);
 
+// Pinned message banner height
+$pinned-message-banner-height: 53px;
```
Comment (Antreesy) [inline src/assets/variables.scss]:
```suggestion
$pinned-message-banner-height: calc(2 * var(--default-font-size) * var(--default-line-height) + 2 * var(--default-grid-baseline));
```

File: src/components/MessagesList/PinnedMessage/PinnedMessage.vue [hunk 4]
```diff
@@ -184,6 +189,11 @@ onMounted(() => {
 	}
 }
 
+.pin-icon {
+	padding-inline-start: calc(var(--default-grid-baseline) * 3);
```
Comment (Antreesy) [inline src/components/MessagesList/PinnedMessage/PinnedMessage.vue]: maybe just height: 40px and width: 40px, so it's the avatar size? Feels the same, and text is more aligned with the chat

File: src/components/MessagesList/PinnedMessage/PinnedMessage.vue [hunk 5]
```diff
@@ -196,4 +206,8 @@ onMounted(() => {
 	flex-direction: row;
 	gap: 1px;
 }
+
+:deep(.list-item-content__subname) {
+	color: var(--color-main-text);
```
Comment (Antreesy) [inline src/components/MessagesList/PinnedMessage/PinnedMessage.vue]: Need important or nesting, specificity is too small

File: src/components/MessagesList/PinnedMessage/PinnedMessage.vue [hunk 6]
```diff
@@ -171,6 +164,18 @@ onMounted(() => {
 
 <style scoped lang="scss">
 
+.pin_wrapper:before {
+	content: '';
+    top: 0;
```
Comment (Antreesy) [inline src/components/MessagesList/PinnedMessage/PinnedMessage.vue:169]: Whitespaces...
```suggestion
	top: 0;
```

File: src/stores/chatExtras.ts [hunk 7]
```diff
@@ -71,6 +71,16 @@ export const useChatExtrasStore = defineStore('chatExtras', () => {
...
 	const vuexStore = useStore()
 
+	/**
+	 * Returns whether to show pinned message banner in chat
+	 *
+	 * @param token - conversation token
+	 */
+	function hasPinnedMessageShown(token: string) {
+		const conversation = vuexStore.getters.conversation(token)
+		return conversation?.lastPinnedId && conversation.lastPinnedId !== conversation.hiddenPinnedId
```
Comment (Antreesy) [inline src/stores/chatExtras.ts:81]: Hm. Maybe this should be a getter in conversationsStore?

**Review by Antreesy — APPROVED** [review]
Otherwise good

File: src/stores/chatExtras.ts (hunk 7 above)
Comment (DorraJaouad) [reply src/stores/chatExtras.ts:81]: It belonged more to chatExtras semantically. At least, when you look for it in the future, it would make sense
