### PR TITLE
Bugfix/3130/accessibility labels

### LINKED ISSUE #3130: Missing accessibility labels for all buttons in composer, and more.
## Steps to reproduce
1. With a browser and screen reader such as VoiceOver on Mac or NVDA on Windows, bring up the Talk app and go into a chat.
2. Explore the vicinity of the input box.

### Expected behaviour
Screen reader should be able to identify the input box and the buttons for what they do.

### Actual behaviour
Screen Reader doesn't announce the input box as a textbox, and the buttons all are only announced as "button", but what they do is not spoken.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 74.0.1

### Browser log

<details>
Accessibility Inspector shows the name of all buttons to be "".
</details>

### PR DESCRIPTION
**Pull request by ma12-co**
fix #3130

### CODE REVIEW

**Comment by MarcoZehe** [comment]
@nickvergessen @skjnldsv I approved the accessibility side of things, but if possible, one of you should look over the code style etc. I am not that familiar with Vue itself. Checks have passed, though, so it should be OK to merge. But leaving it up to either of you to make the call.

File: src/components/CallView/LocalMediaControls.vue [hunk 1]
```diff
@@ -196,6 +206,22 @@ export default {
...
+		videoButtonAriaLabel() {
+			if (!this.model.attributes.videoAvailable) {
+				return t('spreed', 'No camera')
+			}
+
+			if (this.model.attributes.videoEnabled) {
+				return t('spreed', 'Disable video')
+			}
+
+			if (!this.model.getWebRtc() || !this.model.getWebRtc().connection || this.model.getWebRtc().connection.getSendVideoIfAvailable()) {
```
Comment (skjnldsv) [inline src/components/CallView/LocalMediaControls.vue]: Seems like this could be a cleaner conditional structure :p

File: src/components/CallView/LocalMediaControls.vue [hunk 2]
```diff
@@ -212,6 +238,14 @@ export default {
 			return (this.model.attributes.localScreen || this.splitScreenSharingMenu) ? t('spreed', 'Screensharing options') : t('spreed', 'Enable screensharing')
 		},
 
+		screenSharingButtonAriaLabel() {
+			if (this.screenSharingMenuOpen) {
+				return ''
+			}
+
+			return (this.model.attributes.localScreen || this.splitScreenSharingMenu) ? t('spreed', 'Screensharing options') : t('spreed', 'Enable screensharing')
```
Comment (skjnldsv) [inline src/components/CallView/LocalMediaControls.vue]:
```suggestion
			return (this.model.attributes.localScreen || this.splitScreenSharingMenu)
				? t('spreed', 'Screensharing options')
				: t('spreed', 'Enable screensharing')
```
Cleaner to me, but personal preferences, I don't know how you do it in talk :man_shrugging:

**Comment by MarcoZehe** [comment]
@nickvergessen @ma12-co Will this be backported to the stable branches somehow? Would be good to get these into people's hands sooner rather than later. I see from above that automatic backporting doesn't seem to work.

**Comment by ma12-co** [comment]
Hello @MarcoZehe, it has been manually backported to stable18 yesterday :)

**Comment by nickvergessen** [comment]
Backport is in #3215
