### PR TITLE
fix(MessagesList): show date separator when div is not scrollable

### LINKED ISSUE #12453: Date separator invisible before reloading the page
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Before reload
336085283-a4fcc4dc-2d13-4b7b-bf0f-a03c30c512b0

After reload
image

## Steps to reproduce
I had a conversation that I hadn't opened in a while. When I sent a new message, the Date separator was invisible.

### Expected behaviour
Date separator shows

### Actual behaviour
Conversation wasn't separated by todays date

## Talk app

**Talk app version:** c.nc
**Custom Signaling server configured:** c.nc
**Custom TURN server configured:** c.nc

**Custom STUN server configured:** c.nc

## Browser

**Microphone available:** yes
**Camera available:** yes
**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 125

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #12453

sticky date value was stored from the previous conversation and applied to the current conversation. 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesList.vue [hunk 1]
```diff
@@ -241,6 +241,10 @@ export default {
 		currentDay() {
 			return moment().startOf('day').unix()
 		},
+
+		isScrollable() {
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:245]: For me value is calculated only once for a long chat. When I switch to the short chat, issue is still persisted

Though approach is correct, we need to trigger it differently. `v-element-resize` is more reliable, but still quirky

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:245]: We can add `this.token` to trigger recalculation on conv switch or add `this.messagesList.length`  to also make sure that the issue won't occur when deleting chat messages.

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:245]: Still happens from time to time =/
image

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:245]: Even with isScrollable faulty ?

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:245]: I'm thinking it needs nextTick to update the chat and it's height anyway

File: src/components/MessagesList/MessagesList.vue [hunk 2]
```diff
@@ -267,6 +267,9 @@ export default {
 			this.$store.dispatch('easeMessageList', { token: oldToken })
 			this.stopFetchingOldMessages = false
 			this.messagesGroupedByDateByAuthor = this.prepareMessagesGroups(this.messagesList)
+			this.$nextTick(() => {
+				this.isScrollable = this.$refs.scroller?.scrollHeight > this.$refs.scroller?.clientHeight
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:271]: Also nextTick should be in `messagesList` watcher, because it depends on its render.
Maybe move this check to `scrollToBottom()` method? It already has nextTick and check for scroller to exist

```js
data() {
	isScrollable: false,
}

File: src/components/MessagesList/MessagesList.vue [hunk 3]
```diff
@@ -267,6 +267,9 @@ export default {
 			this.$store.dispatch('easeMessageList', { token: oldToken })
 			this.stopFetchingOldMessages = false
 			this.messagesGroupedByDateByAuthor = this.prepareMessagesGroups(this.messagesList)
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:269]: Another thing is that we prepareMessagesGroup separately in `token` watcher and `messagesList` watcher. Maybe move it from here, and adjust if block?
```js
// token watcher will handle the conversations change
if (oldMessages?.length && newMessages.length && newMessages[0].token !== oldMessages?.at(0)?.token) {
	// prepare new groups and replace instead
+	this.messagesGroupedByDateByAuthor = this.prepareMessagesGroups(newMessages)
	// also do not skip scrollToBottom, and computation of isScrollable, when switching between loaded chats
-	return
}
```

**Review by Antreesy — APPROVED** [review]
