### PR TITLE
fix(shares): use FilePicker component directly

### LINKED ISSUE #11236: FilePicker doesn't open at FullScreen
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open chat
2. Toggle FullScreen
3. Click on "Share from Nextcloud"
image

### Expected behaviour
FilePicker should be visible

### Actual behaviour
FilePicker is mounted by default at `body`, so same issue as with Viewer
We either can:
- set container with https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/4ec4aa2f22e73e7e7a9a32e90af01cb55a7b0181/lib/filepicker-builder.ts#L134C1-L134C1
- migrate to using a component: https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/main/lib/components/FilePicker/FilePicker.vue

:warning:  Haven't tested with stable27 yet

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #11236
  * For chat attachments: added multiselect

### 🖼️ Screenshots / Screencasts
`picker.setType` is deprecated, but it was responsible for buttons labels => `Choose` everythere

| 🏚️ Before | 🏡 After |
|------------|----------|
| image          | image        |

### 🚧 Tasks

- [ ] Hard to reproduce, but sometimes FilePicker dialog appears behind the main dialog (MediaSettings, ConversationSettings)

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences

### CODE REVIEW

File: src/components/SettingsDialog/SettingsDialog.vue [hunk 1]
```diff
@@ -374,13 +387,19 @@ export default {
...
-			cursor: default;
-		}
+		margin: 0;
+		padding: 10px 6px 10px 12px;
+		border: 2px solid var(--color-border-maxcontrast);
+		border-radius: var(--border-radius-large);
+		background-color: var(--color-main-background);
+		font-size: var(--default-font-size);
+		text-overflow: ellipsis;
+		color: var(--color-main-text);
```
Comment (DorraJaouad) [inline src/components/SettingsDialog/SettingsDialog.vue:400]: not needed

File: src/components/SettingsDialog/SettingsDialog.vue [hunk 2]
```diff
@@ -268,30 +286,25 @@ export default {
...
-					this.attachmentFolderLoading = false
-				})
+			this.attachmentFolderLoading = true
+			try {
+				this.$store.dispatch('setAttachmentFolder', path)
+			} catch (exception) {
+				showError(t('spreed', 'Error while setting attachment folder'))
+			}
+			this.attachmentFolderLoading = false
+			this.showFilePicker = false
```
Comment (DorraJaouad) [inline src/components/SettingsDialog/SettingsDialog.vue:307]: This is not needed by the way, because close event is emitted

**Review by DorraJaouad — APPROVED** [review]
Tested, nothing is blocking.

File: src/components/SettingsDialog/SettingsDialog.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/SettingsDialog/SettingsDialog.vue:400]: Only color or all of these styles? I tried to fake input appearance, to not import NcTextField component for that

Comment (DorraJaouad) [reply src/components/SettingsDialog/SettingsDialog.vue:400]: Only color
