### PR TITLE
fix(shares): use `nextcloud/upload` to track upload progress

### LINKED ISSUE #11153: webdav doesn't support upload progress since v5
Reference: https://github.com/perry-mitchell/webdav-client/blob/master/CHANGELOG.md#v500

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #11153 
  * add `nextcloud/upload` library to perform file uploads to server
  * attach uploadManager data to track common upload progress
* Split large `uploadFiles` action into 4 smaller manageable actions
* update NcProgressBar styles (so it won't affects scroller height and chat jumping)

### 🖼️ Screenshots / Screencasts

image

https://github.com/nextcloud/spreed/assets/93392545/21a3ad37-cbe9-463e-bcdb-8e93fc620903

### 🚧 TODO

- [x] track upload progress for each single file
- [x] test coverage

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible

### CODE REVIEW

**Comment by Antreesy** [comment]
Possible style variation with circular progress (could be combined with loading spinner):

image

cc @nextcloud/designers

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue [hunk 1]
```diff
@@ -534,6 +538,31 @@ export default {
 		},
 	},
 
+	watch: {
+		isTemporaryUpload: {
+			immediate: true,
+			handler(value) {
+				this.uploadManager = value ? getUploader() : null
+			}
+		},
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:547]: It is temporary only in the beginning, why don't you call getUploader() when on mounted ? 
and you can remove it once upload is finished

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue [hunk 2]
```diff
@@ -534,6 +538,31 @@ export default {
...
+			deep: true,
+			handler(value) {
+				if (!value) {
+					return
+				}
+				const progress = value._uploaded / value._size * 100
+				this.uploadProgress = Math.max(this.uploadProgress, progress)
+			}
+		}
+	},
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:564]: This can be computed

```js
   uploadProgress() {
                                if (!this.upload) {
					return 100
				}
				return  this.upload._uploaded / this.upload._size * 100

		}
```

Unless ._uploaded is not progressing in one direction ( gets higher and then lower) or computed can't detect in depth object change here too despite we are using its attributes.

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:547]: Maybe a better idea, also helps to not create the uploadManager for dialog window

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:564]: It could fall back to 0 when upload got removed from the queue, but I will see what could be done

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:564]: Here is the lifecycle of upload:
```
(File) (fileUpload.status) (upload._progress/upload._size)
FilePreview.vue:379 initialised undefined
FilePreview.vue:379 pendingUpload undefined
FilePreview.vue:379 uploading 0
FilePreview.vue:379 uploading 0.025629074670996455
FilePreview.vue:379 uploading 0.05125814934199291
...
FilePreview.vue:379 uploading 0.9739048374978653
FilePreview.vue:379 uploading 0.9995339121688618
FilePreview.vue:379 uploading 1
FilePreview.vue:379 uploading undefined // progressBar shows 0 at this point, and it takes a while
FilePreview.vue:379 successUpload undefined
FilePreview.vue:379 sharing undefined
FilePreview.vue:379 shared undefined
```

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue]: We can condition showing progressBar only if uploadProgress is not undefined. This means that this part is not included in the progress state :
`FilePreview.vue:379 uploading undefined // progressBar shows 0 at this point, and it takes a while`

Which makes sense because it is actually uploaded but fileUpload.status hasn't been updated yet ?

**Comment by Antreesy** [comment]
Rebased, updated style of NcProgressBar to `circular`

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue [hunk 3]
```diff
@@ -50,6 +50,11 @@
 				:class="previewImageClass"
 				alt=""
 				:src="defaultIconUrl">
+			<NcProgressBar v-if="showUploadProgress"
+				class="file-preview__progress"
+				type="circular"
+				:size="56"
+				:value="uploadProgress" />
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:57]: Maybe it is good to reduce the opacity of the file icon behind or add transparent white layer with the progressBar.

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:57]: Thought about that 👍

**Comment by Antreesy** [comment]
Another proposal for progress circle placement (where the spinner/checkmark is usually):
image

Whic option can we stick with, @marcoambrosini ?

**Review by marcoambrosini — COMMENTED** [review]
@Antreesy would it be possible to put it to the left of the title? 

In the first option there's not enough contrast with the background and the shapes below make it a bit confusing, while in the second option I fear that the indicator might be too far from the title and icon.

**Comment by Antreesy** [comment]
@marcoambrosini If you're not ready to come up quickly with a solution, we could split out the design changes into follow-up and merge only library + code for now

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue [hunk 4]
```diff
@@ -648,6 +657,13 @@ export default {
 		transition: outline 0.1s ease-in-out;
 	}
 
+	&__progress {
+		position: absolute;
+		top: 50%;
+		right: 0;
+		transform: translate(100%, -50%);
+	}
+
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:666]: `display: inline-flex` didn't work out ?

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue:666]: Could cause some issues with image resizing

**Review by DorraJaouad — APPROVED** [review]
Tested 🦅
