### PR TITLE
fix(CallView): freeze promoted video on hover

### LINKED ISSUE #12631: Speaker view should not change when hovering icons
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
grafik

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #12631

### 🖼️ Screenshots / Screencasts

🏚️ Before (hovered)| 🏡 After (hovered)
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

---

### CODE REVIEW

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 1]
```diff
@@ -11,7 +11,10 @@
 			</div>
 		</TransitionWrapper>
 
-		<div v-if="!isSidebar" class="bottom-bar">
+		<div v-if="!isSidebar"
+			class="bottom-bar"
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:15]: That's quite a small area to catch:
image

I thought about freezing the whole promoted VideoVue on hover. It already has a logic for that (and styles, but they're disable for `isBig`, and I'd revert it to provide feedback)

File: src/components/CallView/shared/VideoVue.vue [hunk 2]
```diff
@@ -588,6 +589,10 @@ export default {
 				// Fallback for Firefox
 				?? this.$refs.video.videoWidth / this.$refs.video.videoHeight
 		},
+
+		handleHoverEvent(event) {
+			this.$emit('force-promote-video', { promoted: event, model: this.model })
+		}
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoVue.vue:595]: Should be enough?

```suggestion
	watch: {
		mouseover(value) {
			if (!this.isBig) {
				return
			}
			this.$emit('force-promote-video', value ? this.model : null )
		}
	},
```

File: src/components/CallView/shared/VideoBottomBar.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/components/CallView/shared/VideoBottomBar.vue:15]: That would be a large area from the screen and probability that the mouse is just there is high

Comment (Antreesy) [reply src/components/CallView/shared/VideoBottomBar.vue:15]: So fine? If user sees that it's hovered
Or we add some complex logic with timeout, like video players have

Comment (DorraJaouad) [reply src/components/CallView/shared/VideoBottomBar.vue:15]: > So fine? If user sees that it's hovered

That means, it could be easily hovered randomly (user left the mouse there) and now the actual speaker doesn't show up anymore.

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 3]
```diff
@@ -278,17 +298,28 @@ export default {
...
 		& .bottom-bar {
 			width: unset;
+			padding: 0 4px;
 		}
+
 		& .participant-name {
 			margin-right: 0;
 		}
+
+		&:hover {
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:317]: Feels a bit counter-intuitive, so the whole line is now freezing the model, but feedback is only on smaller part.
Maybe, we keep `@mouseover` on the bottom-bar, as it was initially, and increase it's padding?

wrapper | bottombar
-- | --
image | image
image | image

File: src/components/CallView/shared/VideoVue.vue [hunk 4]
```diff
@@ -588,6 +589,10 @@ export default {
 				// Fallback for Firefox
 				?? this.$refs.video.videoWidth / this.$refs.video.videoHeight
 		},
+
+		handleHoverEvent(event) {
+			this.$emit('force-promote-video', { promoted: event, model: this.model })
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoVue.vue:594]:
```suggestion
		handleHoverEvent(value) {
			this.$emit('force-promote-video', value ? this.model : null)
```

File: src/components/CallView/CallView.vue [hunk 5]
```diff
@@ -76,7 +76,8 @@
 						fit-video
 						is-big
 						:is-one-to-one="isOneToOne"
-						:is-sidebar="isSidebar" />
+						:is-sidebar="isSidebar"
+						@force-promote-video="updateForcePromoted" />
```
Comment (Antreesy) [inline src/components/CallView/CallView.vue:80]:
```suggestion
						@force-promote-video="forcePromotedModel = $event" />
```

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 6]
```diff
@@ -247,6 +258,15 @@ export default {
 		},
 	},
 
+	watch: {
+		mouseover(value) {
+			if (!this.isBig) {
+				return
+			}
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:265]: theoretically, this can be and should be checked on a VideoVue level (if we ever wanted to apply a freeze on a Stripe/Grid)

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 7]
```diff
@@ -278,17 +298,28 @@ export default {
...
+	padding: 0 12px 4px 12px;
 	z-index: 1;
 
 	&--big {
 		justify-content: center;
+		margin: 0 var(--default-clickable-area); // grid collapse button
+		width: calc(100% - var(--default-clickable-area) * 2);
 		& .bottom-bar {
 			width: unset;
+			padding: 0 4px;
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:310]:
```suggestion
			padding: calc(var(--default-grid-baseline) * 2);
```

File: src/components/CallView/shared/VideoBottomBar.vue (hunk 3 above)
Comment (DorraJaouad) [reply src/components/CallView/shared/VideoBottomBar.vue:317]: It was indented, so to have more area to apply freeze as you mentioned it's a small area initially and user can miss it. I will revert to the initial state.

File: src/components/CallView/shared/VideoBottomBar.vue (hunk 6 above)
Comment (DorraJaouad) [reply src/components/CallView/shared/VideoBottomBar.vue:265]: I wouldn't apply the freeze too much on the call view ? It's not much needed in grid or stripe as much as in speaker view because in the latter, tile will change on each speaking signal coming in chronologically whereas in the other view, the move is only on the first speaking signal of each speaker and they remain in the same position in first page until they mute their mic. 

Also, it can happen that user lays the cursor on the bottom bar of a tile for a while and many changes took place (a lot of participants spoke and order changed). Once they move it away, the view can jump oddly.

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 8]
```diff
@@ -4,14 +4,18 @@
...
+		:class="{'wrapper--big': isBig}"
+		@mouseover.stop="mouseover = true"
+		@mouseleave.stop="mouseover = false">
 		<TransitionWrapper name="fade">
 			<div v-if="showRaiseHandIndicator" class="status-indicator raiseHandIndicator">
 				<HandBackLeft :size="18" fill-color="#ffffff" />
 			</div>
 		</TransitionWrapper>
 
-		<div v-if="!isSidebar" class="bottom-bar">
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:14]: revert to one-line or bring back mouseover listeners here?
Still weird for me to have this 50px-high freeze line, but it's your call =)

File: src/components/CallView/shared/VideoBottomBar.vue [hunk 9]
```diff
@@ -278,14 +299,23 @@ export default {
 	position: absolute;
 	bottom: 0;
 	width: 100%;
-	padding: 0 12px 8px 12px;
+	padding: 0 12px 4px 12px;
```
Comment (Antreesy) [inline src/components/CallView/shared/VideoBottomBar.vue:302]: variables. and maybe reduce padding on the sides?

```suggestion
	padding: 0 calc(var(--default-grid-baseline) * 2) var(--default-grid-baseline);
```

**Review by Antreesy — APPROVED** [review]

File: src/components/CallView/shared/VideoBottomBar.vue (hunk 8 above)
Comment (DorraJaouad) [reply src/components/CallView/shared/VideoBottomBar.vue:14]: so you are suggesting to reduce the height here or what ? I am a bit confused 🙈

Comment (Antreesy) [reply src/components/CallView/shared/VideoBottomBar.vue:14]: Just revert a change on this line

**Review by marcoambrosini — APPROVED** [review]
