### PR TITLE
Adjust viewer and sidebar to changes in Nextcloud 22

### LINKED ISSUE #5810: Viewer doesn't open anymore in the chat
Ref https://github.com/nextcloud/spreed/pull/3665#issuecomment-864907332

## Steps to reproduce
1. Upload an image to the chat
2. Try to open the image

### Expected behaviour
Image opens

### Actual behaviour
```
Uncaught (in promise) TypeError: OCA.Files.Sidebar.setFullScreenMode is not a function
    e Viewer.vue:369
    u talk-main.js:1
    _invoke talk-main.js:1
    b talk-main.js:1
    S viewer-main.js:2
    a viewer-main.js:2
    F viewer-main.js:2
    F viewer-main.js:2
    openFile Viewer.vue:357
    file Viewer.vue:277
    VueJS 5
```

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #5810 

In Nextcloud 22 [`setFullScreenMode()` was added to `OCA.Files.Sidebar`](https://github.com/nextcloud/server/blob/c03a14934b543c6734e5458f814997e419cf808b/apps/files/src/sidebar.js#L61). That method [is expected and used by the viewer](https://github.com/nextcloud/viewer/blob/eba1a1bd3240ad825cd324254871438bebf0d587/src/views/Viewer.vue#L369), so it needs to be there even if the sidebar style is not changed to put it in full screen mode.

Besides that, in Nextcloud 22 [the viewer also reacts to `files:sidebar:opened` and `files:sidebar:closed` events](https://github.com/nextcloud/viewer/blob/eba1a1bd3240ad825cd324254871438bebf0d587/src/views/Viewer.vue#L343-L344) to adjust its width based on the sidebar.

At least for me the "opened" event from `AppSidebar` component does not seem to work reliably (it seems that sometimes in Firefox it is emitted before the sidebar has finished opening, so the viewer ends overlapping the sidebar due to getting its width when it is not fully opened), so for now the custom detection of when the sidebar has finished opening is still used.

Follow ups:
- Adjust the sidebar style to cover the top bar when the viewer is opened? Personally in Talk I would prefer not to alter the sidebar style when the viewer is opened, but fine by me too if you prefer the full screen mode.
- Investigate why emitting the `opened` event directly in the `RightSidebar` based on `AppSidebar` events is unreliable. Is it an issue with how it is done in Talk? Or is it an issue in the `AppSidebar` component?

## How to test
- Upload an image to the conversation
- Click on the image to open the viewer

### Result with this pull request
The viewer is opened. Closing and opening the sidebar again from the viewer works as expected too.

### Result without this pull request
The viewer is not opened.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: tested, works

can we have a tech debt ticket to adjust the general approach to be cleaner ?

File: src/main.js [hunk 1]
```diff
@@ -160,6 +167,10 @@ Sidebar.prototype.close = function() {
 	store.dispatch('hideSidebar')
 	this.state.file = ''
 }
+Sidebar.prototype.setFullScreenMode = function(isFullScreen) {
+	// Sidebar style is not changed in Talk when the viewer is opened; this is
+	// needed only for compatibility with OCA.Files.Sidebar interface.
```
Comment (nickvergessen) [inline src/main.js:172]: 🙈

**Review by nickvergessen — APPROVED** [review]
Works and solves the issue.

But I guess skj will not be happy
