### PR TITLE
fix(auth): migrate authenticate.php to use vue-based form

### LINKED ISSUE #17192: [Bug]: TALK - Guest access with Link+Password no reaction at guest login page
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud version: 33.0.0
Talk app version: 23.0.1
Talk hpb backend: 2.1.0~docker

Bug on endpoints:
Chrome (Windows)
Edge (Windows)
Firefox (Android)

### Steps to reproduce

1. Create a new meeting in Talk
2. Set option with link and password in guest access
3. open link and enter password -> no reaction

### Expected behavior

Entering

### Nextcloud Server version

33

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.jungundjung.org"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "33.0.0.16",
        "overwrite.cli.url": "https:\/\/cloud.jungundjung.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "default_phone_region": "CH",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-aarch64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-aarch64",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie"
        ],
        "memories.vod.disable": false,
        "memories.vod.ffmpeg": "\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/bin\/ffprobe",
        "memories.gis_type": 2,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 6.0.0-dev.0
  - admincockpit: 1.1.7
  - analytics: 6.1.0
  - app_api: 33.0.0
  - bruteforcesettings: 6.0.0-dev.0
  - calendar: 6.2.0
  - checksum: 2.0.3
  - circles: 33.0.0
  - cloud_federation_api: 1.17.0
  - comments: 1.23.0
  - contacts: 8.3.3
  - contactsinteraction: 1.14.1
  - cookbook: 0.11.6
  - dashboard: 7.13.0
  - dav: 1.36.0
  - deck: 1.17.0
  - federatedfilesharing: 1.23.0
  - federation: 1.23.0
  - files: 2.5.0
  - files_3dmodelviewer: 0.0.16
  - files_downloadlimit: 5.1.0-dev.0
  - files_external: 1.25.1
  - files_pdfviewer: 6.0.0-dev.0
  - files_reminders: 1.6.0
  - files_sharing: 1.25.2
  - files_trashbin: 1.23.0
  - files_versions: 1.26.0
  - firstrunwizard: 6.0.0-dev.0
  - forms: 5.2.4
  - gpoddersync: 3.16.0
  - gpxpod: 8.1.0
  - libresign: 13.0.2
  - logreader: 6.0.0
  - lookup_server_connector: 1.21.0
  - mail: 5.7.0
  - nextcloud_announcements: 5.0.0
  - notes: 4.13.0
  - notifications: 6.0.0
  - notify_push: 1.3.0
  - oauth2: 1.21.0
  - password_policy: 5.0.0-dev.0
  - photos: 6.0.0-dev.0
  - previewgenerator: 5.12.1
  - privacy: 5.0.0-dev.0
  - profile: 1.2.0
  - provisioning_api: 1.23.0
  - recommendations: 6.0.0-dev.0
  - registration: 2.9.0
  - related_resources: 4.0.0-dev.0
  - repod: 4.0.0
  - richdocuments: 10.1.0
  - serverinfo: 5.0.0-dev.0
  - settings: 1.16.0
  - sharebymail: 1.23.0
  - socialsharing_whatsapp: 4.0.1
  - spreed: 23.0.1
  - support: 5.0.0
  - survey_client: 5.0.0-dev.0
  - suspicious_login: 11.0.0-dev.0
  - systemtags: 1.23.0
  - talk_matterbridge: 1.33.1026000
  - tasks: 0.17.1
  - text: 7.0.0-dev.3
  - theming: 2.8.0
  - twofactor_backupcodes: 1.22.0
  - twofactor_nextcloud_notification: 7.0.0
  - twofactor_totp: 15.0.0-dev.0
  - updatenotification: 1.23.0
  - uppush: 2.4.0
  - user_status: 1.13.0
  - viewer: 6.0.0-dev.0
  - weather_status: 1.13.0
  - webhook_listeners: 1.5.0
  - whiteboard: 1.5.6
  - workflowengine: 2.15.0
Disabled:
  - admin_audit: 1.23.0
  - drawio: 3.1.2 (installed 3.1.2)
  - electronicsignatures: 3.0.6 (installed 3.0.6)
  - encryption: 2.21.0
  - integration_youtube: 0.6.1 (installed 0.6.1)
  - mail_roundcube: 1.2.2 (installed 1.2.2)
  - memories: 7.8.2 (installed 7.8.2)
  - metadata: 0.23.0 (installed 0.23.0)
  - music: 2.5.1 (installed 2.5.1)
  - passwords: 2025.12.21 (installed 2025.12.21)
  - riotchat: 0.20.0 (installed 0.20.0)
  - user_ldap: 1.24.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => cb945c6402e12d9e7d42d0359acf95a6e9a9b0c1f3bd8528f598a7fb1694e5ae34c80cf44ef6c8901eac1bfdd152de3315fc7eac007efee0f33f09ed3e518b6a
                            [current] => 6b290ba45e633706e1fe761ca21422053c113f17b2bb35f2351f2cf1c3b893aa543af6c594077ca213c755cfa0d002e22109bb1797bbadd8fb410ca839143e0e
                        )

                )

        )

)
```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #17192
* Mostly copied https://github.com/nextcloud/server/pull/57571 at least to match up in terms of using vue components
* New endpoint is 70 kB size 🏋🏽 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
2026-02-26_17h16_47 | 2026-02-26_17h17_49
Errors and warnings | Translations
2026-02-26_17h17_25 | 2026-02-26_17h30_43
Video verification | Failed request to Talk
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

---

### 🚧 Tasks

- [ ] ??

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not possible
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

File: templates/authenticate.php [hunk 1]
```diff
@@ -6,32 +6,16 @@
...
-					placeholder="<?php p($l->t('Password')); ?>" value=""
-					autocomplete="new-password" autocapitalize="off" autocorrect="off"
-					autofocus />
-				<input type="submit" id="password-submit"
-					class="svg icon-confirm input-button-inline" value="" disabled="disabled" />
-			</p>
-		</fieldset>
-	</form>
-</div>
+<div class="hidden-visually"><?php p($l->t('This conversation is password-protected.')); ?></div>
```
Comment (DorraJaouad) [inline templates/authenticate.php:20]: You removed half of the condition tree (wrong password), it is fine to remove this div as well

File: templates/authenticate.php [hunk 2]
```diff
@@ -6,32 +6,16 @@
  * SPDX-License-Identifier: AGPL-3.0-or-later
  */
 
-/** @var array $_ */
 /** @var \OCP\IL10N $l */
-\OCP\Util::addStyle('core', 'publicshareauth');
-\OCP\Util::addScript('core', 'publicshareauth');
+/** @var array{share: \OCP\Share\IShare, identityOk?: bool, wrongpw?: bool} $_ */
+\OCP\Util::addStyle('spreed', 'talk-public-share-auth-form');
```
Comment (DorraJaouad) [inline templates/authenticate.php:11]: Do we have it?

File: templates/authenticate.php [hunk 3]
```diff
@@ -6,32 +6,16 @@
...
+\OCP\Util::addScript('spreed', 'talk-public-share-auth-form');
+
+$initialState = \OCP\Server::get(\OCP\IInitialStateService::class);
+$initialState->provideInitialState('spreed', 'talk-public-share-auth', [
+	'showBruteForceWarning' => $_['showBruteForceWarning'] ?? null,
+	'wrongpw' => $_['wrongpw'] ?? null,
```
Comment (DorraJaouad) [inline templates/authenticate.php:17]:
```suggestion
	'wrongPassword' => $_['wrongPassword'] ?? null,
```

File: templates/authenticate.php (hunk 1 above)
Comment (Antreesy) [reply templates/authenticate.php:20]: Was requested by Joas to keep it for security / bruteforce CI

File: templates/authenticate.php (hunk 2 above)
Comment (Antreesy) [reply templates/authenticate.php:11]: Yes, when complied, vue component is split in JS and CSS (that included vue library styles as well)

File: templates/authenticate.php (hunk 3 above)
Comment (Antreesy) [reply templates/authenticate.php:17]: I can change the key name for Vue component, by `$_['wrongpw']` might be returned by server core, so I'm not messing with it
