### PR TITLE
Fix chat "not loading" and performance issue with many reactions or v…

### LINKED ISSUE #8289: Many reactions in a row can break the chat
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
Sample conversation was created on sermo

1. Create a set of message `/spam 50 messages`
2. Write a test message (`This one has the reactions`)
3. Open the reaction emoji picker on the previous message and run this code in your JS console:
```js
[...document.querySelectorAll('.emoji-mart-emoji')].forEach(input => input.click())
```
4. Waiting some time for the 1.868 requests to finish
5. Write another chat message (`Empty chat?`)
6. Reload the web UI

### Expected behaviour
Chat should be readable

### Actual behaviour
- [ ] Web UI chat does not load further and browser becomes unresponsive for the author
- [ ] Android chat does not load further
- [ ] iOS app freezes

### PR DESCRIPTION
**Pull request by nickvergessen**
…otes

Fix #8289

### CODE REVIEW

File: src/store/messagesStore.js [hunk 1]
```diff
@@ -796,6 +798,15 @@ const actions = {
 
 		context.commit('loadedMessagesOfConversation', { token })
 
+		if (invisibleMessages > 95) {
+			// If there are more than 95 invisible messages we load another chunk
```
Comment (ShGKme) [inline src/store/messagesStore.js:802]: `95` seems to be a magic number for me here. If I understand correctly, that is because default limit of chunk is 100 messages and the problem occurs when a whole chunk consists only of "invisible messages". Currently web client never sets the limit and always uses default, so limit does not occur on client side.

What about adding a constant like `DEFAULT_FETCH_MESSAGES_LIMIT`?

Comment (nickvergessen) [reply src/store/messagesStore.js:802]: > and the problem occurs when a whole chunk consists only of "invisible messages"

Not only, but yeah then you get the "numb" feeling. But also if it loads for a long time and then only one message shows and you have to scroll down and up again it is weird.

Comment (ShGKme) [reply src/store/messagesStore.js:802]: Oh, I see now. So then I'd prefer to add 2 constants for this place to be clean.
Something like `DEFAULT_FETCH_MESSAGE_LIMIT = 100` and `MIN_PREFERED_FETCH_VISIBLE_MESSAGES = 5`.
Or at least a comment with description / link to issue, so it will be no magic in 95...

> if it loads for a long time and then only one message shows and you have to scroll down and up again it is weird

Maybe then require 20-25 messages instead of 5? It is approximate amount of messages takes up the whole 4K screen forcing user to scroll up for previous messages.

Comment (ShGKme) [reply src/store/messagesStore.js:802]: There is also a hard but strict way - fetch messages and count visible messages continuously until  there will be 100 visible messages or messages ends. (Or even do this part on server side). But not sure it's worth it =D

Comment (nickvergessen) [reply src/store/messagesStore.js]: Made a change that should improve the situation

**Review by marcoambrosini — APPROVED** [review]
looks good!

**Review by ShGKme — APPROVED** [review]
Thanks for adding constants :)
