### PR TITLE
fix: do not leave room session from duplicated session tab

### LINKED ISSUE #15116: Closing tab on duplicated session messages ends call
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Be in a call
2. Open the same conversation in a second tab
3. See the "Duplicate session" dialog
4. Close the tab again / Press "Leave page"

### Expected behaviour
Call still works

### Actual behaviour
Call is ended in the first tab

## Talk app

**Talk app version:** 21.1. RC2

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #15116
  * `spawnDialog` handles 'yes', 'no' and 'close dialog' cases correctly, but not the page unload
  * If I get it correctly, we are denied to join the room on a second tab and ask user for confirmation. That means:
    * First tab has an active Nextcloud session
    * First tab has connected signaling session
  * If we close tab, 'unload' event triggers signaling kill and ⚠️ leave conversation request, which aborts the call on the first tab

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/composables/useSessionIssueHandler.js [hunk 1]
```diff
@@ -46,6 +56,31 @@ export function useSessionIssueHandler() {
 		}
 	}
 
+	const handleSessionConflict = (token) => {
+		spawnDialog(ConfirmDialog, {
```
Comment (ShGKme) [inline src/composables/useSessionIssueHandler.js]: Note: `spawnDialog` now supports Promise API. When a callback is not provided, it returns a promise resolved with the result

File: src/composables/useSessionIssueHandler.js [hunk 2]
```diff
@@ -48,7 +48,7 @@ export function useSessionIssueHandler() {
 				// FIXME: can't use router push as it somehow doesn't clean up
 				// fully and leads the other instance where "Join here" was clicked
 				// to redirect to "not found"
-				window.location = generateUrl(url)
+				window.location.replace(generateUrl(url))
```
Comment (ShGKme) [inline src/composables/useSessionIssueHandler.js]: Could you describe this change?

File: src/composables/useSessionIssueHandler.ts [hunk 3]
```diff
@@ -4,6 +4,7 @@
  */
 
 import { nextTick, onBeforeMount, onBeforeUnmount, readonly, ref } from 'vue'
+import type { Readonly, Ref } from 'vue'
```
[the remark this answers is not in the document]
Comment (ShGKme) [reply src/composables/useSessionIssueHandler.ts:7]: `Readonly` is TS's utility type

**Review by ShGKme — APPROVED** [review]

File: src/composables/useSessionIssueHandler.js (hunk 2 above)
Comment (Antreesy) [reply src/composables/useSessionIssueHandler.js]: 1. TS was complaining at the new value type
2. location.replace won't be saved in history, so user can't go back to the conflicting route
3. More clear from the method, that we want to trigger a page reload

File: src/composables/useSessionIssueHandler.js (hunk 1 above)
Comment (Antreesy) [reply src/composables/useSessionIssueHandler.js]: Vue3 only.. I'll leave a FIXME comment

**Review by DorraJaouad — APPROVED** [review]
Tested
