### PR TITLE
Remove chat when leaving active room

### LINKED ISSUE #626: Leaving/deleting the current room still shows chat
## Steps to reproduce
1. Create public room
2. Leave public room
3. Write something in the chat that is still visible

### Expected behaviour
Either the chat should no longer be visible, or there should be no way to write anything.

### Actual behaviour
A notification is shown that the message could not be sent.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #626 

The fixme from signaling.js should be done in a new PR

### CODE REVIEW

File: js/views/roomlistview.js [hunk 1]
```diff
@@ -191,19 +187,23 @@
...
-
+			this.exitingActiveRoom();
 			this.$el.slideUp();
 
 			$.ajax({
 				url: OC.linkToOCS('apps/spreed/api/v1/room', 2) + this.model.get('token'),
 				type: 'DELETE'
 			});
 		},
+		exitingActiveRoom: function() {
```
Comment (fancycode) [inline js/views/roomlistview.js]: Maybe rename this to `cleanupIfActiveRoom` or similar? The current name sounds like an event handler that is called when the active room is left. This will also make code clearer at the locations from where it is called.
