### PR TITLE
Make sure users with numerical user ids/display names still show as u…

### LINKED ISSUE #664: Participants with  numerical id shown as "(?) Guest"
## Steps to reproduce
1. As admin, create a user with a numerical  id, e.g. "12345"
2. Invite the user to a call

### Expected behaviour

The user is shown as any regular user in the particpiants list

### Actual behaviour

The participant is represented as "(?) Guest":

screenshot_20180215_132838

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Antergos

**Browser name:** Firefox

**Browser version:** 58.0.2

## Spreed app

**Spreed app version:** git master

**Custom TURN server configured:** no

**Custom STUN server configured:** no 

## Server configuration

**Operating system**: Antergos

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2.2

**Nextcloud Version:** git master

cc @nextcloud/talk

### PR DESCRIPTION
**Pull request by nickvergessen**
…sers
Fix #664 

To test, set the display name of user `123456` to `123456` :boom: 
with this branch we:

1. check against the userId instead of the display name
2. make sure an int userId does not gail

### CODE REVIEW

File: js/views/participantlistview.js [hunk 1]
```diff
@@ -131,8 +131,10 @@
 			},
 			onRender: function() {
 				this.$el.find('.avatar').each(function() {
-					var element = $(this);
-					if (element.data('displayname').length) {
```
Comment (nickvergessen) [inline js/views/participantlistview.js]: this compared the display name instead of the user id and also data returns "numbers" as "int" and int.length is undefined....
