### PR TITLE
fix(MessagesList): fix resizeObserver and scrolledToBottom state update

### LINKED ISSUE #14392: Typing a message invokes the scroll indicator, and prevents the other party's next message from auto scrolling into view
In a Talk chat, scrolling up invokes the double-down-chevron indicator, to show that we are not at the bottom of the chat. Any new messages from the other party will not be auto scrolled into view until I scroll down or click the indicator to go back to the bottom. This is as expected.

However, often the indicator appears as a result of me typing my own message. Everything (so far) is still in view, but the chat now thinks it's not fully scrolled - so won't auto scroll a reply from the other party into view. When this happens, I need to either scroll up+down, or click the indicator, to ensure the next reply appears. It's easy to miss this and thus miss a reply.

This seems random, I can't pin it down to anything. Reproducible on 2 different NC installs, and in Firefox and Chromium.

## Steps to reproduce

See example video - **skip to 3:00**:

https://github.com/user-attachments/assets/e8a3e201-e0d0-4247-b099-e3a2a42c0c25

### Expected behaviour
New messages from the other party should automatically scroll into view

### Actual behaviour
But they don't because my own message triggered the scroll indicator

## Talk app

**Talk app version:** 20.1.4
**Custom Signaling server configured:** no
**Custom TURN server configured:** no
**Custom STUN server configured:** no

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Follow-up to #14266
  * Keeps node reference for ResizeObserver after switching conversations
  * Ensure non-scrollable chat doesn't have 'scroll to bottom' button
* Fix #14392 🚧
  * `setChatScrolledToBottom(false)` should be only set on scroll up (if we're scrolling down. it should be already set)

### 🖼️ Screenshots / Screencasts

🏡 After

https://github.com/user-attachments/assets/0cdcac86-e967-43e4-a894-94f5b5861c86

### 🔬  Test
- [x] removing `:key`:
  - [x] ResizeObserver works after conversation switch
  - [x] nothing is broken, if we get rid of 'force-refresh' of whole component
- [x] non-scrollable chats do not have 🔽 button:
  - [x] on open (on open with focusing message)
  - [x] on resize
  - [x] on messages list (height) change
- [x] scrollable chats do not have 🔽 button:
  - [x] when scrolling down
  - [x] when nothing to scroll
  - [x] when new message arrives, and there's a mismatch of last read (follow-up from above)

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesList.vue [hunk 1]
```diff
@@ -7,7 +7,6 @@
 	<!-- size and remain refer to the amount and initial height of the items that
 	are outside of the viewport -->
 	<div ref="scroller"
-		:key="token"
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:10]: Was added during messages list soft update refactoring, but now it seems to be covered with `messagesList` watcher
With key in place, ResizeObserver loses reference to the scroller

File: src/components/MessagesList/MessagesList.vue [hunk 2]
```diff
@@ -387,6 +386,9 @@ export default {
 				this.$refs.scroller.scrollTo({
 					top: this.$refs.scroller.scrollHeight,
 				})
+			} else if (this.$refs.scroller.clientHeight === this.$refs.scroller.scrollHeight) {
+				// chat is not scrollable
+				this.setChatScrolledToBottom(true)
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:391]: For non-scrollable chats, removes the scroll to bottom on resize

File: src/components/MessagesList/MessagesList.vue [hunk 3]
```diff
@@ -931,10 +933,10 @@ export default {
 				this.displayMessagesLoader = false
 				this.debounceUpdateReadMarkerPosition()
 				return
+			} else if (scrollHeight > clientHeight) {
+				this.setChatScrolledToBottom(false)
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:937]: After swtiching to conversation, handleScroll is triggered. Regardless of container height, it sets value to false (whereas it shouldn't for non-scrollable chats)

File: src/components/MessagesList/MessagesList.vue [hunk 4]
```diff
@@ -932,24 +934,25 @@ export default {
 				return
 			}
 
-			this.setChatScrolledToBottom(false)
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:935]: After swtiching to conversation, handleScroll is triggered. Regardless of container height, it sets value to false (whereas it shouldn't for non-scrollable chats)
For scrollable chats it also shouldn't set to false, when receiiving message (handleScroll is triggered with 'down' direction)

File: src/components/MessagesList/MessagesList.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:10]: fine

File: src/components/MessagesList/MessagesList.vue (hunk 2 above)
Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:390]: Maybe we need `nextTick` here? edge case:
* Have one long message in a conversation (the scroller is scrollable)
* Delete that message (no Longer scrollable)
* You will have `chatScrolledToBottom` truthy

**Review by DorraJaouad — COMMENTED** [review]
Sthg is wrong, chat is sticky when document is not focused (hidden) and it scrolls to bottom ⚠️

File: src/components/MessagesList/MessagesList.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:390]: added to messageList watcher

File: src/components/MessagesList/MessagesList.vue [hunk 5]
```diff
@@ -301,6 +300,10 @@ export default {
 				// scroll to bottom if needed
 				this.scrollToBottom({ smooth: false })
 
+				this.$nextTick(() => {
+					this.checkChatNotScrollable()
+				})
+
 				if (this.conversation?.type === CONVERSATION.TYPE.NOTE_TO_SELF) {
 					this.$nextTick(() => {
 						this.updateTasksCount()
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesList.vue:309]: Wrap them together?

File: src/components/MessagesList/MessagesList.vue [hunk 6]
```diff
@@ -932,7 +936,9 @@ export default {
 				return
 			}
 
-			this.setChatScrolledToBottom(false)
+			if (scrollHeight > clientHeight && this.isScrolling === 'up') {
+				this.setChatScrolledToBottom(false)
+			}
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesList.vue:941]: Now, when there are unread messages, it scrolls correctly but `isChatScrolledToBottom` is truthy (hence isSticky) and clears all unread messages.

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:941]: The scroll to bottom button is missing and it reads all of the chat at once (without even scrolling).
For the second part, it might sound okay but it's a new behaviour that we should agree on, no?

https://github.com/user-attachments/assets/54b39fce-4496-43c4-b3ff-942658bc7539

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:941]: This is incorrect, let me reproduce and fix it

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue]: Was a false-positive check for `isScrolling`

File: src/store/messagesStore.js [hunk 7]
```diff
@@ -1205,6 +1210,14 @@ const actions = {
 			}
 		}
 
+		if (conversation && lastMessageFromSelf?.id > conversation.lastReadMessage) {
+			context.dispatch('updateLastReadMessage', {
+				token,
+				id: lastMessageFromSelf.id,
+				updateVisually: true,
+			})
+		}
```
Comment (DorraJaouad) [inline src/store/messagesStore.js:1219]: I am afraid it should not be on store level but rather on message posting level as it kills mark a particular message X as unread functionality when you have already posted a message Y such that X.id < Y.id.

Comment (Antreesy) [reply src/store/messagesStore.js:1219]: Ah, right
Hm, maybe it could be done then we're replacing temp message

File: src/store/messagesStore.js [hunk 8]
```diff
@@ -586,9 +586,21 @@ const actions = {
 
 		if (message.referenceId) {
 			const tempMessages = context.getters.getTemporaryReferences(token, message.referenceId)
-			tempMessages.forEach(tempMessage => {
-				context.commit('deleteMessage', { token, id: tempMessage.id })
-			})
+			if (tempMessages.length > 0) {
```
Comment (DorraJaouad) [inline src/store/messagesStore.js:589]: `// If successful, deletes the temporary message from the store
			context.dispatch('removeTemporaryMessageFromStore', { token, id: temporaryMessage.id })`

temp message is removed before processing the message is `postNewMessage`

Also, `processMessage` in multiple points, I wouldn't risk updating the last read message there. As suggested before, it should rather focus on post new message only. What's odd is that the current addition already exists there but it wasn't working efficiently

https://github.com/nextcloud/spreed/blob/main/src/store/messagesStore.js#L1276-L1291

Comment (Antreesy) [reply src/store/messagesStore.js:589]: it exists and works for text messages only. File share (with /without caption) is a one-way, a we will receive a feedback only from message polling

postNewMessage can do it, as we receive a message object as a response and can replace it safely

Comment (Antreesy) [reply src/store/messagesStore.js:589]: As discussed, moved logic from postNewMessage to processMessage, to not duplicate it and also cover file shares

File: src/components/MessagesList/MessagesList.vue (hunk 4 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:908]: Modify to set 'false' only if we're above 10px from bottom. So if we're sticky, that shouldn't cause button appearance

**Comment by DorraJaouad** [comment]
Time has come 🦅 
Tested ✅

**Review by DorraJaouad — APPROVED** [review]
