### PR TITLE
fix(MessageItem): increase hover area for actions to appear

### LINKED ISSUE #16413: [SPLIT VIEW] Message buttons bar should show up on hover bigger area
This zone should react on hover effect. Otherwise it's hard to click the buttons
Image 

Image

Currently, we don't have a wrapper that covers the whole space.
A solution we can add a div and listen to its hovering to pass it to MessageButtonsBar

_Originally posted by @DorraJaouad in https://github.com/nextcloud/spreed/pull/16273#discussion_r2560166436_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #16413
  * MessageItem in split view hover area is expanded to better access message actions
  * .message-body__scroll width is compensated with 4px paddings to fit buttons on screen
  * MessagesGroup moved to `isSmallMobile` breakpoint, same as MessageItem
  * Fix background colors for hovered/focused messages in classic / split view
  * Refactor shared styles for message bubbles

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | -- 
image | image
image | image
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue [hunk 1]
```diff
@@ -442,30 +436,45 @@ export default {
...
-
-	&.incoming:hover .message-body,
-	&--hovered .message-body {
-		background-color: var(--color-primary-element-extra-light-hover);
-	}
-
 	&--sided {
 		width: fit-content;
-		max-width: min(90%, calc(100% - 3 * var(--default-clickable-area)));
+		max-width: min(90%, calc(100% - 3 * var(--default-clickable-area) - 2 * var(--default-grid-baseline)));
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessageItem.vue]: Maybe put the min width of buttons bar in a variable so this can be understandable?

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue [hunk 2]
```diff
@@ -442,30 +436,45 @@ export default {
...
-			inset-inline-end: 0;
-			padding-block-end: var(--default-grid-baseline);
+		// Shared styles for message bubbles
+		.message-body {
+			border: 1px solid var(--color-primary-element-light-hover);
+			border-block-end-width: 2px;
+		}
+
+		.message-body__scroll {
+			--overlay-offset: 100%;
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessageItem.vue:455]: Pin icon depends on this container, please adjust for outgoint class

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesGroup/Message/MessageItem.vue:455]: UPD: it will be always broken for bottom side style (in call), we need to move it somewhere else :/

For now, I recommend to use overlay more:
`overlay: isSplitViewEnabled && isReactionsMenuOpen,`

**Comment by DorraJaouad** [comment]
The buttons bar design needs to be updated for call view, as it is often off the view:
- If you think about overlaying it like we do for reactions menu when it is open, it will always hide small messages and thus you cannot copy
- If you think about allocating enough space for it, the chat width is too small to afford that. 

It should be small-view oriented

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessageItem.vue:455]: Added condition for pinned-only, buttons remain on the same place:

B | A
-- | --
image | image

**Comment by Antreesy** [comment]
> It should be small-view oriented

Would be rather an easy change to move them to small size:
wide | narrow
-- | --
image | image

I'll push a commit, so it can be discussed and merged/discarded afterwards

UPD: rebased, changes are in fixups only

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue (hunk 2 above)
Comment (DorraJaouad) [reply src/components/MessagesList/MessagesGroup/Message/MessageItem.vue:455]: > Added condition for pinned-only, buttons remain on the same place:

I still think it should be elsewhere, bc when the bar is at the bottom side and you hover, the pin will disappear

**Comment by DorraJaouad** [comment]
> Would be rather an easy change to move them to small size:

this approach is just reducing the probability of excess the boundaries but not solving the issue so ofc we will sometimes bump into this:

image

File: src/components/MessagesList/MessagesGroup/Message/MessageItem.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessageItem.vue:455]: It's not a part of the issue to be solved. We can follow-up on position of pin icon separately

**Comment by Antreesy** [comment]
> this approach is just reducing the probability of excess the boundaries but not solving the issue so ofc we will sometimes bump into this:

https://github.com/nextcloud/spreed/blob/0261b486452bfe2da94b4f6b7c048b06bc78e96e/src/components/MessagesList/MessagesGroup/Message/MessageItem.vue#L335

let's move to follow-up as well with small buttons
