### PR TITLE
fix(signaling): Add the displayname to the signaling ticket for feder…

### LINKED ISSUE #12818: Join of federated user is missing displayName
Join of a federated user misses the displayname, that we usually have for local users.

This is a join from a federated user:
Bildschirmfoto 2024-07-25 um 19 36 50

This from a user of the instance:
Bildschirmfoto 2024-07-25 um 19 36 32

_Originally posted by @SystemKeeper in https://github.com/nextcloud/spreed/issues/12802#issuecomment-2251057160_

### PR DESCRIPTION
**Pull request by nickvergessen**
…atd users

### ☑️ Resolves

* Fix #12818 

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]
Can't really judge the code, but seems to work fine: 
image

image

File: lib/Controller/SignalingController.php [hunk 1]
```diff
@@ -17,6 +17,7 @@
 use OCA\Talk\Exceptions\RoomNotFoundException;
 use OCA\Talk\Federation\Authenticator;
 use OCA\Talk\Manager;
+use OCA\Talk\Middleware\Attribute\FederationSupported;
```
Comment (danxuliu) [inline lib/Controller/SignalingController.php:20]: Unused.
