### PR TITLE
fix(SharedItems): adjust tab styling

### LINKED ISSUE #15707: Improve right sidebar styling
The sidebar styling can be improved so that it looks more appealing when all items are filled, espcially now that we are including threads there

Image

- [ ] Add more gap between the sections (`.app-navigation-caption__name { margin-top: calc(6*var(--default-grid-baseline)) } ` )
- [ ] Media
  - [ ] Show only the last 5 images 
  - [ ] Fit them all into one row (`.shared-items { grid-template-columns: 1fr 1fr 1fr 1fr 1fr } `)
- [ ] Files/recording
  - [ ] Text should be normal (removed `.file-preview .name-container { font-weight: bold} `)
- [ ] Polls
  - [ ] Move "Browse all poll drafts" into polls section as the first item
- [ ] Nice-to-have: "Show all media/files/etc" button 
  - [ ] Make it left aligned
  - [ ] Icon size 24px
  - [ ] gap 8px

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #15707

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | 2025-08-26_20h53_18
image | 2025-08-26_20h53_35
image | 2025-08-26_20h53_45

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [x] 🖌️ Design was reviewed, approved or inspired by the design team

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by Antreesy** [comment]
Forgot one more icon: 
image

File: src/components/RightSidebar/RightSidebar.vue
Comment (DorraJaouad) [inline src/components/RightSidebar/RightSidebar.vue:1]: Forgot to remove `IconFolderMultipleImage` import

File: src/components/RightSidebar/SharedItems/SharedItemsTab.vue [hunk 1]
```diff
@@ -221,19 +218,47 @@ function openPollDraftHandler() {
...
+	}
+
 	&__loading,
 	&__empty-content {
 		flex: 1;
 	}
+
+	&__more-button {
+		margin-top: var(--default-grid-baseline);
+		margin-inline-start: -1px; // compensate button border
```
Comment (DorraJaouad) [inline src/components/RightSidebar/SharedItems/SharedItemsTab.vue]: What about `border: 0` ?

**Review by DorraJaouad — COMMENTED** [review]
I also noticed that previews in tab is  not well aligned

Image

File: src/components/RightSidebar/SharedItems/SharedItemsTab.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/RightSidebar/SharedItems/SharedItemsTab.vue]: Might be fine for tertiary

**Comment by Antreesy** [comment]
> I also noticed that previews in tab is  not well aligned

Need to be more specific on this) 
gap, border-radius?

**Comment by DorraJaouad** [comment]
I thought it is obvious from the screenshot, it the positioning

image
