### PR TITLE
fix: Moderators no longer able to ban themselves or other moderators

### LINKED ISSUE #12670: fix: Moderators are able to ban themselves and other moderators
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Expected behaviour
Moderators should not be able to ban themselves and other moderators

### Actual behaviour
Moderators are able to ban themselves and other moderators

### PR DESCRIPTION
**Pull request by skalidindi53**
### ☑️ Resolves

* Fix #12670 

### 🚧 Tasks

- [x] Moderators no longer able to ban themselves or other moderators

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

File: tests/integration/features/bootstrap/FeatureContext.php [hunk 1]
```diff
@@ -1487,6 +1489,18 @@ public function userBansUserFromRoom(string $user, string $actorType, string $ac
...
+		if($user === $actorId) {
+			return;
+		}
+
+		//If actorId is a moderator
+		if(isset(self::$promotedParticipants[$identifier])) {
+			if($actorId === self::$promotedParticipants[$identifier]) {
+				return;
+			}
+		}
```
Comment (nickvergessen) [inline tests/integration/features/bootstrap/FeatureContext.php:1502]: this must not be here. You should block this in the actual BanController/BanService

File: lib/Controller/BanController.php [hunk 2]
```diff
@@ -55,6 +58,17 @@ public function banActor(string $actorType, string $actorId, string $internalNot
...
 
+			$bannedParticipant = $this->participantService->getParticipantByActor($this->room, $actorType, $actorId);
+			
+			if ($bannedParticipant->getAttendee()->getParticipantType() === Participant::MODERATOR) {
+				throw new \InvalidArgumentException('Cannot ban a moderator');
+			}
+
+			if ($actorId === $moderatorActorId && $actorType === $moderatorActorType) {
+				throw new \InvalidArgumentException('Cannot ban yourself');
+			}
```
Comment (nickvergessen) [inline lib/Controller/BanController.php:69]: Should be in the banService with `throw new \InvalidArgumentException('yourself')` and `'moderator'`

If you would keep it here, it should not throw but return a 400 data response instead, but that would just duplicate the work and allow to make mistakes if the services is invoked in another way at some point, so it's better to have the check in the service.

File: tests/integration/features/bootstrap/FeatureContext.php [hunk 3]
```diff
@@ -63,6 +63,8 @@ class FeatureContext implements Context, SnippetAcceptingContext {
 	protected static array $createdTeams = [];
 	/** @var array<string, int> */
 	protected static array $userToBanId;
+	/** @var array<string, string> */
+	protected static array $promotedParticipants = []; //list to keep track of participants promoted to moderator
```
Comment (nickvergessen) [inline tests/integration/features/bootstrap/FeatureContext.php:67]:
```suggestion
```

File: tests/integration/features/bootstrap/FeatureContext.php [hunk 4]
```diff
@@ -1838,6 +1840,9 @@ public function userAddAttendeeToRoom(string $user, string $newType, string $new
 		$this->assertStatusCode($this->response, $statusCode);
 	}
 
+
+
+
```
Comment (nickvergessen) [inline tests/integration/features/bootstrap/FeatureContext.php:1845]:
```suggestion
```

File: tests/integration/features/bootstrap/FeatureContext.php [hunk 5]
```diff
@@ -1866,6 +1871,7 @@ public function userPromoteDemoteInRoom(string $user, string $isPromotion, strin
 			'/apps/spreed/api/' . $apiVersion . '/room/' . self::$identifierToToken[$identifier] . '/moderators',
 			new TableNode($requestParameters)
 		);
+
```
Comment (nickvergessen) [inline tests/integration/features/bootstrap/FeatureContext.php:1874]:
```suggestion
```

File: lib/Controller/BanController.php [hunk 6]
```diff
@@ -55,6 +58,17 @@ public function banActor(string $actorType, string $actorId, string $internalNot
...
 			$moderatorActorId = $moderator->getActorId();
 
+			$bannedParticipant = $this->participantService->getParticipantByActor($this->room, $actorType, $actorId);
+			
+			if ($bannedParticipant->getAttendee()->getParticipantType() === Participant::MODERATOR) {
+				throw new \InvalidArgumentException('Cannot ban a moderator');
+			}
+
+			if ($actorId === $moderatorActorId && $actorType === $moderatorActorType) {
+				throw new \InvalidArgumentException('Cannot ban yourself');
```
Comment (nickvergessen) [inline lib/Controller/BanController.php:68]: Just as a note, if you check the error message in the integration test, you will notice this never triggers, as you yourself are a moderator so the previous check does it :P

File: lib/Controller/BanController.php [hunk 7]
```diff
@@ -55,6 +58,17 @@ public function banActor(string $actorType, string $actorId, string $internalNot
 			$moderatorActorType = $moderator->getActorType();
 			$moderatorActorId = $moderator->getActorId();
 
+			$bannedParticipant = $this->participantService->getParticipantByActor($this->room, $actorType, $actorId);
+			
+			if ($bannedParticipant->getAttendee()->getParticipantType() === Participant::MODERATOR) {
```
Comment (nickvergessen) [inline lib/Controller/BanController.php:63]:
```suggestion
			if ($bannedParticipant->hasModeratorPermissions()) {
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Otherwise it looks good :)

File: lib/Controller/BanController.php (hunk 6 above)
Comment (skalidindi53) [reply lib/Controller/BanController.php:68]: Yeah I also thought the same but yesterday I was able to see that it was able catch this check. so I just left it But your right today it never triggers so I just moved it up.

**Review by nickvergessen — APPROVED** [review]
