### PR TITLE
Remove deleted groups from settings

### LINKED ISSUE #4248: Shows deleted Groups in "Limit to groups" settings
## Steps to reproduce
1. Delete all groups from the system that are in Talk's limit to group settings

### Expected behaviour
All groups removed from the limit to group settings, open Talk app for everyone

### Actual behaviour
Three groups, which are deleted are shown in the limit to group line. 
Those Groups are not avaiable in the nextcloud group watch.

## Talk app

**Talk app version:** 9.0.4

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no 

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows 10

**Browser name:** Edge Chromium / Internet Explorer 

**Browser version:** 85.0.564.63 / 11.508.19041.0

## Server configuration

**Operating system**: Linux 4.15.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.1.44

**PHP version:** 7.3.22
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud Version:** 19.0.3

**List of activated apps:**

```
Enabled:  - accessibility: 1.5.0  - activity: 2.12.0  - announcementcenter: 3.8.1  - bruteforcesettings: 2.0.1  - calendar: 2.0.4  - cloud_federation_api: 1.2.0  - comments: 1.9.0  - contacts: 3.3.0  - contactsinteraction: 1.0.0  - dav: 1.15.0  - deck: 1.0.5  - documentserver_community: 0.1.7  - event_update_notification: 1.0.2  - federatedfilesharing: 1.9.0  - federation: 1.9.0  - files: 1.14.0  - files_mindmap: 0.0.22  - files_pdfviewer: 1.8.0  - files_rightclick: 0.16.0  - files_sharing: 1.11.0  - files_trashbin: 1.9.0  - files_versions: 1.12.0  - files_videoplayer: 1.8.0  - firstrunwizard: 2.8.0  - forms: 2.0.4  - groupfolders: 7.0.0  - guests: 1.5.0  - issuetemplate: 0.7.0  - logreader: 2.4.0  - lookup_server_connector: 1.7.0  - mail: 1.4.1  - nextcloud_announcements: 1.8.0  - notes: 3.6.4  - notifications: 2.7.0  - oauth2: 1.7.0  - occweb: 0.0.7  - password_policy: 1.9.1  - photos: 1.1.0  - polls: 1.4.3  - privacy: 1.3.0  - provisioning_api: 1.9.0  - recommendations: 0.7.0  - registration: 0.5.0  - serverinfo: 1.9.0  - settings: 1.1.0  - sharebymail: 1.9.0  - spreed: 9.0.4  - support: 1.2.1  - survey_client: 1.7.0  - systemtags: 1.9.0  - tasks: 0.13.3  - text: 3.0.1  - theming: 1.10.0  - twofactor_backupcodes: 1.8.0  - updatenotification: 1.9.0  - viewer: 1.3.0  - workflowengine: 2.1.0
```

**Nextcloud configuration:**

```json
{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "cloud.presse-fflg.luenefire.de"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "19.0.3.1",        "overwrite.cli.url": "https:\/\/cloud.presse-fflg.luenefire.de",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "oc_",        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "mysql.utf8mb4": true,        "htaccess.RewriteBase": "\/",        "mail_smtpmode": "smtp",        "mail_smtpsecure": "ssl",        "mail_sendmailmode": "smtp",        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_smtpauthtype": "LOGIN",        "mail_smtpauth": 1,        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpport": "465",        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "maintenance": false,        "loglevel": 2,        "theme": "",        "app_install_overwrite": [            "files_external",            "files_external_dropbox",            "occweb",            "registration",            "gluusso",            "files_external_ipfs"        ]    },    "apps": {        "accessibility": {            "enabled": "yes",            "installed_version": "1.5.0",            "types": ""        },        "activity": {            "enabled": "yes",            "installed_version": "2.12.0",            "notify_email_announcementcenter": "1",            "notify_email_calendar": "0",            "notify_email_calendar_event": "0",            "notify_email_calendar_todo": "1",            "notify_email_comments": "0",            "notify_email_cospend": "0",            "notify_email_cospend_bill_event": "0",            "notify_email_deck": "0",            "notify_email_deck_card_description": "0",            "notify_email_deck_comment": "0",            "notify_email_favorite": "0",            "notify_email_file_changed": "0",            "notify_email_file_created": "0",            "notify_email_file_deleted": "0",            "notify_email_file_restored": "0",            "notify_email_public_links": "0",            "notify_email_remote_share": "0",            "notify_email_shared": "0",            "notify_email_spreed": "0",            "notify_email_systemtags": "0",            "notify_setting_batchtime": "3600",            "notify_setting_self": "1",            "notify_setting_selfemail": "0",            "notify_stream_calendar": "1",            "notify_stream_calendar_event": "1",            "notify_stream_calendar_todo": "1",            "notify_stream_comments": "1",            "notify_stream_cospend": "1",            "notify_stream_cospend_bill_event": "1",            "notify_stream_deck": "1",            "notify_stream_deck_card_description": "1",            "notify_stream_favorite": "1",            "notify_stream_file_changed": "1",            "notify_stream_file_created": "1",            "notify_stream_file_deleted": "1",            "notify_stream_file_favorite": "0",            "notify_stream_file_restored": "1",            "notify_stream_public_links": "1",            "notify_stream_remote_share": "1",            "notify_stream_shared": "1",            "notify_stream_spreed": "1",            "notify_stream_systemtags": "1",            "types": "filesystem"        },        "announcementcenter": {            "enabled": "yes",            "installed_version": "3.8.1",            "types": "logging"        },        "backgroundjob": {            "lastjob": "63"        },        "bruteforcesettings": {            "enabled": "yes",            "installed_version": "2.0.1",            "types": ""        },        "calendar": {            "enabled": "yes",            "installed_version": "2.0.4",            "types": ""        },        "cloud_federation_api": {            "enabled": "yes",            "installed_version": "1.2.0",            "types": "filesystem"        },        "comments": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "logging"        },        "contacts": {            "enabled": "yes",            "installed_version": "3.3.0",            "types": ""        },        "contactsinteraction": {            "enabled": "yes",            "installed_version": "1.0.0",            "types": "dav"        },        "core": {            "backgroundjobs_mode": "ajax",            "enterpriseLogoChecked": "yes",            "installed.bundles": "[\"CoreBundle\"]",            "installedat": "1589886855.1605",            "lastcron": "1601386120",            "lastupdateResult": "[]",            "lastupdatedat": "1601385482",            "oc.integritycheck.checker": "[]",            "public_files": "files_sharing\/public.php",            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",            "theming.variables": "1f437217ebcf0f29759a9a086eb0fb03",            "updater.secret.created": "1600707585",            "vendor": "nextcloud"        },        "cospend": {            "enabled": "no",            "installed_version": "1.0.5",            "types": ""        },        "dav": {            "buildCalendarReminderIndex": "yes",            "buildCalendarSearchIndex": "yes",            "chunks_migrated": "1",            "enabled": "yes",            "installed_version": "1.15.0",            "regeneratedBirthdayCalendarsForYearFix": "yes",            "sendEventRemindersPush": "yes",            "types": "filesystem"        },        "deck": {            "enabled": "yes",            "installed_version": "1.0.5",            "types": "dav"        },        "documentserver_community": {            "enabled": "yes",            "installed_version": "0.1.7",            "types": "filesystem"        },        "event_update_notification": {            "enabled": "yes",            "installed_version": "1.0.2",            "types": "logging,dav"        },        "federatedfilesharing": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": ""        },        "federation": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "authentication"        },        "files": {            "cronjob_scan_files": "500",            "enabled": "yes",            "installed_version": "1.14.0",            "types": "filesystem"        },        "files_external": {            "enabled": "yes"        },        "files_external_dropbox": {            "enabled": "no",            "installed_version": "1.4.2",            "types": "filesystem"        },        "files_external_ipfs": {            "enabled": "no",            "installed_version": "0.2.0",            "types": "filesystem"        },        "files_mindmap": {            "enabled": "yes",            "installed_version": "0.0.22",            "types": ""        },        "files_pdfviewer": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "files_rightclick": {            "enabled": "yes",            "installed_version": "0.16.0",            "types": ""        },        "files_sharing": {            "enabled": "yes",            "installed_version": "1.11.0",            "types": "filesystem"        },        "files_trashbin": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "filesystem,dav"        },        "files_versions": {            "enabled": "yes",            "installed_version": "1.12.0",            "types": "filesystem,dav"        },        "files_videoplayer": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "firstrunwizard": {            "enabled": "yes",            "installed_version": "2.8.0",            "types": "logging"        },        "forms": {            "enabled": "yes",            "installed_version": "2.0.4",            "types": ""        },        "groupfolders": {            "enabled": "yes",            "installed_version": "7.0.0",            "types": "filesystem,dav"        },        "guests": {            "allow_external_storage": "false",            "enabled": "yes",            "hide_users": "true",            "installed_version": "1.5.0",            "types": "authentication",            "usewhitelist": "true",            "whitelist": "files_trashbin,files_versions,files_sharing,files_texteditor,text,activity,firstrunwizard,photos,notifications,groupfolders,tasks"        },        "issuetemplate": {            "enabled": "yes",            "installed_version": "0.7.0",            "types": ""        },        "logreader": {            "enabled": "yes",            "installed_version": "2.4.0",            "types": ""        },        "lookup_server_connector": {            "enabled": "yes",            "installed_version": "1.7.0",            "types": "authentication"        },        "mail": {            "enabled": "yes",            "installed_version": "1.4.1",            "types": ""        },        "nextcloud_announcements": {            "enabled": "yes",            "installed_version": "1.8.0",            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",            "types": "logging"        },        "notes": {            "enabled": "yes",            "installed_version": "3.6.4",            "types": ""        },        "notifications": {            "enabled": "yes",            "installed_version": "2.7.0",            "types": "logging"        },        "oauth2": {            "enabled": "yes",            "installed_version": "1.7.0",            "types": "authentication"        },        "occweb": {            "enabled": "yes",            "installed_version": "0.0.7",            "types": ""        },        "onlyoffice": {            "DocumentServerInternalUrl": "https:\/\/cloud.presse-fflg.luenefire.de\/",            "DocumentServerUrl": "https:\/\/cloud.presse-fflg.luenefire.de\/index.php\/apps\/documentserver_community\/",            "StorageUrl": "https:\/\/cloud.presse-fflg.luenefire.de\/",            "customizationChat": "true",            "customizationCompactHeader": "true",            "customizationFeedback": "true",            "customizationHelp": "true",            "customizationReviewDisplay": "original",            "customizationToolbarNoTabs": "true",            "defFormats": "{\"csv\":\"false\",\"doc\":\"true\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"true\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"true\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",            "demo": "{\"available\":true,\"enabled\":false,\"start\":{\"date\":\"2020-06-07 02:54:20.481386\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",            "editFormats": "{\"csv\":\"true\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"rtf\":\"true\",\"txt\":\"true\"}",            "enabled": "no",            "groups": "[\"FFLG_Pressesprecher\",\"FFLG_Webmaster\",\"StFv_\\u00d6ffentlichkeitsarbeit\",\"admin\"]",            "installed_version": "4.3.0",            "jwt_secret": "",            "sameTab": "true",            "settings_error": "Client error: `GET https:\/\/cloud.presse-fflg.luenefire.de\/healthcheck` resulted in a `404 Not Found` response:\n<!DOCTYPE HTML PUBLIC \"-\/\/IETF\/\/DTD HTML 2.0\/\/EN\">\n<html><head>\n<title>404 Not Found<\/title>\n<\/head><body>\n<h1>Not Found (truncated...)\n",            "types": "filesystem"        },        "password_policy": {            "enabled": "yes",            "enforceHaveIBeenPwned": "1",            "enforceNumericCharacters": "1",            "enforceSpecialCharacters": "1",            "enforceUpperLowerCase": "1",            "installed_version": "1.9.1",            "types": "authentication"        },        "photos": {            "enabled": "yes",            "installed_version": "1.1.0",            "types": ""        },        "polls": {            "enabled": "yes",            "installed_version": "1.4.3",            "types": ""        },        "privacy": {            "enabled": "yes",            "installed_version": "1.3.0",            "types": ""        },        "provisioning_api": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "prevent_group_restriction"        },        "recommendations": {            "enabled": "yes",            "installed_version": "0.7.0",            "types": ""        },        "registration": {            "enabled": "yes",            "installed_version": "0.5.0",            "types": ""        },        "richdocuments": {            "disable_certificate_verification": "",            "enabled": "no",            "installed_version": "3.7.0",            "types": "filesystem,dav,prevent_group_restriction",            "wopi_url": "https:\/\/cloud.presse-fflg.luenefire.de\/index.php\/apps\/documentserver_community\/"        },        "serverinfo": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": ""        },        "settings": {            "enabled": "yes",            "installed_version": "1.1.0",            "types": ""        },        "sharebymail": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "filesystem"        },        "spreed": {            "allowed_groups": "[\"Presse\",\"Pressesprecher\",\"Webadmins\"]",            "enabled": "yes",            "has_reference_id": "yes",            "installed_version": "9.0.4",            "project_access_invalidated": "1",            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",            "stun_servers": "***REMOVED SENSITIVE VALUE***",            "types": "prevent_group_restriction"        },        "support": {            "SwitchUpdaterServerHasRun": "yes",            "enabled": "yes",            "installed_version": "1.2.1",            "types": "session"        },        "survey_client": {            "enabled": "yes",            "installed_version": "1.7.0",            "types": ""        },        "systemtags": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "logging"        },        "tasks": {            "enabled": "yes",            "installed_version": "0.13.3",            "types": ""        },        "text": {            "enabled": "yes",            "installed_version": "3.0.1",            "types": "dav"        },        "theming": {            "backgroundMime": "backgroundColor",            "cachebuster": "24",            "color": "#F7F7F7",            "enabled": "yes",            "faviconMime": "image\/jpeg",            "installed_version": "1.10.0",            "logoMime": "image\/png",            "logoheaderMime": "image\/png",            "name": "Cloud - Pressestelle Feuerwehr L\u00fcneburg",            "slogan": "***REMOVED SENSITIVE VALUE***",            "types": "logging",            "url": "***REMOVED SENSITIVE VALUE***"        },        "twofactor_backupcodes": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "updatenotification": {            "core": "19.0.3.1",            "cospend": "1.0.5",            "deck": "1.0.5",            "enabled": "yes",            "files_mindmap": "0.0.22",            "forms": "2.0.3",            "installed_version": "1.9.0",            "notes": "3.6.2",            "onlyoffice": "4.3.0",            "spreed": "9.0.4",            "tasks": "0.13.2",            "types": "",            "update_check_errors": "0"        },        "viewer": {            "enabled": "yes",            "installed_version": "1.3.0",            "types": ""        },        "workflowengine": {            "enabled": "yes",            "installed_version": "2.1.0",            "types": "filesystem"        }    }}
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #4248

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Makes sense :+1:

File: lib/Listener/GroupDeletedListener.php [hunk 1]
```diff
@@ -0,0 +1,64 @@
+<?php
+
+declare(strict_types=1);
+/**
+ * @copyright Copyright (c) 2020 Joas Schilling <coding@schilljs.com>
```
Comment (danxuliu) [inline lib/Listener/GroupDeletedListener.php:5]: 2020... copy-pasta? :-)

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:
