### PR TITLE
Only render emoji picker on hover

### LINKED ISSUE #7319: UI switching between large conversations is slow
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have two conversations with multiple >20 users and lots of messages
2. Switch between the conversations

### Expected behaviour
The message list should load fast

### Actual behaviour
The message list takes multiple seconds to load, even though the actual network requests to the API are fast.

This happens on our instance but I couldn't reproduce it locally with the dev javascript build, probably because I haven't enough message history, reactions or manually added users.

But the profile from our instance should give an idea on where to investigate further. From there I see two major points:
Screenshot 2022-05-05 at 15 04 41

- Destruction of the old components (it seems that for the v-tooltip each destroy is issuing a timeout function to hide it)
Screenshot 2022-05-05 at 15 05 15

- When rendering the new components a lot of style recalculations are happening during emoji-mart related code

Screenshot 2022-05-05 at 15 16 55

## Additional context:

- I feel this has started with the upgrade to 24
- The tooltip thing links like skipDelay is not passed over here: https://github.com/Akryum/floating-vue/blob/v2.0.3/src/components/Popover.vue#L285
  - Seems like this commit https://github.com/Akryum/floating-vue/commit/70043d3850dfe0f3bf0b32b9f5878fe70f40549a is not part of the most recent v-tooltip release
  - Might need https://github.com/nextcloud/nextcloud-vue/pull/2600

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7319 

### Steps
1. Open two tabs with 2 users and send chat message `/spam 200 messages` in both
2. Close the tabs
3. Remove the div around the picker (to save you from having to react to all messages)
https://github.com/nextcloud/spreed/blob/e6e005760174417fd820aeb91180b9931635e9c8/src/components/MessagesList/MessagesGroup/Message/Message.vue#L118-L136
and
https://github.com/nextcloud/spreed/blob/e6e005760174417fd820aeb91180b9931635e9c8/src/components/MessagesList/MessagesGroup/Message/Message.vue#L147
5. Open Talk in a new tab
6. Load the chat
7. Wait until it loaded and observe 1.5GB ram being used
8. Scroll up and load the second page
9. Wait long again and see 1.5 GB more being used
10. Close the tab and see 3 GB ram being freed
11. Change to this patch
12. Remove again the change from 3.
13. Load the chat again in a new tab and see no significant memory consumption and also much more loading speed
14. Same with page 2 of the chat
15. Closing the tab also doesn't free 3 GB again

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/Message.vue [hunk 1]
```diff
@@ -523,6 +527,7 @@ export default {
 		},
 
 		showMessageButtonsBar() {
+			console.error(this.isHovered)
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/Message.vue:530]: Temp from debugging the tests

**Review by marcoambrosini — APPROVED** [review]

**Comment by danxuliu** [comment]
While this is much better it still has two small issues (which are more noticeable when there are several messages with reactions):
- Moving the mouse over the messages feels laggy (as the emoji picker is created and then destroyed when the mouse passes over each message that has reactions)
- Moving the mouse over the messages temporary increases the memory consumption (although the memory is freed soon afterwards once all the emoji pickers are destroyed)

Maybe it would be better to create the emoji picker only when the button to show it is actually clicked? Of course showing the emoji picker could still feel laggy, but it should be less common than just moving the mouse over a message. To address that maybe the emoji picker could be preloaded if the message was hovered for more than two seconds or something like that.
