### PR TITLE
Fix missing call-type in groups with no name

### LINKED ISSUE #970: Include call type in push message

### PR DESCRIPTION
**Pull request by mario**
Fix #970

### CODE REVIEW

File: lib/Notification/Notifier.php [hunk 1]
```diff
@@ -385,7 +385,13 @@ protected function parseCall(INotification $notification, Room $room, IL10N $l)
 			} else {
 				$notification
 					->setParsedSubject($l->t('A group call has started'))
-					->setRichSubject($l->t('A group call has started'));
+					->setRichSubject($l->t('A group call has started'), [
+						'call' => [
```
Comment (nickvergessen) [inline lib/Notification/Notifier.php]: this is "invalid", because the `{call}` placeholder is not used in the message.

I guess you do this, so you have the room details available in the mobile apps?

Comment (mario) [reply lib/Notification/Notifier.php]: Yes, indeed.

File: lib/Notification/Notifier.php [hunk 2]
```diff
@@ -385,7 +385,13 @@ protected function parseCall(INotification $notification, Room $room, IL10N $l)
...
+							'type' => 'call',
+							'id' => $room->getId(),
+							'call-type' => $this->getRoomType($room),
+						],
```
Comment (nickvergessen) [inline lib/Notification/Notifier.php]: It's missing the required name part:
https://github.com/nextcloud/server/blob/0913bc2157293acafa186afec4018ad25d7fbb22/lib/public/RichObjectStrings/Definitions.php#L170-L175
You can reuse the name from the activities:
https://github.com/nextcloud/spreed/blob/master/lib/Activity/Provider/Base.php#L143-L144

Comment (nickvergessen) [reply lib/Notification/Notifier.php]: :ping_pong: @mario

**Comment by mario** [comment]
Will be done today.

**Comment by mario** [comment]
Done @nickvergessen

File: lib/Notification/Notifier.php [hunk 3]
```diff
@@ -389,7 +389,14 @@ protected function parseCall(INotification $notification, Room $room, IL10N $l)
 			} else {
 				$notification
 					->setParsedSubject($l->t('A group call has started'))
-					->setRichSubject($l->t('A group call has started'));
+					->setRichSubject($l->t('A group call has started'), [
+						'call' => [
+							'type' => 'call',
+							'id' => $room->getId(),
```
Comment (nickvergessen) [inline lib/Notification/Notifier.php]: this should be `getToken()` now since #1028

**Comment by nickvergessen** [comment]
On one2one calls this is also missing atm, shall we add it there too?

**Comment by nickvergessen** [comment]
Do you still need this, now that the push notification already contains the token?

**Comment by mario** [comment]
Not really, no. You killed my way of sending call type anyway :p

**Comment by nickvergessen** [comment]
@mario feel free to test, then we can merge this

**Comment by mario** [comment]
Will do. As usual this week _ during the night :)

**Comment by mario** [comment]
Works like a charm.

**Comment by nickvergessen** [comment]
This is stable14+ only.
