### PR TITLE
[stable29] fix: show tooltips in sidebar (from Vue directive)

### LINKED ISSUE #12033: Failed to resolve directive: tooltip
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call in the file sidebar

### Actual behaviour

Bildschirmfoto 2024-04-09 um 20 58 26

Bildschirmfoto 2024-04-09 um 20 58 17

## Talk app

**Talk app version:** main @ 949d1cab1394d6d31d8891f8f93959bf06e87611

**Custom Signaling server configured:** yes

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #12033
* Directive was only declared in MatterbridgeSettings.vue, which made it work in main app (without it nothing works 🙈)
* stable30+ are not affected, as we replaced tooltips with native titles or NcPopover

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Files sidebars (3/3) | --
image | image
Admin settings | --
image| image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue [hunk 1]
```diff
@@ -121,8 +120,6 @@ import {
 	getBridgeProcessState,
 } from '../../../services/matterbridgeService.js'
 
-Vue.directive('tooltip', Tooltip)
```
Comment (ShGKme) [inline src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue:124]: Sadly, there is no ESLint rule to forbid it in Vue 2...

File: src/mainRecording.js [hunk 2]
```diff
@@ -79,6 +79,7 @@ Vue.use(VueRouter)
 Vue.use(VueObserveVisibility)
 Vue.use(VueShortKey, { prevent: ['input', 'textarea', 'div'] })
 Vue.use(vOutsideEvents)
+Vue.directive('tooltip', Tooltip)
```
Comment (ShGKme) [inline src/mainRecording.js:82]: I don't care for stable29, but in general - we should only use local registration, like with components. Otherwise it is hard to control whether a directive is available in a component or not.

**Review by ShGKme — APPROVED** [review]

File: src/mainRecording.js (hunk 2 above)
Comment (Antreesy) [reply src/mainRecording.js:82]: Thanks for future reference!
Yes, intent was only to fix in on stable29, since we drop it afterwards

File: src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue:124]: I see what can be done
