### PR TITLE
fix: add max description length as a capability

### LINKED ISSUE #14131: Support conversation description length from capabilities
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Hardcoded 500 in https://github.com/nextcloud/spreed/blob/07e6368d88bdf2c6bcb6864e3c6f1bd31c9f7ad5/src/constants.js#L113 has to be replaced with a capability check for:
> `config => conversations => description-length` (local) - The maximum length for conversation descriptions, currently 2000. Before this config was added the implicit limit was 500, since the existance of the feature capability `room-description`.

the 500 still need to be kept as a fall back for older versions via the desktop client

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #14131

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/ConversationSettings/BasicInfo.vue [hunk 1]
```diff
@@ -53,9 +53,10 @@ import ConversationAvatarEditor from './ConversationAvatarEditor.vue'
 import EditableTextField from '../UIShared/EditableTextField.vue'
 
 import { CONVERSATION } from '../../constants.js'
-import { hasTalkFeature } from '../../services/CapabilitiesManager.ts'
+import { hasTalkFeature, getTalkConfig } from '../../services/CapabilitiesManager.ts'
 
 const supportsAvatar = hasTalkFeature('local', 'avatar')
+const maxDescriptionLength = getTalkConfig('local', 'conversations', 'description-length') || 500
```
Comment (Antreesy) [inline src/components/ConversationSettings/BasicInfo.vue:59]: Should it be not local in future for federated moderators? 🤔

**Review by Antreesy — APPROVED** [review]

File: src/components/ConversationSettings/BasicInfo.vue (hunk 1 above)
Comment (nickvergessen) [reply src/components/ConversationSettings/BasicInfo.vue:59]: it has to take the value of the server hosting the conversation yeah. That being said, I think it might break on the API when a 31 conversation has 2k and invites someone from a 30 server with 500 limit. I'll raise a new issue about this.

**Review by Antreesy — APPROVED** [review]
