### PR TITLE
[stable29] fix: public share style and guest actions fixes 

### LINKED ISSUE #14694: [29] Public share sidebar trigger button not visible
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Use Talk on 29
2. Set primary color to something bright and background image to something dark
3. Create public share
4. See sidebar trigger button

### Screenshots

current | expected (see fix)
---|---
Image|Image

### Expected behaviour
Button should be white like all header buttons

### Actual behaviour
Button is black due to primary color being bright -> text color is dark.

## Fix
Use something like this:
```css
.button-holder button {
  background: transparent;
  color: #000;
  filter: var(--background-invert-if-dark);
}
```

Probably in `PublicShareSidebarTrigger.vue`.

## Talk app

**Talk app version:** 19.0.14

## Server configuration
**Nextcloud Version:** 29.0.14.2

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Ref #12159 
* Fix #14694

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/PublicShareSidebarTrigger.vue [hunk 1]
```diff
@@ -72,5 +73,10 @@ export default {
 	display: flex;
 	justify-content: center;
 	height: 44px !important;
+
+	& .sidebar-button {
+		color: #ffffff;
```
Comment (ShGKme) [inline src/PublicShareSidebarTrigger.vue:78]: Shouldn't be variable-defined?

Comment (Antreesy) [reply src/PublicShareSidebarTrigger.vue:78]: We have a variable for it in stable30+, for 29 I don't see anything useful.
This is a copy of https://github.com/nextcloud/server/pull/51599/commits/af55ec81fd123795bf62ed60579cfe2b48e1a6af

**Review by ShGKme — APPROVED** [review]
