### PR TITLE
fix: use method of largest remainder to count poll votes

### LINKED ISSUE #11867: Poll rounding error
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a poll
2. Have a bunch of people vote
3. Watch the numbers

### Expected behaviour
Tell us what should happen

### Actual behaviour
iOS
Android
Linux
Desktop
The math is not mathing.
`69+30=99`

## Talk app
I don't currently have access to the server but I can get access if you need me to.

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** n/a

**Camera available:** n/a

**Operating system:** Arch Linux, iOS, Android

**Browser name:** Native App

**Browser version:** respectively latest versions

### Browser log

n/a

## Server configuration
I don't currently have access to the server but I can get access if you need me to.

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #11867 
* Ref https://en.wikipedia.org/wiki/Quota_method
  * Rounds up total to 100% for most cases. Keeps it lower if there is no possibility to add up to equally high values

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
image | image
image | image
image | image

### 🏁 Checklist

- [x] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [x] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/PollViewer/PollViewer.vue [hunk 1]
```diff
@@ -222,6 +223,11 @@ export default {
 		canEndPoll() {
 			return this.isPollOpen && this.selfIsOwnerOrModerator
 		},
+
+		votePercentage() {
+			const votes = Object.keys(Object(this.poll?.options)).map(index => this.poll?.votes['option-' + index] ?? 0)
+			return countPollVotes(votes, this.poll.numVoters)
```
Comment (DorraJaouad) [inline src/components/PollViewer/PollViewer.vue:229]:
```suggestion
			return calculatesVotesPercentages(votes, this.poll.numVoters)
```

It is not counting

**Review by DorraJaouad — COMMENTED** [review]
Quota methods is a good solution, yet I'd recommend to simplify its implementation for a better understanding 

```
    if (!total) {
        return votes
    }

    const { wholes, remainders } = votes.reduce((acc: VoteAccumulator, vote) => {
        const quota = vote / total * 100
        acc.wholes.push(Math.floor(quota))
        acc.remainders.push(quota % 1)
        return acc
    }, { wholes: [], remainders: [] })

    // Calculate the sum of whole parts
    const sumWholes = wholes.reduce((acc, value) => acc + value, 0)

    // If the sum of whole parts is already 100, return it
    if (sumWholes === 100) {
        return wholes
    }

    // Calculate how many more votes we need to reach 100
    let remainingVotes = 100 - sumWholes

    // Get the indexes of the largest remainders
    const largestRemainders = remainders
        .map((value, index) => ({ value, index }))
        .sort((a, b) => b.value - a.value)
        .slice(0, remainingVotes)
        .map(item => item.index)

    // Distribute the remaining votes
    for (const index of largestRemainders) {
        wholes[index]++
    }

    return wholes
```

**Comment by Antreesy** [comment]
> // If the sum of whole parts is already 100, return it

Almost never the case, unless you have exactly 1,2,4,5,10,20,50 or 100 votes. Math.round is better here

> // Distribute the remaining votes

That rounds until 100%, but that's exactly the possible error for equal remainders described in the issue:
image

**Comment by DorraJaouad** [comment]
Another suggestion:

```
function adjustPercentages(totalVotes, votes) {
    // Step 1: Calculate initial percentages
    const rawPercentages = votes.map(vote => (vote / totalVotes) * 100);
    const roundedPercentages = rawPercentages.map(p => Math.round(p));
    let roundedSum = roundedPercentages.reduce((sum, p) => sum + p, 0);
    
    // Step 2: Calculate rounding difference
    let difference = 100 - roundedSum;
    
    // Step 3: Distribute rounding difference
    if (difference !== 0) {
        // Get indexes and fractional parts
        const fractionalParts = rawPercentages.map((p, i) => ({
            index: i,
            fraction: p - roundedPercentages[i]
        }));
        
        // Sort by the fractional part, descending
        fractionalParts.sort((a, b) => Math.abs(b.fraction) - Math.abs(a.fraction));
        
        // Adjust based on the rounding difference
        for (let i = 0; i < Math.abs(difference); i++) {
            let index = fractionalParts[i % votes.length].index;
            roundedPercentages[index] += (difference > 0) ? 1 : -1;
        }
    }
    
    return roundedPercentages;
}

// Test cases
const testCases = [
    [4, [1, 3]],
	[11, [1, 2, 8]],
	[13, [11, 2]],
	[13, [9, 4]],
	[26, [16, 5, 5]],
    [3, [1, 1, 1]],
    [7, [2, 2, 3]],
    [1000, [132, 494, 92, 282]],
	[1000, [135, 480, 97, 288]],
    [1000, [133, 491, 93, 283]],
    [1000, [134, 488, 94, 284]],
    [1000, [136, 482, 96, 286]],
    [1000, [135, 140, 345, 95, 285]],
    [1000, [137, 132, 347, 97, 287]],
];

testCases.forEach(([total, votes]) => {
    console.log(`Total votes: ${total}, Votes: ${votes} -> Adjusted Percentages: ${adjustPercentages(total, votes)}`);
});

```

outcome 

```
Total votes: 4, Votes: 1,3 -> Adjusted Percentages: 25,75
Total votes: 11, Votes: 1,2,8 -> Adjusted Percentages: 9,18,73
Total votes: 13, Votes: 11,2 -> Adjusted Percentages: 85,15
Total votes: 13, Votes: 9,4 -> Adjusted Percentages: 69,31
Total votes: 26, Votes: 16,5,5 -> Adjusted Percentages: 62,19,19
Total votes: 3, Votes: 1,1,1 -> Adjusted Percentages: 34,33,33
Total votes: 7, Votes: 2,2,3 -> Adjusted Percentages: 28,29,43
Total votes: 1000, Votes: 132,494,92,282 -> Adjusted Percentages: 13,50,9,28
Total votes: 1000, Votes: 135,480,97,288 -> Adjusted Percentages: 13,48,10,29
Total votes: 1000, Votes: 133,491,93,283 -> Adjusted Percentages: 14,49,9,28
Total votes: 1000, Votes: 134,488,94,284 -> Adjusted Percentages: 14,49,9,28
Total votes: 1000, Votes: 136,482,96,286 -> Adjusted Percentages: 14,48,10,28
Total votes: 1000, Votes: 135,140,345,95,285 -> Adjusted Percentages: 13,14,35,10,28
Total votes: 1000, Votes: 137,132,347,97,287 -> Adjusted Percentages: 14,13,34,10,29
```

so in some case, we kinda "cheat" to get to 100%, isn't that the goal after all :p ?
