### PR TITLE
fix(threads): Add thread info to messages

### LINKED ISSUE #15775: provide thread title in first thread message
For a thread, right now only the system message contains the thread title inside messageParameters.

As the clients should show the thread title in the first message but hide the system message, it would be great to also have the threadTitle also provided inside the first thread message.

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #15775

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Controller/ChatController.php [hunk 1]
```diff
@@ -1299,7 +1315,7 @@ public function getUpcomingReminders(): DataResponse {
 				continue;
 			}
 
-			$data = $message->toArray($this->getResponseFormat());
+			$data = $message->toArray($this->getResponseFormat(), null);
```
Comment (miaulalala) [inline lib/Controller/ChatController.php:1318]:
```suggestion
			$data = $message->toArray($this->getResponseFormat());
```

File: lib/Controller/ChatController.php [hunk 2]
```diff
@@ -1384,7 +1400,7 @@ public function clearHistory(): DataResponse {
 		$this->messageParser->parseMessage($systemMessage);
 
 
-		$data = $systemMessage->toArray($this->getResponseFormat());
+		$data = $systemMessage->toArray($this->getResponseFormat(), null);
```
Comment (miaulalala) [inline lib/Controller/ChatController.php:1403]:
```suggestion
		$data = $systemMessage->toArray($this->getResponseFormat());
```

File: lib/Model/Message.php [hunk 3]
```diff
@@ -184,7 +184,7 @@ public function isReplyable(): bool {
 	 * @psalm-param 'json'|'xml' $format
 	 * @return TalkChatMessage
 	 */
-	public function toArray(string $format, ?bool $isThread = null): array {
+	public function toArray(string $format, ?Thread $thread): array {
```
Comment (miaulalala) [inline lib/Model/Message.php:187]:
```suggestion
	public function toArray(string $format, ?Thread $thread = null): array {
```

File: lib/Service/RoomFormatter.php [hunk 4]
```diff
@@ -462,6 +462,6 @@ public function formatLastMessage(
 			return null;
 		}
 
-		return $message->toArray($responseFormat);
+		return $message->toArray($responseFormat, null);
```
Comment (miaulalala) [inline lib/Service/RoomFormatter.php:465]:
```suggestion
		return $message->toArray($responseFormat);
```

File: lib/Model/Message.php (hunk 3 above)
Comment (nickvergessen) [reply lib/Model/Message.php:187]: I made it a required parameter, so we are aware when the info is not provided and don't accidentally fall back to skip the thread info?

Comment (miaulalala) [reply lib/Model/Message.php:187]: makes sense, ignore my comments then. Looks good otherwise

**Review by Antreesy — APPROVED** [review]

**Comment by Antreesy** [comment]
ah, merged it before checking... 
threadTitle and threadReplies would be nice to have from other endpoints, e.g. posting a new message

**Comment by nickvergessen** [comment]
> threadTitle and threadReplies would be nice to have from other endpoints, e.g. posting a new message

Should also have it 🤔

**Comment by nickvergessen** [comment]
It's only missing when posting a thread. it works on all replies. Problem is the usual "getTopMostParentId()" is 0 for the root message
