### PR TITLE
Special handling of CLI administrators in system messages

### LINKED ISSUE #3664: Special handling of CLI interactions when managing users
## Steps to reproduce
1. Add a user via CLI to a conversation (#3465)
2. Chat shows the user was added by an administrator

### Expected behaviour
Clear message that the user was added by an admin

### Actual behaviour
Bildschirmfoto von 2020-05-25 14-28-54

cc @PhrozenByte in case you want to look into it, otherwise I might also have a look at some point

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #3664

### CODE REVIEW

File: lib/Chat/Parser/SystemMessage.php [hunk 1]
```diff
@@ -221,6 +259,11 @@ public function parseMessage(Message $chatMessage): void {
 				$parsedMessage = $this->l->t('You promoted {user} to moderator');
 			} elseif ($participant->isGuest() && $participant->getSessionId() === $parsedParameters['user']['id']) {
 				$parsedMessage = $this->l->t('{actor} promoted you to moderator');
+				if ($cliIsActor) {
+					$parsedMessage = $this->l->t('An administrator promoted you to moderator');
+				}
+			} elseif ($cliIsActor) {
+				$parsedMessage = $this->l->t('An administrator promoted {user} to moderator');
```
Comment (PhrozenByte) [inline lib/Chat/Parser/SystemMessage.php:266]: `guest_moderator_promoted` is never reached since we can't promote guests to moderators via CLI.

File: lib/Chat/Parser/SystemMessage.php [hunk 2]
```diff
@@ -229,6 +272,11 @@ public function parseMessage(Message $chatMessage): void {
 				$parsedMessage = $this->l->t('You demoted {user} from moderator');
 			} elseif ($participant->isGuest() && $participant->getSessionId() === $parsedParameters['user']['id']) {
 				$parsedMessage = $this->l->t('{actor} demoted you from moderator');
+				if ($cliIsActor) {
+					$parsedMessage = $this->l->t('An administrator demoted you from moderator');
+				}
+			} elseif ($cliIsActor) {
+				$parsedMessage = $this->l->t('An administrator demoted {user} from moderator');
```
Comment (PhrozenByte) [inline lib/Chat/Parser/SystemMessage.php:279]: `guest_moderator_demoted` is never reached since we can't demote guests from moderators via CLI.

File: lib/Chat/Parser/SystemMessage.php (hunk 1 above)
Comment (nickvergessen) [reply lib/Chat/Parser/SystemMessage.php:266]: well we can't so far, I'd like to keep it in case we do it at some point.
