### PR TITLE
fix: chat jumping when reference widgets are rendered

### LINKED ISSUE #10627: Chat doesn't properly scroll down to the last message
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a 1:1 chat
2. Fill convo so that it starts scrolling
3. Click refresh and select the chat again

### Expected behaviour
Chat should be scrolled to the very last message sent or received.

### Actual behaviour
Chat is scrolled to some arbitrary point 2-3 inches above the last message.

## Talk app

**Talk app version:** 17.1.1

**Custom Signaling server configured:** No

**Custom TURN server configured:** No

**Custom STUN server configured:** No

## Browser

**Microphone available:** Yes

**Camera available:** Yes

**Operating system:** Arch Linux

**Browser name:** Firefox and Chrome

**Browser version:** Firefox 118.0.1 and Chromium 117.0.5938.132

### Browser log

<details>

```
setVisualLastReadMessageId token=qo42gp6h id=1397 MessagesList.vue:854
The request has been canceled
Object { stack: <omitted for privacy reasons> message: "canceled", name: "CanceledError", code: "ERR_CANCELED" }
MessagesList.vue:711
InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 content-script.js:40:65
Ignoring handleScroll as the messages history is empty MessagesList.vue:755
Joined signaling.js:235:10
Scrolling to a focused message programmatically MessagesList.vue:1020
Scrolling to a focused message programmatically MessagesList.vue:1020
undefined lockdown-install.js:1:93966
```

</details>

## Server configuration

**Operating system**: Arch Linux

**Web server:** Apache

**Database:** Maria

**PHP version:** 8.2.10

**Nextcloud Version:** 27.1.0.7

**List of activated apps:**
<details>

```
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - calendar: 4.5.1
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.0
  - richdocumentscode: 23.5.402
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.1
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<removed for privacy>"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.1.0",
        "overwrite.cli.url": "<removed for privacy>",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "app_install_overwrite": [
            "bruteforcesettings",
            "richdocumentscode"
        ],
        "loglevel": 2,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_phone_region": "US",
        "theme": ""
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10627 

During testing, this fix seems smooth when joining, during scrolling and on message link (yet, needs some conditions for this case). 

### 🖼️ Screenshots / Screencasts

Before

https://github.com/nextcloud/spreed/assets/84044328/b79aae8a-cce2-4881-8941-2b8d48bc9796

After

https://github.com/nextcloud/spreed/assets/84044328/974a84ec-e357-4ecf-a637-758800ffb2a8

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 1]
```diff
@@ -401,7 +410,28 @@ export default {
...
+			if (!this.isVisible) {
+				return
+			}
+			if (this.previousSize?.width && this.previousSize.width !== width) {
+				// Resizing messages list
+				return
+			}
+			if (height === 0) {
+				// remove the default 44px of loading icon
+				this.previousSize = { width: 0, height: 0 }
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:429]:
```suggestion
				// component is unmounted
				return
```

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 2]
```diff
@@ -39,7 +39,8 @@
 			<Quote v-if="message.parent" :message="message.parent" />
 
 			<!-- Message content / text -->
-			<NcRichText :text="renderedMessage"
+			<NcRichText v-intersection-observer="onIntersectionObserver"
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:42]: I would put both directives on a root element. Then it would be the following flow for the component:

image

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 3]
```diff
@@ -4,7 +4,7 @@
 -->
 
 <template>
-	<div ref="messageMain" class="message-main">
+	<div ref="messageMain" v-element-size="onResize" class="message-main">
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:7]:
```suggestion
	<div ref="messageMain" v-element-size="[onResize, { width: 0, height: 24 }]" class="message-main">
```

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 4]
```diff
@@ -199,6 +206,8 @@ export default {
 			codeBlocks: null,
 			currentCodeBlock: null,
 			copyButtonOffset: 0,
+			isVisible: false,
+			previousSize: { width: 0, height: 44 }, // default height of loading icon
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:210]:
```suggestion
			previousSize: { width: 0, height: 24 }, // default height of one-line message body without widgets
```

**Review by Antreesy — COMMENTED** [review]
There is a negative (non-null, by 16px) change when custom widget is loaded. Then, if message is visible, it immediately resize to full height, or remain like this:
`Message resize: 175 1186  ->  1186  |  66.5  ->  50.5`. If we ignore it when chat is scrolled to bottom, then it looks good. Otherwise there are still jumps

**Comment by Antreesy** [comment]
There is also 40px jumping affecting the overall impression from loader; maybe we position it absolute and align with avatars?

image

File: src/components/MessagesList/MessagesList.vue [hunk 5]
```diff
@@ -1217,6 +1218,11 @@ export default {
 		messagesGroupComponent(group) {
 			return group.isSystemMessagesGroup ? MessagesSystemGroup : MessagesGroup
 		},
+
+		onMessageHeightChanged({ heightDiff }) {
+			// scroll down by the height difference
+			this.$refs.scroller.scrollTop += heightDiff
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:1224]: That looks better for me, but we need to track scrolling direction (could be done with `onScroll` event, and `this.previousScrollTopValue`), and it may be still flacky on corner cases (conversation switch, initial rendering)
 
```suggestion
			if (this.lastScrollDirection === 'up' || this.isChatScrolledToBottom) {
				// scroll down by the height difference
				this.$refs.scroller.scrollTop += heightDiff
			}
```

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:1224]: I don't see a reason to specify the direction as jumping happens anyway.

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:1230]: Try this one. Feels less jumpy for me, when scrolling in both directions
```suggestion
			// scroll down by the height difference
			this.$refs.scroller.scrollTop += this.isChatScrolledToBottom ? heightDiff : heightDiff / 2
```

**Review by Antreesy — APPROVED** [review]
Have no objections for merging into v30

File: src/components/MessagesList/MessagesList.vue (hunk 5 above)
Comment (DorraJaouad) [reply src/components/MessagesList/MessagesList.vue:1230]: why divided by 2 when it's not at the bottom ? it is always scrolled by heightDiff

Comment (Antreesy) [reply src/components/MessagesList/MessagesList.vue:1230]: If scroll to the middle of the widget, it looks like it's expanding in both directions
