### PR TITLE
Fix/11585/follow up all reactions button

### LINKED ISSUE #11585: Follow up to "All" reactions button
Seeing it the first time in use now, I think we should change 2 things:
grafik

- Hide the button similarly like the "Emoji plus" when the message is not hovered/focused
- To avoid jumping with above change, move the heart to the end between the reactions and the "Emoji plus"

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/11508#issuecomment-1942526250_

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #11585

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image     | image    |

### 🚧 Tasks

- [ ] Visual review
- [ ] Code review

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/Message.vue [hunk 1]
```diff
@@ -46,6 +46,7 @@
 				:id="id"
 				:token="token"
 				:can-react="canReact"
+				:is-hovered="isHovered"
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/Message.vue:49]:
```suggestion
				:show-controls="isHovered || isFollowUpEmojiPickerOpen"
```

Then it won't dissapear, if you open emoji picker and move cursor out of its borders
And naming could be adjusted a bit

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue [hunk 2]
```diff
@@ -57,8 +51,16 @@
 			</div>
 		</NcPopover>
 
+		<!-- all reactions button -->
+		<NcButton v-if="isHovered"
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue:55]:
```suggestion
		<NcButton v-if="hasReactions && showControls"
```

Don't we need to check `hasReactions`?

**Review by Antreesy — APPROVED** [review]

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue (hunk 2 above)
Comment (DorraJaouad) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue:55]: no because Reactions comp is not shown if there is no reaction.
