### PR TITLE
fix(call): hide remaining call-related UI when calls are disabled

### LINKED ISSUE #17390: [Enhancement] Hide call-related settings and dashboard buttons when calls are disabled (Follow-up to #17215)
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Disable video/audio calls on the server or restrict them via Talk administration permissions.
2. Log in as a user who does not have permission to use calls.
3. Open the Talk app Dashboard.
4. Open the Talk app Settings (gear icon).

### Expected behaviour

Since calls are disabled/restricted for the user, all call-specific UI elements should be hidden to prevent confusion. This should include the dashboard action buttons related to calls (#17215) , as well as the call-specific settings (devices, background blur, call shortcuts) in the settings modal.

Image

Image

### Actual behaviour
This is a follow-up to issue #17215 . While some UI elements are successfully hidden, many others remain visible and lead to dead ends or errors (e.g., "Camera access denied" in settings).

Left behind on the Dashboard:
1. The "Check devices" button (microphone-icon)
2. Upcoming meetings - check if there's 'Join call' button appears

Left behind on the Conversation settings:
1. Notify about calls in this conversation toggle
2. SIP settings
3. Permissions - call related ones - I'd argue this should be disabled, not hidden (@antreesy)

Left behind in the Settings Modal:
1. The entire "Devices" section (Camera/Mic selectors, Test speakers, Microphone settings, Check devices).
2. Appearance & sounds section (for call-related features)
3. ~~The entire "Performance" section (Background blur during call).~~ deprecated
4. In the "Keyboard shortcuts" section, the specific sub-section "Shortcuts while in a call".
Image

Image

<details>

### Workaround
```css
/* 1 and 2 are fixed by #17215 
/* 1. Hide the "Start a call now" button from the dashboard */
.talk-dashboard__actions button:has(.video-icon) {
    display: none !important;
}

/* 2. Hide the parent container (v-popper) to prevent empty space */
.talk-dashboard__actions > div.v-popper {
    display: none !important;
}

/* 3. Optional: Hide the "Check devices" (Mic/Camera) button */
.talk-dashboard__actions button:has(.microphone-icon) {
    display: none !important;
}

/* 4. Hide call-related settings menus (Devices and Performance) */
.app-settings__navigation li:has(a[href="#settings-section_devices"]),
.app-settings__navigation li:has(a[href="#settings-section_performance"]) {
    display: none !important;
}

/* 5. Hide the content of these sections (in case of direct link access) */
#settings-section_devices,
#settings-section_performance {
    display: none !important;
}

/* 6. Clean up the "Keyboard shortcuts" section: 
      Hide the "Shortcuts during a call" title (h3) and the following list (+ dl) */
#settings-section_shortcuts h3,
#settings-section_shortcuts h3 + dl {
    display: none !important;
}
```

</details>

## Talk app

**Talk app version:** 21.1.8
**Nextcloud version:** 31.0.13.1

Best regards,

### PR DESCRIPTION
**Pull request by notoriousisk**
Hello! This is my first contribution to this repository. Looking forward to your feedback

## ☑️ Resolves

* Fix #17390

### AI (if applicable)

- [x] The content of this PR was partly or fully generated using AI

#### Dashboard actions and upcoming meetings

🏚️ Before | 🏡 After
-- | --
Dashboard before | Dashboard after

#### App settings: devices / appearance

🏚️ Before | 🏡 After
-- | --
App settings before | App settings after

#### Keyboard shortcuts

🏚️ Before | 🏡 After
-- | --
Keyboard shortcuts before | Keyboard shortcuts after

#### Participant permissions

🏚️ Before | 🏡 After
-- | --
Participant permissions before | Participant permissions after

#### Conversation notification settings

🏚️ Before | 🏡 After
-- | --
Conversation notifications before | Conversation notifications after

### 🚧 Tasks

- [x] Hide remaining call-related dashboard actions when calls are disabled
- [x] Hide dashboard join buttons for upcoming meetings when calls are disabled
- [x] Hide call-only app settings sections and shortcuts when calls are disabled
- [x] Hide conversation call-related settings and SIP-related sidebar actions when calls are disabled
- [x] Disable call-related permission controls when calls are disabled while keeping non-call permissions editable

### 🏁 Checklist

- [x] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [x] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Review by nickvergessen — DISMISSED** [review]

**Comment by notoriousisk** [comment]
Force-pushed to fix DCO: rewrote the 4 commits so author/signoff match correctly. No code changes.

File: src/components/PermissionsEditor/PermissionsEditor.vue [hunk 1]
```diff
@@ -123,6 +127,11 @@ export default {
 			type: Boolean,
 			default: false,
 		},
+
+		token: {
+			type: String,
+			default: 'local',
```
Comment (Antreesy) [inline src/components/PermissionsEditor/PermissionsEditor.vue]: You've adjusted in both places, so default value is not needed
```suggestion
			required: true,
```

File: src/components/RightSidebar/Participants/ParticipantsTab.vue [hunk 2]
```diff
@@ -245,10 +246,11 @@ export default {
 
 		hintAddPhones() {
 			const canModerateSipDialOut = hasTalkFeature(this.token, 'sip-support-dialout')
+				&& getTalkConfig(this.token, 'call', 'enabled')
```
Comment (Antreesy) [inline src/components/RightSidebar/Participants/ParticipantsTab.vue]: Not needed, it's negated on L253

```suggestion
```

File: src/components/RightSidebar/RightSidebar.vue [hunk 3]
```diff
@@ -336,7 +336,8 @@ export default {
 		},
 
 		showSIPSettings() {
-			return this.conversation.sipEnabled !== WEBINAR.SIP.DISABLED
+			return getTalkConfig(this.token, 'call', 'enabled')
```
Comment (Antreesy) [inline src/components/RightSidebar/RightSidebar.vue]: You can't have SIP enabled without calls anyway, so I would revert this change


```suggestion
			return this.conversation.sipEnabled !== WEBINAR.SIP.DISABLED
```

File: src/components/RightSidebar/RightSidebar.vue [hunk 4]
```diff
@@ -359,7 +360,7 @@ export default {
 		},
 
 		showBreakoutRoomsTab() {
-			return this.getUserId && !this.isOneToOne
+			return getTalkConfig(this.token, 'call', 'enabled') && this.getUserId && !this.isOneToOne
```
Comment (Antreesy) [inline src/components/RightSidebar/RightSidebar.vue]: You are not blocking breakout rooms creation, so this would break.
Technically they can also function without calls (as sub-chats), so there's no harm in keeping the tab visible

```suggestion
			return this.getUserId && !this.isOneToOne
```

File: src/components/ConversationSettings/NotificationsSettings.vue [hunk 5]
```diff
@@ -44,7 +44,8 @@ const notificationLevels = [
 const store = useStore()
 
 const showCallNotificationSettings = computed(() => {
-	return !props.conversation.remoteServer || hasTalkFeature(props.conversation.token, 'federation-v2')
+	return getTalkConfig(props.conversation.token, 'call', 'enabled')
```
Comment (Antreesy) [inline src/components/ConversationSettings/NotificationsSettings.vue:47]: Counterpart is missing in `src/components/LeftSidebar/ConversationsList/ConversationItem.vue` -> `showCallNotificationSettings()`

Image

File: src/components/Dashboard/EventCard.vue [hunk 6]
```diff
@@ -219,7 +220,7 @@ function handleJoin({ call }: { call: boolean }) {
 				{{ invitesLabel }}
 			</span>
 			<NcButton
-				v-if="(hasCall && !isInCall)"
+				v-if="isCallEnabled && hasCall && !isInCall"
```
Comment (Antreesy) [inline src/components/Dashboard/EventCard.vue]: hasCall is already enough and won't be truthy, if you disable calls globally. So another check is unnecessary

```suggestion
				v-if="hasCall && !isInCall"
```

File: src/components/ConversationSettings/ConversationSettingsDialog.vue [hunk 7]
```diff
@@ -43,7 +43,7 @@
 
 			<!-- Meeting: lobby and sip -->
 			<NcAppSettingsSection
-				v-if="canFullModerate && !isNoteToSelf"
+				v-if="isCallEnabled && canFullModerate && !isNoteToSelf"
```
Comment (Antreesy) [inline src/components/ConversationSettings/ConversationSettingsDialog.vue]: Lobby isn't limited to calls, so shouldn't be hidden
```suggestion
				v-if="canFullModerate && !isNoteToSelf"
```

File: src/components/ConversationSettings/ConversationSettingsDialog.vue [hunk 8]
```diff
@@ -208,7 +208,11 @@ export default {
 
 	computed: {
 		canUserEnableSIP() {
-			return this.conversation.canEnableSIP
+			return this.isCallEnabled && this.conversation.canEnableSIP
```
Comment (Antreesy) [inline src/components/ConversationSettings/ConversationSettingsDialog.vue]: canEnableSIP is false, if not configured, so unnecessary check

```suggestion
			return this.conversation.canEnableSIP
```

File: src/components/ConversationSettings/ConversationSettingsDialog.vue [hunk 9]
```diff
@@ -278,25 +282,29 @@ export default {
...
+			return this.isCallEnabled
+				&& !this.isLiveTranscriptionSupported
 				&& this.selfIsOwnerOrModerator
 				&& showTalkFeatureHint(34)
 		},
 
 		canConfigureBreakoutRooms() {
-			return !this.isVoiceRoom
+			return this.isCallEnabled
+				&& !this.isVoiceRoom
```
Comment (Antreesy) [inline src/components/ConversationSettings/ConversationSettingsDialog.vue]:
```suggestion
			return !this.isVoiceRoom
```

File: src/components/ConversationSettings/ConversationPermissionsSettings.vue [hunk 10]
```diff
@@ -189,6 +194,10 @@ export default {
 		 * which case it's a number indicating the permissions value.
 		 */
 		async handleSubmitPermissions(value) {
+			if (!this.isCallEnabled && ['all', 'restricted'].includes(value)) {
+				return
+			}
```
Comment (Antreesy) [inline src/components/ConversationSettings/ConversationPermissionsSettings.vue]: Should not be blocked and disabled, as it also affect 'chat'/'react'/'lobby' permissions

Maybe text hints can be edited to not mention 'call' permissions

File: src/components/PermissionsEditor/PermissionsEditor.vue [hunk 11]
```diff
@@ -217,14 +238,18 @@ export default {
 		 * accordingly.
 		 */
 		formPermissions() {
```
Comment (Antreesy) [inline src/components/PermissionsEditor/PermissionsEditor.vue:232]: I wouldn't mess with this value, if we're just disabling checkboxes and not editing them

**Review by Antreesy — COMMENTED** [review]
Thanks for the work done! Left some comments on the changes:

**Comment by notoriousisk** [comment]
Thanks for the review
Addressed the review comments and pushed the requested changes. 
I applied the suggested simplifications, added the missing call-notification check in the sidebar, and updated the permissions settings hints so they only change when calls are disabled.
@Antreesy could you take another look?

File: src/components/ConversationSettings/ConversationPermissionsSettings.vue (hunk 10 above)
Comment (notoriousisk) [reply src/components/ConversationSettings/ConversationPermissionsSettings.vue]: I updated the hint text so it no longer references call-specific behaviour when calls are disabled.

Let me know if this matches what you had in mind

Comment (Antreesy) [reply src/components/ConversationSettings/ConversationPermissionsSettings.vue]: > 'all' - Participants can use all available features.
> 'restricted' - Participants get a reduced feature set until a moderator manually grants additional permissions.

Good enough! Will check later as a follow-up, if we can opt for these descriptions for consistency.

**Review by Antreesy — APPROVED** [review]
Looks nice now, tested.
Thanks for the great contribution! 🎉
