### PR TITLE
Fix missing Talk sidebar trigger in public share pages

### LINKED ISSUE #7578: Trigger on public share page is not visible
https://github.com/nextcloud/spreed/blob/9e9197cc56fd8374c4916ba1fd029721cd1a5486/src/mainPublicShareSidebar.js#L98-L115

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #7576
Fixes #7578

Since the removal of SCSS files the `menu-people` icon can no longer be used directly with a CSS class. However, it is available as a Vue component; although it would be possible to directly render the Vue component for the icon* inside the button element the whole button is moved to Vue instead, as the other approach requires more fighting with the styles.

*For reference in case it is ever needed:
```
const talkSidebarTriggerIconVm = new Vue({
	// MenuPeople is a functional component, so it needs to be explicitly
	// rendered rather than just spread (...MenuPeople) in the constructor
	// of the Vue instance.
	render: h => h(MenuPeople, {
		props: {
			fillColor: 'var(--color-primary-text)',
			size: 20,
			decorative: true,
		},
	}),
})
talkSidebarTriggerIconVm.$mount('#talk-sidebar-trigger-icon')
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
It's not a functional component anymore with #7592 🤕😅

File: src/PublicShareSidebarTrigger.vue [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+  - You should have received a copy of the GNU Affero General Public License
+  - along with this program. If not, see <http://www.gnu.org/licenses/>.
+  -
+  -->
+
+<template>
+	<Button @click="$emit('click')">
+		<MenuPeople :size="20"
+			fill-color="var(--color-primary-text)"
+			decorative />
```
Comment (nickvergessen) [inline src/PublicShareSidebarTrigger.vue:25]:
```suggestion
			fill-color="var(--color-primary-text)" />
```

File: src/PublicShareSidebarTrigger.vue [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+  - GNU Affero General Public License for more details.
+  -
+  - You should have received a copy of the GNU Affero General Public License
+  - along with this program. If not, see <http://www.gnu.org/licenses/>.
+  -
+  -->
+
+<template>
+	<Button @click="$emit('click')">
+		<MenuPeople :size="20"
```
Comment (nickvergessen) [inline src/PublicShareSidebarTrigger.vue:23]: Should be wrapped in a `<template #icon>` so it's in the slot

File: src/PublicShareSidebarTrigger.vue [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+  - GNU Affero General Public License for more details.
+  -
+  - You should have received a copy of the GNU Affero General Public License
+  - along with this program. If not, see <http://www.gnu.org/licenses/>.
+  -
+  -->
+
+<template>
+	<Button @click="$emit('click')">
```
Comment (nickvergessen) [inline src/PublicShareSidebarTrigger.vue:22]: Needs aria-label attribute as per console warning

File: src/PublicShareSidebarTrigger.vue [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+		Button,
+		MenuPeople,
+	},
+
+}
+</script>
+
+<style lang="scss" scoped>
+/* Match style for header buttons defined in server stylesheets. */
+.button-vue {
```
Comment (nickvergessen) [inline src/PublicShareSidebarTrigger.vue:47]: Sound like the button component needs another mode,
Can you raise an issue please in the vue repo?

**Review by nickvergessen — CHANGES_REQUESTED** [review]

**Comment by Fazzrol** [comment]
[www -zimperium@gmail.com]-http://@paswor

File: src/PublicShareSidebarTrigger.vue (hunk 3 above)
Comment (danxuliu) [reply src/PublicShareSidebarTrigger.vue]: I asked Marco about the aria label and then forgot to add it :facepalm: 

Anyway, I have added it but I can not get rid of the console warning. I guess I made some silly mistake when passing the property to the button or something like that, but I can not find out what :shrug:

File: src/PublicShareSidebarTrigger.vue (hunk 4 above)
Comment (danxuliu) [reply src/PublicShareSidebarTrigger.vue:66]: I will do tomorrow.

File: src/PublicShareSidebarTrigger.vue (hunk 3 above)
Comment (nickvergessen) [reply src/PublicShareSidebarTrigger.vue]: The warning also comes from other bits, but talk is mostly got with my PR

Comment (danxuliu) [reply src/PublicShareSidebarTrigger.vue]: Now that the button component was replaced by a div the warning is gone (but I nevertheless added the aria label to the div).

File: src/PublicShareSidebarTrigger.vue (hunk 4 above)
Comment (nickvergessen) [reply src/PublicShareSidebarTrigger.vue]: Reported at https://github.com/nextcloud/nextcloud-vue/issues/2869 so it's not lost.

Comment (nickvergessen) [reply src/PublicShareSidebarTrigger.vue]: > I should not have used a button component but a div with role="button" and class="menutoggle", as that is what is used in all header buttons.

That is what you do right now, correct? Because it does not work with keyboard navigation e.g. so still an issue.
But I'm fine proceeding as at least the button is back and clickable with the mouse for now.

**Comment by nickvergessen** [comment]
Keyboard tabbing before https://github.com/nextcloud/nextcloud-vue/issues/2869

Bildschirmfoto vom 2022-07-21 16-19-00

Keyboard tabbing with https://github.com/nextcloud/nextcloud-vue/issues/2869

Bildschirmfoto vom 2022-07-21 16-14-07

So let's get this in https://github.com/nextcloud/nextcloud-vue/pull/2871

**Comment by nickvergessen** [comment]
Vue lib is in

File: src/PublicShareSidebarTrigger.vue [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+			return t('spreed', 'Open Talk sidebar')
+		},
+	},
+
+}
+</script>
+
+<style scoped>
+.button-holder {
+	margin: 2px 5px 2px 2px;
```
Comment (danxuliu) [inline src/PublicShareSidebarTrigger.vue:68]: [Header contents are vertically centered](https://github.com/nextcloud/server/blob/87320cba99229e065747d699461b1dddc54326f8/core/css/header.scss#L196-L200). Are the vertical margins needed?

Out of curiosity, why 5px instead of 2px for `margin-right`?

File: src/PublicShareSidebarTrigger.vue [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+	display: flex;
+	justify-content: center;
```
Comment (danxuliu) [inline src/PublicShareSidebarTrigger.vue:70]: Is it needed to horizontally center the button? As the div has no explicit width it should have the width of its child elements, so the button should be already centerd in the div. Or am I missing something?

**Review by danxuliu — COMMENTED** [review]
[Header menu toggles](https://github.com/nextcloud/server/blob/master/core/css/header.scss#L226) and [app buttons](https://github.com/nextcloud/server/blob/master/core/css/header.scss#L444) have an opacity of 0.85, but [the Vue button uses 0.7](https://github.com/nextcloud/nextcloud-vue/blob/183f6e9139b9c4e884783e8afec2bda499815e72/src/components/Button/Button.vue#L607). Should the opacity be increased (in _PublicShareSidebarTrigger_)?

Other than the comments, tested and works :+1:

Thanks for adding the style for the Vue button!

File: src/PublicShareSidebarTrigger.vue (hunk 5 above)
Comment (nickvergessen) [reply src/PublicShareSidebarTrigger.vue:68]: The margins where needed otherwise the box shadow was cut off.

For the right sidebar I added 3px on top so the white border of keyboard active doesn't touch the browser as it looked too weird.

File: src/PublicShareSidebarTrigger.vue (hunk 6 above)
Comment (nickvergessen) [reply src/PublicShareSidebarTrigger.vue:70]: Copied this from the app icons and only then the centering worked as expected.

**Review by marcoambrosini — APPROVED** [review]

File: src/PublicShareSidebarTrigger.vue (hunk 5 above)
Comment (danxuliu) [reply src/PublicShareSidebarTrigger.vue:68]: > The margins where needed otherwise the box shadow was cut off.

I tried removing the margins (or, rather, replacing with `margin-right: 3px`) and as far as I can tell it was working fine :shrug: That is why I was asking. But maybe it depends on the browser, I do not know.

> For the right sidebar I added 3px on top so the white border of keyboard active doesn't touch the browser as it looked too weird.

:+1:

File: src/PublicShareSidebarTrigger.vue (hunk 6 above)
Comment (danxuliu) [reply src/PublicShareSidebarTrigger.vue:70]: Same as above, I tried removing the rules and as far as I can tell it was working fine. But same as above, maybe it is related to the browser, no idea :shrug:

**Comment by danxuliu** [comment]
> We should probably not rely on the opacity for the hover effect in the button in the first place @danxuliu

And how it should be done? Using a background? Something else? In any case it should be changed in [nextcloud-vue](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L621-L642) as well as in the header stylesheet.

**Comment by marcoambrosini** [comment]
Yes I mean changing it in the vue library. The hover feedback can be just the change in cursor (we have a `tertiary` style that has a background feedback), this one should be used only for special cases. The keyboard navigation feedback is a big box shadow.

**Comment by nickvergessen** [comment]
Since vue 5.4 is merged, this can be rebased and then merged.

**Comment by nickvergessen** [comment]
Nevermind, one of the things that was merged after 5.4.0 https://github.com/nextcloud/nextcloud-vue/pull/2940

**Comment by nickvergessen** [comment]
Rebased

**Comment by nickvergessen** [comment]
As per chat:
> Also I'd vote to merge the sidebar trigger even though it currently shows wrong colors, but at least it can be used again

Updating the vue lib to 6 with #7711 will fix it.

**Review by nickvergessen — APPROVED** [review]
