### PR TITLE
fix(TalkDashboard): make home button a link for a11y and UX and add refresh function 

### LINKED ISSUE #15321: Make home button primary when in home view
Just like with other navigation elelments, I think this button should become primary when the home view is active.

Image

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #15321

### 🖼️ Screenshots / Screencasts

When current page is dashboard.

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/LeftSidebar/LeftSidebar.vue [hunk 1]
```diff
@@ -508,6 +509,16 @@ export default {
...
 		},
+
+		isInDashboard() {
+			return this.$route.name === 'root'
+		},
+
+		dashboardButtonLabel() {
+			return this.isInDashboard
+				? t('spreed', 'Reload dashboard')
+				: t('spreed', 'Talk home')
```
Comment (ShGKme) [inline src/components/LeftSidebar/LeftSidebar.vue]: It is confusing that sometimes this button is for `home`, but sometimes for `dashboard`.

File: src/services/EventBus.ts [hunk 2]
```diff
@@ -36,6 +36,7 @@ export type Events = {
 	'poll-editor-open': { token: string, id: number | null, fromDrafts: boolean, action?: string, selector?: string }
 	'refresh-peer-list': void
 	'retry-message': number
+	'refresh-talk-dashboard': void
```
Comment (ShGKme) [inline src/services/EventBus.ts:38]: 🥲

File: src/components/LeftSidebar/LeftSidebar.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/components/LeftSidebar/LeftSidebar.vue]: home only on the surface, dashboard BTS :p

Comment (DorraJaouad) [reply src/components/LeftSidebar/LeftSidebar.vue]: maybe `Reload Talk home` is more consistent here

Comment (ShGKme) [reply src/components/LeftSidebar/LeftSidebar.vue]: The page itself has no accessible name (the heading is "Hello, displayName").
I'd use dashboard as this is the name used in the blog and in the changelog.

But the important part is to keep it consistent on a single button. Otherwise for a screen reader it is:
1. "Link, Talk home, Talk home" (some screen-readers doesn't handle title duplicating aria-label)
2. *click*
3. "Link, Reload dashboard, current page" (it was for home, and not it is for some dashboard without moving to a new location).

File: src/components/LeftSidebar/LeftSidebar.vue [hunk 3]
```diff
@@ -9,12 +9,13 @@
...
+						:variant="isInDashboard ? 'primary' : 'tertiary'"
 						:class="{ 'hidden-visually': isSearching }"
 						class="talk-home-button"
-						:title="t('spreed', 'Talk home')"
-						:aria-label="t('spreed', 'Talk home')"
-						@click="showTalkDashboard">
+						:title="dashboardButtonLabel"
+						:aria-label="dashboardButtonLabel"
+						:to="{ name: 'root' }"
+						@click="refreshTalkDashboard">
```
Comment (ShGKme) [inline src/components/LeftSidebar/LeftSidebar.vue:18]: To fix in `nextlcoud/vue`: `aria-current` is missing.

File: src/components/Dashboard/TalkDashboard.vue [hunk 4]
```diff
@@ -73,6 +73,8 @@ async function actualiseData() {
 onMounted(() => {
 	actualiseData()
 	actualiseDataInterval = setInterval(actualiseData, 300_000)
+
+	EventBus.on('refresh-talk-dashboard', actualiseData)
 })
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: I'd restart a timer here in that case. Also could be called earlier without onMounted hook?
```suggestion
initActualizeData()
EventBus.on('refresh-talk-dashboard', initActualizeData)

function initActualizeData() {
	if (actualiseDataInterval) {
		clearInterval(actualiseDataInterval)
	}
	actualiseData()
	actualiseDataInterval = setInterval(actualiseData, 300_000)
}
```

**Review by Antreesy — COMMENTED** [review]
Otherwise fine

File: src/components/LeftSidebar/LeftSidebar.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/LeftSidebar/LeftSidebar.vue]: IIRC we should not use it to not conflict with Nextcloud Dashboard. So `reload Talk home` sounds valid here from my pov

File: src/components/Dashboard/TalkDashboard.vue (hunk 4 above)
Comment (ShGKme) [reply src/components/Dashboard/TalkDashboard.vue]: In this case it should be `setTimeout` (it is restarted on each iteration anyway)

Comment (Antreesy) [reply src/components/Dashboard/TalkDashboard.vue]: Unless you're staying on home page longer than 5 minutes, then `actualiseData()` should set it again

**Review by Antreesy — APPROVED** [review]
What was wrong with `actualiSe`?)

**Comment by DorraJaouad** [comment]
> What was wrong with `actualiSe`?)

I am used to `actualize` and we are mainly using american english so..
