### PR TITLE
fix(permissions): Fix the permissions editor claiming custom permissions are used, when all boxes are ticked

### LINKED ISSUE #8924: all advanced permissions are set when lobby is started
## Steps to reproduce
see video
[Screencast_02.03.2023_10:59:38.webm](https://user-images.githubusercontent.com/2932790/222440924-ae85dc1e-7c1e-43d9-b269-b1a792632404.webm)

### Expected behaviour
advanced permissions are not set

### Actual behaviour
all advanced permissions are set when lobby is started

Firefox
Nextcloud 26.0.0 beta 5 on sermo

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #8924 

### Steps (before)

1. Create a conversation
2. Open settings permissions section: 🗒️ (expected) **Advanced** 👀 (actual) **Advanced**
3. Go to advanced 
4. Grant "Skip lobby"
5. "Update permissions"
6. Settings: 🗒️ (expected) **All permissions** 👀 (actual) **Advanced**

### Steps (after)

1. Create a conversation
2. Open settings permissions section: 🗒️ (expected) **Advanced** 👀 (actual) **Advanced**
3. Go to advanced 
4. Grant "Skip lobby"
5. "Update permissions"
6. Settings: 🗒️ (expected) **All permissions** 👀 (actual) **All permissions**

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/components/ConversationSettings/ConversationPermissionsSettings.vue [hunk 1]
```diff
@@ -221,6 +221,7 @@ export default {
 		getPermissionRadioValue(value) {
 			switch (value) {
 			case PERMISSIONS.MAX_DEFAULT:
+			case PERMISSIONS.MAX_CUSTOM:
```
Comment (Antreesy) [inline src/components/ConversationSettings/ConversationPermissionsSettings.vue:224]: Could we do the same for 'Restricted'?

https://user-images.githubusercontent.com/93392545/223188099-83d032c0-cbe7-4d78-bd2d-762e4efdea0f.mp4

Comment (nickvergessen) [reply src/components/ConversationSettings/ConversationPermissionsSettings.vue:224]: Added
