### PR TITLE
fix(notifications): Allow sessions to mark themselves as inactive

### LINKED ISSUE #1575: Notifications for chats are not showing when browser tab/window is inactive
## Steps to reproduce
1. Join a chat and stay in room but change browser tab
2. Make someone in the room send you a message
3. No notification raised

### Expected behaviour
As the browser tab or window is not active, user should be marked as inactive and the receive notification.

### Actual behaviour
No notification is raised because of user not being marked "inactive" on window change.
So you are to miss all messages from other until you go back to Nextcloud talk tab/window

## I removed many of items asked in this bug in order to keep it clear. Those were not revelant.
If you miss any information, please feel free to ask.

## Browser ALL

**Operating system:** Ubuntu
**Browser name:** Firefox/Chrome

**Browser version:** 65 for Firefox

## Spreed app

**Spreed app version:** 5.0.2

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:**

**Nextcloud Version:** 15.0.4

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #1575
* Current session (opened room) will be marked as inactive if:
  * Tab was hidden or minimized
  * Tab was blurred, and there were not any movements on it for 3 minutes
* If inactive, it will receive notifications for this tab as well

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Migration/Version18000Date20230920182747.php [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+	 * @param IOutput $output
+	 * @param Closure(): ISchemaWrapper $schemaClosure
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		$modified = false;
```
Comment (SystemKeeper) [inline lib/Migration/Version18000Date20230920182747.php:45]: Not needed?

Comment (nickvergessen) [reply lib/Migration/Version18000Date20230920182747.php]: fixed

File: src/composables/useActiveSession.js [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+import { SESSION } from '../constants.js'
+import { setSessionState } from '../services/participantsService.js'
+import { useStore } from './useStore.js'
+
+const supportSessionState = getCapabilities()?.spreed?.features?.includes('session-state')
+const INACTIVE_TIME_MS = 3 * 60 * 1000
+/**
+ * Check whether the current session is active or not:
+ * - tab or browser window was moved to background or minimized
+ * - there was not movements within tab window for a long time
```
Comment (nickvergessen) [inline src/composables/useActiveSession.js:34]: and not in a call?

File: src/composables/useActiveSession.js [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+		if (currentState.value === SESSION.STATE.INACTIVE) {
+			return
+		}
+		clearTimeout(inactiveTimer.value)
+		inactiveTimer.value = null
+		currentState.value = SESSION.STATE.INACTIVE
+
+		try {
+			await setSessionState(token.value, SESSION.STATE.INACTIVE)
+			showInfo(t('spreed', 'Session has been marked as inactive'))
```
Comment (nickvergessen) [inline src/composables/useActiveSession.js:100]: console.info

Not sure about `showInfo` might be helpful if you see it on another screen though.

File: src/composables/useActiveSession.js [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+	const currentState = ref(SESSION.STATE.ACTIVE)
+
+	watch(token, () => {
+		// Joined conversation has active state by default
+		currentState.value = SESSION.STATE.ACTIVE
+	})
+
+	watch(windowIsVisible, (value) => {
+		// Change state if tab is hidden or minimized
+		// FIXME upstream: Notifications app doesn't work in background
```
Comment (nickvergessen) [inline src/composables/useActiveSession.js:57]: Not sure what you mean, the notifications app should work fine.
It even has code to track visibility because we change the page title to prefix it with `*` when you receive something, so pinned tabs are highlighted.

Comment (Antreesy) [reply src/composables/useActiveSession.js:57]: I don't see native browser notifications, when tab is minimized, only when tab is opened again, new notification is added to the list and trigger browser notification to show

File: src/composables/useActiveSession.js (hunk 3 above)
Comment (Antreesy) [reply src/composables/useActiveSession.js:100]: Looks like this. It will provide at least some info, why you start to receive notifications from the chat, which is currently opened. But for sure, we could remove this and leave only `console.info`

image

Comment (nickvergessen) [reply src/composables/useActiveSession.js:100]: Let's do both

File: src/composables/useActiveSession.js [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+	const currentState = ref(SESSION.STATE.ACTIVE)
+
+	watch(token, () => {
+		// Joined conversation has active state by default
+		currentState.value = SESSION.STATE.ACTIVE
+	})
+
+	watch(windowIsVisible, (value) => {
+		// Change state if tab is hidden or minimized
+		// FIXME: Notifications app doesn't show browser notifications if in background
```
Comment (nickvergessen) [inline src/composables/useActiveSession.js:58]:
```suggestion
```

I think this does not belong here. Also I just tested it again and it works as expected on my side.

Comment (Antreesy) [reply src/composables/useActiveSession.js]: Rebased, squashed fixup and removed this comment

**Review by nickvergessen — COMMENTED** [review]
Frontend code seems to work 👍🏼

**Review by Antreesy — APPROVED** [review]
Backend also works fine
