### PR TITLE
Correctly get new messages for guests

### LINKED ISSUE #3020: Public chats load the full history everytime
## Steps to reproduce
1. Open a browser + network tab
2. Go to https://cloud.nextcloud.com/call/c7fz9qpr

### Expected behaviour
200 messages loaded and then it should calm down

### Actual behaviour
CPU gets busy and loads all messages (eventually bringing the browser to the knees)
It also tries to load avatars again and again (maybe the 404 which guests currently see in most cases should be cached by the avatar component in a shared matter, so it doesn't try to load it for each message of the same user again...)

### PR DESCRIPTION
**Pull request by nickvergessen**
For guests we also need to set the last known message id
after the first grab of the history, otherwise they start loading
the full history with getNewMessages() because last known message
is still 0. Since the requests for getNewMessages() are doine right
away, it will make constant requests until the full chat is loaded

Fix #3020 

### Steps to reproduce
1. Create a public conversation with some messages
2. As a guest open the chat with network tab open
3. See a request to get the history
4. See a second request getting new messages containing the "XYZ created the conversation" (indicator that the chat beginning is loaded instead of new messages)

### CODE REVIEW

File: src/components/MessagesList/MessagesList.vue [hunk 1]
```diff
@@ -366,23 +366,38 @@ export default {
...
 						token: token,
-						id: messages.headers['x-chat-last-given'],
+						id: parseInt(messages.headers['x-chat-last-given'], 10),
+					})
+				}
+
+				// For guests we also need to set the last known message id
+				// after the first grab of the history, otherwise they start loading
+				// the full history with getNewMessages().
+				if (includeLastKnown && newestKnownMessageId
```
Comment (danxuliu) [inline src/components/MessagesList/MessagesList.vue]: As the last known message id is only set if it was not already set, is it really needed to limit this to `includeLastKnown` being enabled too?

Comment (nickvergessen) [reply src/components/MessagesList/MessagesList.vue]: Yes, otherwise a subsequent getOldMessages() call would set it's own newest message as last known, and then we would fetch the messages of the first getOldMessages() call with the next getNewMessages() call.

Comment (danxuliu) [reply src/components/MessagesList/MessagesList.vue]: > a subsequent getOldMessages() call would set it's own newest message as last known

But in a subsequent `getOldMessages()` call the last known message id would be already set, so it would not be set again, no? Anyway, this is already merged, so... :-P
