### PR TITLE
fix(federation): Don't send notifications for most system messages in…

### LINKED ISSUE #12307: Edit in a federated conversation moves conversation to the top again
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. A conversation hosted on server "S" adds a user from server "C" as a federated user
2. Messages are exchanged and the conversation is not the top of the list anymore
3. A user from server "S" edits a message

### Expected behaviour
The conversation should not be moved to the top of the conversation list again (this seems to be the case for non-federated conversations)

### Actual behaviour
The conversation is moved to the top again, although it is still marked as read. 
Not sure if we need to take into account if it was the last message because of soft-updating, but in the observed case it was not the last message.

## Talk app

**Talk app version:** 19.0.0

### PR DESCRIPTION
**Pull request by nickvergessen**
… federation

### ☑️ Resolves

* Fix #12307 

### 🚧 Tasks

- [x] Don't create push notifications
- [x] Don't bump the last activity

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Notification/FederationChatNotifier.php [hunk 1]
```diff
@@ -111,6 +113,14 @@ protected function isMentionedAll(Room $room, ProxyCacheMessage $message): bool
 		return false;
 	}
 
+	protected function isUserMessageOrRelevantSystemMessage(?string $systemMessage): bool {
+		return $systemMessage === null
+			|| $systemMessage === ''
+			|| $systemMessage === 'object_shared'
+			|| $systemMessage === 'poll_closed'
+			|| $systemMessage === 'file_shared';
```
Comment (SystemKeeper) [inline lib/Notification/FederationChatNotifier.php:121]: `reaction`?
