### PR TITLE
fix: handle password policy validation

### LINKED ISSUE #13651: Setting a password shows success even when failing due to password policy
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have password policy enabled
2. Set a password for conversation

### Expected behaviour
Error should be shown, when password does not comply to policy

### Actual behaviour
If you're slow enough, a validation message is shown -> But still allowing you to save the password with a success message!
If you're fast, _no_ validation message is shown, just showing a success toast.

https://github.com/user-attachments/assets/e0037942-57b0-4b50-bfa3-50ba55249df6

## Talk app

**Talk app version:** main

### PR DESCRIPTION
**Pull request by sanskar-soni-9**
### ☑️ Resolves

* Fix #13651 

## 🖌️ UI Checklist

- Added `@valid`, `@invalid` handlers to ensure password meets policy requirements
- Moved success and error handling to store

### 🏡 After
https://github.com/user-attachments/assets/1ed6fe01-6bc3-441e-8bca-76fda648d27d

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [x] Not risky to browser differences / client
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/ConversationSettings/LinkShareSettings.vue [hunk 1]
```diff
@@ -123,6 +125,7 @@ export default {
 			showPasswordField: false,
 			isSaving: false,
 			isSendingInvitations: false,
+			isValid: true,
```
Comment (Antreesy) [inline src/components/ConversationSettings/LinkShareSettings.vue:128]: Also should be done/checked in `NewConversationSetupPage`, as most passwords should be provided from the beginning

And in this component, `handleSetNewPassword` method should be blocked with invalid password, so keydown 'Enter' won't send it

File: src/components/ConversationSettings/LinkShareSettings.vue [hunk 2]
```diff
@@ -38,8 +38,10 @@
 					:disabled="isSaving"
 					class="password-form__input-field"
 					label-visible
-					:label="t('spreed', 'Enter new password')" />
-				<NcButton :disabled="isSaving" type="primary" native-type="submit">
+					:label="t('spreed', 'Enter new password')"
+					@valid="isValid = true"
+					@invalid="isValid = false" />
+				<NcButton :disabled="isSaving || !isValid" type="primary" native-type="submit">
```
Comment (Antreesy) [inline src/components/ConversationSettings/LinkShareSettings.vue:44]: Something off with styles (locally and on video)
Nevertheless, align to top (considering margin) and flex-shrink: 0 for the button, to not squeeze it?

image

**Comment by sanskar-soni-9** [comment]
I didn't added flex-shrink as it was making things overflow

**Review by DorraJaouad — APPROVED** [review]
Tested ✅ all good regarding password policy.

Follow-up: remove the action to submit empty password as it's only possible now if you just enable the password radio button (it won't make sense to show "Conversation password has been removed" while you haven't set one yet). I will add this in further refactoring.

Thank you for you contribution 🥳 Looking forward to your next PR.
