### PR TITLE
fix(messages): fix missing instant reactions for own message

### LINKED ISSUE #14670: Immediate reactions from bots are not always visible
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Post a message that a bot reacts to

### Expected behaviour
Always see the +1

### Actual behaviour
Not always see the +1

Desktop where I posted | Web afterwards
---|---
Image | Image

## Assumption

The temporary message got moved or the responses came in a non good order so that when creating the message in the store it was not aware of the reaction

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #14670

**Explanation:**
Own message can be added to polling response (1) before receiving the message creation response (2), the bot will thus react before (2) and another polling response will be received containing the bot reaction system message (3). 
The final order is: (1) -> (3) -> (2) 

We always update by the recent response, which is (2) in this case and it's outdated. 

**Workaround:**
As own message in polling is always up to date (e.g. contains reactions), we skip the update with (2) when (1) is already received.

### 🖼️ Screenshots / Screencasts

🏚️ Before 

https://github.com/user-attachments/assets/6ba4ac9e-eb16-41d6-b37c-a94d3d1ae302 

🏡 After

https://github.com/user-attachments/assets/a287769d-f81f-4210-bf4b-f4d8898348a9

### 🚧 Tasks

- [x] Test with bots

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/store/messagesStore.js [hunk 1]
```diff
@@ -1281,7 +1281,10 @@ const actions = {
 				})
 			}
 
-			context.dispatch('processMessage', { token, message: response.data.ocs.data })
+			// Own message might have been added already by polling, which is more up-to-date (e.g. reactions)
+			if (!Object.keys(context.getters.message(token, response.data.ocs.data.id)).length) {
```
Comment (Antreesy) [inline src/store/messagesStore.js:1285]:
```suggestion
			if (!context.state.messages[token]?.[response.data.ocs.data.id]) {
```

**Review by Antreesy — APPROVED** [review]
Tested, nice addition!

_logging just before PR changes_
```js
console.log(context.state.messages[token][response.data.ocs.data.id])
console.log(context.getters.message(token, response.data.ocs.data.id))
```
image
