### PR TITLE
fix: replace moment.js with Intl formatters

### LINKED ISSUE #14434: Remove moment.js
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

`moment.js` (`@nextcloud/moment`) is deprecated, unmaintained, and in many cases unnecessary.

Instead:
- When possible, replace with simple JS (`Date`)
- For l10n - use `Intl`
- If necessary - for more complex cases use [dayjs](https://day.js.org/) (without i18n)
- Also fixes: https://github.com/nextcloud/spreed/issues/3441

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #14434

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Banned user date | -
'lll', `Feb 15, 2025 8:30 PM` | 'dateTimeShort', `Feb 15, 2025, 8:30 PM`
Bot last error | -
'll LTS', `Feb 15, 2025 8:30:00 PM` | 'dateTimeShortWithSeconds', `Feb 15, 2025, 8:30:00 PM`
Hosted HPB expiration dates | -
'L', `02/15/2025` | 'dateNumeric', `02/15/2025`
Lobby start time | -
'LLL', `February 15, 2025 8:30 PM` | 'dateTimeLong', `February 15, 2025 at 8:30 PM`
Message time and date | -
'LT', `8:30 PM` | 'timeShort', `8:30 PM`
'LL', `February 15, 2025` | 'dateLong', `February 15, 2025`
'lll', `Feb 15, 2025 8:30 PM` | 'dateTimeShort', `Feb 15, 2025, 8:30 PM`
Message reminders | -
'LT', `8:30 PM` | 'timeShort', `8:30 PM`
'ddd LT', `Sat 8:30 PM` | 'weekdayTimeShort', `Sat 8:30 PM`
'LLL', `February 15, 2025 8:30 PM` | 'dateTimeLong', `February 15, 2025 at 8:30 PM`
Absence period | -
'll', `Feb 15, 2025` | 'dateShort', `Feb 15, 2025`

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/CalendarEventsDialog.vue [hunk 1]
```diff
@@ -67,13 +66,13 @@ const submitting = ref(false)
...
 const calendars = computed(() => groupwareStore.calendars)
 const upcomingEvents = computed(() => {
-	const now = convertToUnix(Date.now())
 	return groupwareStore.getAllEvents(props.token)
 		.sort((a, b) => (a.start && b.start) ? (a.start - b.start) : 0)
 		.map(event => {
-			const start = event.start
-				? (event.start <= now) ? t('spreed', 'Now') : moment(event.start * 1000).calendar()
-				: ''
+			const start = (!event.start || event.start * 1000 <= Date.now())
```
Comment (DorraJaouad) [inline src/components/CalendarEventsDialog.vue:72]: How can we know that if an event doesn't have start, it means it's going on now?

File: src/components/CalendarEventsDialog.vue [hunk 2]
```diff
@@ -227,6 +226,40 @@ function getCurrentDateInStartOfNthHour(hours: number) {
 	return date
 }
 
+/**
+ * Returns human-readable string with event start
+ * @param time event start time (in ms)
+ */
+function getEventStartLabel(time: number) {
```
Comment (DorraJaouad) [inline src/components/CalendarEventsDialog.vue:233]: Fits better in `fromattedTime` util?

**Review by DorraJaouad — COMMENTED** [review]
I am not sure about the behavior when Locale is different from Language
Before | After
-- | --
image|image

image

File: src/components/CalendarEventsDialog.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/CalendarEventsDialog.vue:72]: backend returns only future events, if you happen to catch the case like this, it's likely happening at this moment

File: src/components/CalendarEventsDialog.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/CalendarEventsDialog.vue:233]: Will move there

**Comment by Antreesy** [comment]
cc @nimishavijay for string changes (see tables and screenshots)

There's a possibility to keep '1 week ago' for exact 7 days in chat, but I don't think it's worth (and don't know, how it will look like in different languages)

**Comment by nimishavijay** [comment]
Nice! Thank you for getting rid of 02/22/2025 🫂

> There's a possibility to keep '1 week ago' for exact 7 days in chat, but I don't think it's worth (and don't know, how it will look like in different languages)

I agree, nobody else (WhatsApp, Slack and Telegram) show more than "Today" and "Yesterday", after that it's day of the week upto one week in WhatsApp and only absolute dates in signal and telegram

Couple of questions: 
- [x] is it possible to remove the year if it is the same as the current year? So `February 22, 2025` --> `February 22` and `December 15, 2024` stays the same. 
- [ ] I would suggest we remove the absolute date for yesterday and today. So `Yesterday, March 4, 2025` --> `Yesterday`
- [x] I would also suggest we keep the first letter capital for "Today", "Yesterday", etc. We rarely use the first letter lowercase in our UI

**Comment by ShGKme** [comment]
> * I would suggest we remove the absolute date for yesterday and today. So `Yesterday, March 4, 2025` --> `Yesterday`

I liked `Yesterday, March 4, 2025` style. I do not always remember what the day was yesterday :D

**Comment by Antreesy** [comment]
> we remove the absolute date for yesterday and today

I'm also not a fan of that idea. But it look lighter with a year omitted, what do you all think?
en | de | ru
-- | -- | --
image |image | image

**Comment by nimishavijay** [comment]
> But it look lighter with a year omitted

Works for me! The idea was to make it shorter, but if that comprises the usability then this is a good middle ground 👍🏼

File: src/utils/formattedTime.ts [hunk 3]
```diff
@@ -2,11 +2,25 @@
...
+const absoluteTimeFormat = {
+	shortTime: new Intl.DateTimeFormat(locale, { hour: 'numeric', minute: 'numeric' }), // '8:30 PM'
+	longDate: new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'long', day: 'numeric' }), // 'February 15, 2025'
+	longDateWithTime: new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric' }), // 'February 15, 2025 at 8:30 PM'
+	shortDate: new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric' }), // 'Feb 15, 2025'
+	shortDateNumeric: new Intl.DateTimeFormat(locale, { year: 'numeric', month: '2-digit', day: '2-digit' }), // '02/15/2025'
+	shortDateWithTime: new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }), // 'Feb 15, 2025, 8:30 PM'
+	shortDateWithTimeSeconds: new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric' }), // 'Feb 15, 2025, 8:30:00 PM'
+	shortWeekdayWithTime: new Intl.DateTimeFormat(locale, { weekday: 'short', hour: 'numeric', minute: 'numeric' }), // 'Sat 8:30 PM'
+} as const
```
Comment (ShGKme) [inline src/utils/formattedTime.ts:22]: Not sure I understand the idea of replacing options with custom key names, when it is direct mapping

**Review by ShGKme — APPROVED** [review]

File: src/utils/formattedTime.ts (hunk 3 above)
Comment (Antreesy) [reply src/utils/formattedTime.ts:22]: You mean we can go with:
```diff
- return formatDateTime(this.trialAccount.created, 'shortDateNumeric')
+ return formatDateTime(this.trialAccount.created, { year: 'numeric', month: '2-digit', day: '2-digit' })
```
?

It could be fine, but I brought the shortest example. For generic and reused keys, I think, map formatters fit better and easier to use?

**Comment by ShGKme** [comment]
🥳💃🎉

File: src/utils/formattedTime.ts (hunk 3 above)
Comment (ShGKme) [reply src/utils/formattedTime.ts:22]: Yes, that is what I meant.

Mapping is shorter. But it is something custom, requiring to go to the source to see what it actually means. While the long object is a native value, describing the format.

Also, in some options it can be shortened with `dateFormat`, I guess.

I understand mapping with more semantic meaning, like "messageTime".
