### PR TITLE
fix: duplicate stun and turn servers cannot be added

### LINKED ISSUE #11852: Same stun and turn server can be added multiple times via occ
> while scripting this stuff: The stun and turn commands allow adding the same server multiple times with the exact same config. It would be helpful if duplicates would be ignored

_Originally posted by @pschichtel in https://github.com/nextcloud/spreed/issues/11851#issuecomment-2005116301_

### PR DESCRIPTION
**Pull request by skalidindi53**
### ☑️ Resolves

* Fix #11852

### 🚧 Tasks

- [x] Implemented logic to check if a TURN/STUN server is already added before adding a new one
- [x] Added a test case for checking duplicate servers

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by Antreesy** [comment]
Hi, Shankar! Edited a PR info a bit:
- don't forget to put labels and assign yourself;
- same with assigning reviewers, if PR is ready;
- Milestone should be set as most recent - 💙 Next Major (30) - now, if it goes to `main` branch
- Then we're backporting it to stable branches with `/backport to stableX`, and bot does the job with assigning, labelling, and setting the milestones

File: lib/Command/Turn/Add.php [hunk 1]
```diff
@@ -98,6 +98,19 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 			$servers = [];
 		}
 
+		//Checking if the server is already added
+		foreach ($servers as $existingServer) {
+			if (
+				$existingServer['server'] === $server &&
+				$existingServer['protocols'] === $protocols &&
+				$existingServer['secret'] === $secret
```
Comment (nickvergessen) [inline lib/Command/Turn/Add.php:106]: *Question:*
Should also error if the same server+protocol exists with a different secret?

**Must:**
Should also check the schema?

File: tests/php/Command/Stun/AddTest.php [hunk 2]
```diff
@@ -85,4 +85,19 @@ public function testAddServerToNonEmptyList(): void {
...
+		$this->config->method('getAppValue')
+			->with('spreed', 'stun_servers')
+			->willReturn(json_encode(['stun.test.com:443']));
+		$this->config->expects($this->never())
+			->method('setAppValue');
+		$this->output->expects($this->once())
+			->method('writeln')
+			->with($this->equalTo('<error>Server already exists.</error>'));
+	
+		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
```
Comment (nickvergessen) [inline tests/php/Command/Stun/AddTest.php:101]: **Must:**
```suggestion
		$this->assertSame(1, self::invokePrivate($this->command, 'execute', [$this->input, $this->output]));
```

File: tests/php/Command/Turn/AddTest.php [hunk 3]
```diff
@@ -376,4 +376,42 @@ public function testServerSanitization(): void {
...
+				'secret' => 'my-test-secret',
+				'protocols' => 'udp,tcp'
+			]]));
+		$this->config->expects($this->never())
+			->method('setAppValue');
+		$this->output->expects($this->once())
+			->method('writeln')
+			->with($this->equalTo('<error>Server already exists with the same configuration.</error>'));
+	
+		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
```
Comment (nickvergessen) [inline tests/php/Command/Turn/AddTest.php:414]: **Must:**
```suggestion
		$this->assertSame(1, self::invokePrivate($this->command, 'execute', [$this->input, $this->output]));
```

File: tests/php/Command/Turn/AddTest.php [hunk 4]
```diff
@@ -376,4 +376,42 @@ public function testServerSanitization(): void {
 
 		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
 	}
+	public function testAddDuplicateServer(): void {
```
Comment (nickvergessen) [inline tests/php/Command/Turn/AddTest.php:379]: *Nitpick:*
```suggestion

	public function testAddDuplicateServer(): void {
```

File: tests/php/Command/Stun/AddTest.php [hunk 5]
```diff
@@ -85,4 +85,19 @@ public function testAddServerToNonEmptyList(): void {
 
 		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
 	}
+	public function testAddDuplicateServer(): void {
```
Comment (nickvergessen) [inline tests/php/Command/Stun/AddTest.php:88]: *Nitpick:*
```suggestion

	public function testAddDuplicateServer(): void {
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]
