### PR TITLE
Fix command description

### LINKED ISSUE #9362: Wrong description of `talk:monitor:room`
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. `occ talk:monitor:room --help`

### Expected behaviour
The correct description of the command should be given

### Actual behaviour
The same description as `occ talk:monitor:calls` is given

## Talk app

**Talk app version:** 16.0.3

### PR DESCRIPTION
**Pull request by vitormattos**
### ☑️ Resolves

* Fix #9362

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Command/Monitor/Room.php [hunk 1]
```diff
@@ -46,7 +46,7 @@ protected function configure(): void {
 
 		$this
 			->setName('talk:monitor:room')
-			->setDescription('Prints a list with conversations that have an active call as well as their participant count')
+			->setDescription('Prints the total of attendeers, sessions and active participants.')
```
Comment (nickvergessen) [inline lib/Command/Monitor/Room.php:49]:
```suggestion
			->setDescription('Prints the number of attendees, active sessions and participant in a call.')
```
