### PR TITLE
Fix(BreakoutRoomsEditor): Add amount validation

### LINKED ISSUE #11355: Incorrect handling of invalid breakout rooms number
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. In `Configure breakout rooms` dialog enter value outside of allowed range 1-20 (i.e. `0` or `21`).
2. Press `Create rooms`.

### Expected behaviour

Web UI should clearly display allowed rooms range and `Number of breakout rooms` field shouldn't allow entering values outside of allowed range (defined in backend see below).

In case of breakout rooms creating error, no breakout rooms should be created.

### Actual behaviour
Web UI allows `Number of breakout rooms` values outside of range enforced in backend with
```public const MINIMUM_ROOM_AMOUNT = 1;
public const MAXIMUM_ROOM_AMOUNT = 20;
```

When user enters value outside of this range i.e. `0` or `21` and presses `Create rooms`, an error
```
An error occurred while creating breakout rooms
```
is thrown but 1 breakout room is created (and must be removed to allow one to setup correct number of breakout rooms).

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

v18.0.1

## Browser

Firefox ESR.

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #11355

Hint is conditioned because the user will likely pick an amount from 1 to 20, but it will be shown in case they attempt to choose outside that range.

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image      | image     |

### 🚧 Tasks

- [ ] Code review
- [ ] Visual review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue [hunk 1]
```diff
@@ -30,6 +30,9 @@
 			<template v-if="!isEditingParticipants">
 				<div class="breakout-rooms-editor__main">
 					<label class="breakout-rooms-editor__caption" for="room-number">{{ t('spreed', 'Number of breakout rooms') }} </label>
+					<p v-if="isInvalidAmount" class="breakout-rooms-editor__error-hint">
+						{{ t('spreed', 'You can create up to 20 breakout rooms.') }}
+					</p>
 					<NcTextField id="room-number"
```
Comment (nickvergessen) [inline src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:36]: shouldn't the min/max from this component already help with that?

Comment (Antreesy) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:36]: With `min`/`max` we can use a native method `input.checkValidity()`, which returns `true`/`false` in case amount is out of range. But that is not implemented upstream in the vue-library, there I believe it belongs

Comment (nickvergessen) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:36]: yeah that's what I mean. The component should handle this already

Comment (DorraJaouad) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:36]: Yeap, once it is fixed from the upstream we can just replace the boolean `this.isInvalidAmount` with output of the native `checkValidity()` because we still need it for disabling the buttons and maybe keeping the hint 😁.

File: src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue [hunk 2]
```diff
@@ -147,6 +157,7 @@ export default {
 		// now it breaks validation. Another option: Create NcNumberField component
 		setAmount(value) {
 			this.amount = parseFloat(value)
+			this.isInvalidAmount = this.amount > 20 || this.amount < 1
```
Comment (Antreesy) [inline src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:160]:
```suggestion
			this.isInvalidAmount = isNaN(this.amount) || !this.$refs.textField.$refs.inputField.$refs.input?.checkValidity()
```
Maybe a bit ugly, but it checks, if input is not empty and not out of range of provided `min`/`max`

**Review by Antreesy — COMMENTED** [review]
After checking the upstream code, it now make  a little sense for me to literally upstream it :grimacing: 

We still could do at the place (with refs and without pure JS) but to expose `checkValidity()` from lib is not as needed as to expose `focus()`, for example.
In addition to that, NcInput is simple visual / low-functional component, so again, I don't see any point in making it more complicate upstream

File: src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue (hunk 2 above)
Comment (DorraJaouad) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:160]: Literally the same validation as the current one ?

Comment (Antreesy) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:160]: You just got lucky, that `NaN < 1` =)
It's safer, and you define max/min ranges only at the one place (component attrs)

**Review by Antreesy — APPROVED** [review]
