### PR TITLE
Use app with no-camera devices

### LINKED ISSUE #160: Should also work when person only has microphone and no cam
In many cases people don’t have a webcam but only microphone (or headset), especially on desktop computers. Instead of not working at all, we should handle this gracefully:

- Still ask for permission to use the microphone
- Show the avatar placeholder for yourself and for the others (currently a black video view is shown)
- Maybe give some feedback about the missing webcam in case it’s not working or you forgot you have one

cc @fancycode @Ivansss @LukasReschke can we make that work?

### PR DESCRIPTION
**Pull request by Ivansss**
- Fix #160

### CODE REVIEW

File: js/simplewebrtc.js [hunk 1]
```diff
@@ -5360,7 +5360,7 @@
 				self.emit('localStream', stream);
 			} else {
 				// Fallback for users without a camera
-				if (self.config.audioFallback && err.name === 'DevicesNotFoundError' && constraints.video !== false) {
+				if (self.config.audioFallback && ((err.name === 'DevicesNotFoundError') || (err.name === 'NotFoundError')) && constraints.video !== false) {
```
Comment (nickvergessen) [inline js/simplewebrtc.js]: Fewer brackets should be okay as well:
`(err.name === 'DevicesNotFoundError' || err.name === 'NotFoundError')`
