### PR TITLE
Remove undefined property or method usage

### LINKED ISSUE #6868: Dashboard throws error
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Unknown, just opened the dev tools

### Expected behaviour
✅ 

### Actual behaviour
```
[Vue warn]: Property or method "handlers" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>) 2 [vue.runtime.esm.js:619](webpack:///talk/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 3
    fn Dashboard.vue:53
    VueJS 2
    render vue-dashboard.js:783
    renderList VueJS
    render vue-dashboard.js:780
    VueJS 14
    fetchRooms Dashboard.vue:188
    (Async: promise callback)
    fetchRooms Dashboard.vue:177
    beforeMount Dashboard.vue:164
    VueJS 4
    <anonym> dashboard.js:45
    rerenderPanels App.vue:295
    callbacks App.vue:231
    VueJS 5
```

## Talk app

**Talk app version:** 13.0.1

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 96

### Browser log

<details>
```
[Vue warn]: Property or method "handlers" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>) 2 [vue.runtime.esm.js:619](webpack:///talk/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 3
    fn Dashboard.vue:53
    VueJS 2
    render vue-dashboard.js:783
    renderList VueJS
    render vue-dashboard.js:780
    VueJS 14
    fetchRooms Dashboard.vue:188
    (Async: promise callback)
    fetchRooms Dashboard.vue:177
    beforeMount Dashboard.vue:164
    VueJS 4
    <anonym> dashboard.js:45
    rerenderPanels App.vue:295
    callbacks App.vue:231
    VueJS 5
```

</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Regression from dd8d415473d7a39ecfcfaec7cea0f4b52466c796

Fix #6868

### CODE REVIEW

File: src/views/Dashboard.vue [hunk 1]
```diff
@@ -31,8 +31,7 @@
 			<DashboardWidgetItem :target-url="getItemTargetUrl(item)"
 				:main-text="getMainText(item)"
 				:sub-text="getSubText(item)"
-				:item="item"
-				v-on="handlers">
```
Comment (marcoambrosini) [inline src/views/Dashboard.vue:35]: was it maybe meant to be `v-on="$listeners"`?

Comment (nickvergessen) [reply src/views/Dashboard.vue:35]: No, I copied the content from:
https://github.com/nextcloud/nextcloud-vue-dashboard/blob/de7e24fdbb0f53cdbe0affddfd219bbd335399a2/src/DashboardWidget.vue#L46
And while adjusting forgot to remove it. We have no handlers in talk
