### PR TITLE
fix/9446/add-empty-call-view-to-viewer-overlay

### LINKED ISSUE #9446: Show an empty call view in the viewer overlay then there is only 1 participant or connection
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce

1. Start a new call with nobody
2. Open a file in the viewer

The same, if everybody leave, expect one participant. Or it is still connecting.

### Expected behaviour

There is an empty call view in the viewer overlay

### Actual behaviour

There is no viewer overlay, you don't know, if the call is active.

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix #9446

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

Gif with the smallest size

EmptyCallViewOnOverlay

Fullscreen on light theme

image

### 🚧 Tasks

- [x] Add EmptyCallView to ViewerOverlayCallView

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by ShGKme** [comment]
Tested on web and desktop with light and dark theme on small and large screen

**Comment by Antreesy** [comment]
Not visible for me, until other user is connected. Tested at public and  private conversations

https://user-images.githubusercontent.com/93392545/236529057-e8515ce1-ff9c-4fc3-8fd1-9d2534683f19.mp4

**Review by Antreesy — APPROVED** [review]
Everything is perfect from code perspective :seal: 
Tested on web client

**Comment by ShGKme** [comment]
> P.S. Now it works. and I can not reproduce it again 🤔

Maybe old cache?

**Comment by nickvergessen** [comment]
So merge?

File: src/components/CallView/shared/ViewerOverlayCallView.vue [hunk 1]
```diff
@@ -277,7 +293,7 @@ export default {
 }
 
 .viewer-overlay__video {
-	position: relative;
-	height: 100%;
+  position: relative;
+  height: 100%;
```
Comment (nickvergessen) [inline src/components/CallView/shared/ViewerOverlayCallView.vue:297]: https://github.com/nextcloud/server/blob/master/.editorconfig#L8-L9

That is not our intended coding style btw.
I guess the config is not picked up by your editor because you work directly in the talk repo instead of having a project with nextcloud and the app inside?
Should we copy it to talk?

**Comment by ShGKme** [comment]
Rebased onto master and fixed indents, no other changes

**Review by nickvergessen — APPROVED** [review]
