### PR TITLE
fix(reactions): set expiry of reaction message to parent message expiry

### LINKED ISSUE #11298: Message expiration fails to delete emoji reactions from database
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a conversation in Talk, send a message and emoji react to it
2. Enable message expiration and wait for the message to expire
3. Dump the `oc_comments` table from the database

### Expected behaviour
Both the message and reaction are deleted from the database on expiration

### Actual behaviour
The message is deleted as expected, but the database table still contains a row describing the reaction

## Talk app

**Talk app version:** 16.0.4

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

N/A since this is surely a server-side problem

## Server configuration

**Operating system**: Debian

**Web server:** Apache, Caddy

**Database:** MySQL

**PHP version:** 8.2.8

**Nextcloud Version:** 26

**List of activated apps:**

<details>

```
  - bruteforcesettings: 2.6.0
  - calendar: 4.6.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.5.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - encryption: 2.14.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_accesscontrol: 1.16.2
  - files_automatedtagging: 1.16.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_retention: 1.15.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - impersonate: 1.13.1
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - richdocuments: 8.0.2
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.4
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_saml: 5.2.1
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.3.2",
        "overwritehost": "XXX",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "XXX",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "auto, 40",
        "versions_retention_obligation": "auto",
        "theme": ""
    }
}
```
</details>

### Server log (data/nextcloud.log)

Can provide this if necessary, but seems very long

### PR DESCRIPTION
**Pull request by miaulalala**
### ☑️ Resolves

* Fixes #11298

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not possible
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by miaulalala** [comment]
> Deleting a reaction works already?

Do you mean cascading the delete when the parent is deleted?

**Comment by nickvergessen** [comment]
In terms of "does the reaction_revoked message already have an expiration"

**Comment by miaulalala** [comment]
> In terms of "does the reaction_revoked message already have an expiration"

Added expiry date to revoked reactions

File: lib/Chat/ReactionManager.php [hunk 1]
```diff
@@ -119,6 +121,7 @@ public function deleteReactionMessage(Room $chat, string $actorType, string $act
 			])
 		);
 		$comment->setVerb(ChatManager::VERB_REACTION_DELETED);
+		$comment->setExpireDate($parentComment->getExpireDate());
```
Comment (nickvergessen) [inline lib/Chat/ReactionManager.php]: I fear this should be in the addSystemMessage
Now you are changing the expiration data of the original message.

But I guess that one does it already.

Comment (miaulalala) [reply lib/Chat/ReactionManager.php]: I added a check for reaction_deleted

Comment (nickvergessen) [reply lib/Chat/ReactionManager.php]: But the system message below should expire, not the old message above, that one should be unchanged

Comment (miaulalala) [reply lib/Chat/ReactionManager.php]: Why should the reaction deleted comment not expire if the parent comment expires?
