### PR TITLE
Fix: remove warnings on phpunit9.5.6

### LINKED ISSUE #6228: PHPUnit 10 warnings
```

There were 47 warnings:

1) OCA\Talk\Tests\BackgroundJob\CheckHostedSignalingServerTest::testRunWithNoChange
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

2) OCA\Talk\Tests\BackgroundJob\CheckHostedSignalingServerTest::testRunWithPendingToActiveChange
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

3) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterUsersAdd with data set #0 (2, '', array(array('guests'), array('users', 'alice_actor', 3), array('users', 'alice_actor', 5), array('users', 'bob', 3), array('users', 'alice_actor')), array(array('users', 'alice_actor', array('user_added', array('alice_actor'))), array('users', 'alice_actor', array('user_added', array('bob')))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

4) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterUsersAdd with data set #1 (3, '', array(array('guests'), array('users', 'alice_actor', 3), array('users', 'alice_actor', 5), array('users', 'bob', 3), array('users', 'alice_actor')), array(array('users', 'alice_actor', array('user_added', array('alice_actor'))), array('users', 'alice_actor', array('user_added', array('bob')))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

5) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterUsersAdd with data set #3 (2, 'file', array(array('guests'), array('users', 'alice_actor', 3), array('users', 'alice_actor', 5), array('users', 'bob', 3), array('users', 'alice_actor')), array(array('users', 'alice_actor', array('user_added', array('alice_actor'))), array('users', 'alice_actor', array('user_added', array('bob')))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

6) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterUsersAdd with data set #4 (3, 'file', array(array('guests'), array('users', 'alice_actor', 3), array('users', 'alice_actor', 5), array('users', 'bob', 3), array('users', 'alice_actor')), array(array('users', 'alice_actor', array('user_added', array('alice_actor'))), array('users', 'alice_actor', array('user_added', array('bob')))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

7) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterParticipantTypeSet with data set #1 ('users', 3, 2, array(array('moderator_promoted', array('bob_participant'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

8) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterParticipantTypeSet with data set #2 ('users', 2, 3, array(array('moderator_demoted', array('bob_participant'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

9) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterParticipantTypeSet with data set #3 ('guests', 4, 6, array(array('guest_moderator_promoted', array('bob_participant'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

10) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterParticipantTypeSet with data set #4 ('guests', 6, 4, array(array('guest_moderator_demoted', array('bob_participant'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

11) OCA\Talk\Tests\php\Chat\SystemMessage\ListenerTest::testAfterParticipantTypeSet with data set #5 ('users', 5, 3, array(array('user_added', array('bob_participant'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

12) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareOne2One with data set #0 ('admin', 'Admin', 'Admin invited you to a privat...sation')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

13) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareOne2One with data set #1 ('test', 'Test user', 'Test user invited you to a pr...sation')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

14) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareGroup with data set #0 (2, 'admin', 'Admin', 'Group', 'Admin invited you to a group ... Group')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

15) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareGroup with data set #1 (3, 'test', 'Test user', 'Public', 'Test user invited you to a gr...Public')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

16) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "one-to-one mention" ('mention', 1, array('users', 'testUser'), 'Test user', 'Test user', 'Test user mentioned you in a ...sation', array('{user} mentioned you in a pri...sation', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Test user', 'one2one'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

17) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user mention" ('mention', 2, array('users', 'testUser'), 'Test user', 'Room name', 'Test user mentioned you in co...m name', array('{user} mentioned you in conve...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'group'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

18) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user mention" ('mention', 2, array('users', 'testUser'), null, 'Room name', 'A deleted user mentioned you ...m name', array('A deleted user mentioned you ...{call}', array(array('call', 1234, 'Room name', 'group'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

19) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user mention public" ('mention', 3, array('users', 'testUser'), 'Test user', 'Room name', 'Test user mentioned you in co...m name', array('{user} mentioned you in conve...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'public'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

20) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user mention public" ('mention', 3, array('users', 'testUser'), null, 'Room name', 'A deleted user mentioned you ...m name', array('A deleted user mentioned you ...{call}', array(array('call', 1234, 'Room name', 'public'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

21) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "guest mention" ('mention', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest mentioned you in conv...m name', array('A guest mentioned you in conv...{call}', array(array('call', 1234, 'Room name', 'public'))), false, null)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

22) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "named guest mention" ('mention', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'MyNameIs (guest) mentioned yo...m name', array('{guest} (guest) mentioned you...{call}', array(array('call', 1234, 'Room name', 'public'), array('guest', 'random-hash', 'MyNameIs'))), false, 'MyNameIs')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

23) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "empty named guest mention" ('mention', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest mentioned you in conv...m name', array('A guest mentioned you in conv...{call}', array(array('call', 1234, 'Room name', 'public'))), false, '')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

24) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "one-to-one message" ('chat', 1, array('users', 'testUser'), 'Test user', 'Test user', 'Test user sent you a private message', array('{user} sent you a private message', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Test user', 'one2one'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

25) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user message" ('chat', 2, array('users', 'testUser'), 'Test user', 'Room name', 'Test user sent a message in c...m name', array('{user} sent a message in conv...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'group'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

26) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user message" ('chat', 2, array('users', 'testUser'), null, 'Room name', 'A deleted user sent a message...m name', array('A deleted user sent a message...{call}', array(array('call', 1234, 'Room name', 'group'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

27) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user message public" ('chat', 3, array('users', 'testUser'), 'Test user', 'Room name', 'Test user sent a message in c...m name', array('{user} sent a message in conv...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'public'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

28) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user message public" ('chat', 3, array('users', 'testUser'), null, 'Room name', 'A deleted user sent a message...m name', array('A deleted user sent a message...{call}', array(array('call', 1234, 'Room name', 'public'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

29) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "guest message" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest sent a message in con...m name', array('A guest sent a message in con...{call}', array(array('call', 1234, 'Room name', 'public'))), false, null)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

30) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "named guest message" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'MyNameIs (guest) sent a messa...m name', array('{guest} (guest) sent a messag...{call}', array(array('call', 1234, 'Room name', 'public'), array('guest', 'random-hash', 'MyNameIs'))), false, 'MyNameIs')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

31) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "empty named guest message" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest sent a message in con...m name', array('A guest sent a message in con...{call}', array(array('call', 1234, 'Room name', 'public'))), false, '')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

32) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "one-to-one reply" ('reply', 1, array('users', 'testUser'), 'Test user', 'Test user', 'Test user replied to your pri...essage', array('{user} replied to your private message', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Test user', 'one2one'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

33) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user reply" ('reply', 2, array('users', 'testUser'), 'Test user', 'Room name', 'Test user replied to your mes...m name', array('{user} replied to your messag...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'group'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

34) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user reply" ('reply', 2, array('users', 'testUser'), null, 'Room name', 'A deleted user replied to you...m name', array('A deleted user replied to you...{call}', array(array('call', 1234, 'Room name', 'group'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

35) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user message reply" ('reply', 3, array('users', 'testUser'), 'Test user', 'Room name', 'Test user replied to your mes...m name', array('{user} replied to your messag...{call}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'public'))))
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

36) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user message reply" ('reply', 3, array('users', 'testUser'), null, 'Room name', 'A deleted user replied to you...m name', array('A deleted user replied to you...{call}', array(array('call', 1234, 'Room name', 'public'))), true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

37) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "guest reply" ('reply', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest replied to your messa...m name', array('A guest replied to your messa...{call}', array(array('call', 1234, 'Room name', 'public'))), false, null)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

38) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "named guest reply" ('reply', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'MyNameIs (guest) replied to y...m name', array('{guest} (guest) replied to yo...{call}', array(array('call', 1234, 'Room name', 'public'), array('guest', 'random-hash', 'MyNameIs'))), false, 'MyNameIs')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

39) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "empty named guest reply" ('reply', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'A guest replied to your messa...m name', array('A guest replied to your messa...{call}', array(array('call', 1234, 'Room name', 'public'))), false, '')
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

40) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "one-to-one push" ('chat', 1, array('users', 'testUser'), 'Test user', 'Test user', 'Test user\nHi @Administrator', array('{user}\n{message}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Test user', 'one2one'), array('highlight', '123456789', 'Hi @Administrator'))), false, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

41) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user push" ('chat', 2, array('users', 'testUser'), 'Test user', 'Room name', 'Test user in Room name\nHi @A...trator', array('{user} in {call}\n{message}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'group'), array('highlight', '123456789', 'Hi @Administrator'))), false, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

42) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user push" ('chat', 2, array('users', 'testUser'), null, 'Room name', 'Deleted user in Room name\nHi...trator', array('Deleted user in {call}\n{message}', array(array('call', 1234, 'Room name', 'group'), array('highlight', '123456789', 'Hi @Administrator'))), true, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

43) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "user push public" ('chat', 3, array('users', 'testUser'), 'Test user', 'Room name', 'Test user in Room name\nHi @A...trator', array('{user} in {call}\n{message}', array(array('user', 'testUser', 'Test user'), array('call', 1234, 'Room name', 'public'), array('highlight', '123456789', 'Hi @Administrator'))), false, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

44) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "deleted user push public" ('chat', 3, array('users', 'testUser'), null, 'Room name', 'Deleted user in Room name\nHi...trator', array('Deleted user in {call}\n{message}', array(array('call', 1234, 'Room name', 'public'), array('highlight', '123456789', 'Hi @Administrator'))), true, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

45) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "guest push public" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'Guest in Room name\nHi @Administrator', array('Guest in {call}\n{message}', array(array('call', 1234, 'Room name', 'public'), array('highlight', '123456789', 'Hi @Administrator'))), false, null, true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

46) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "named guest push public" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'MyNameIs (guest) in Room name...trator', array('{guest} (guest) in {call}\n{message}', array(array('call', 1234, 'Room name', 'public'), array('guest', 'random-hash', 'MyNameIs'), array('highlight', '123456789', 'Hi @Administrator'))), false, 'MyNameIs', true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

47) OCA\Talk\Tests\php\Notifications\NotifierTest::testPrepareChatMessage with data set "empty named guest push public" ('chat', 3, array('guests', 'testSpreedSession'), null, 'Room name', 'Guest in Room name\nHi @Administrator', array('Guest in {call}\n{message}', array(array('call', 1234, 'Room name', 'public'), array('highlight', '123456789', 'Hi @Administrator'))), false, '', true)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

WARNINGS!
Tests: 507, Assertions: 1931, Warnings: 47.

```

### PR DESCRIPTION
**Pull request by vitormattos**
# How to reproduce

Run tests using PHPUnit 9.5.6

# Solution

Replaced all calls to method `at` by more specific functions

close #6228

### CODE REVIEW

File: tests/php/BackgroundJob/CheckHostedSignalingServerTest.php [hunk 1]
```diff
@@ -81,15 +81,15 @@ public function getBackgroundJob(): CheckHostedSignalingServer {
...
+		$this->config
 			->method('getAppValue')
-			->with('spreed', 'hosted-signaling-server-account-id', '')
-			->willReturn('my-account-id');
-		$this->config->expects($this->at(1))
-			->method('getAppValue')
-			->with('spreed', 'hosted-signaling-server-account', '{}')
-			->willReturn('{"status": "pending"}');
-		$this->config->expects($this->at(2))
+			->willReturnCallback(function ($appid, $key, $default) {
```
Comment (nickvergessen) [inline tests/php/BackgroundJob/CheckHostedSignalingServerTest.php:86]: You can use `willReturnMap` instead (available on all versions too):

https://phpunit.readthedocs.io/en/9.5/test-doubles.html#test-doubles-stubs-examples-stubtest5-php

**Review by nickvergessen — APPROVED** [review]
