### PR TITLE
Adjust typing indicator behaviour

### LINKED ISSUE #9589: typing indicator distorted on small sidebar during call when 3 or more people are typing
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go into call
2. wait until 3 or more people are typing
3. see screenshot
image

### Expected behaviour
It should look nice

### Actual behaviour
it doesnt

## Talk app

**Talk app version:** the one of c.nc.c

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### LINKED ISSUE #9604: Typing indicator does not "expire"
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. A: Join a room
2. B: Typing
3. A: See "B is typing …" message
4. A: Switch to another room before B stops
5. B: Submit the message
6. A: Return to the room

### Expected behaviour
See the message of B and no typing indicator

### Actual behaviour
See the message of B and "B is typing …"

## Talk app

**Talk app version:** master/17rc2

**HPB** yes

### LINKED ISSUE #9615: Signaling messages wrong when conversation is switched
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps
1. Join `Room1`
2. Start typing
3. Switch to `Room2` before the typing indicator timed out

### Expected behaviour
* There should be a `stoppedTyping` message send to `Room1` before the room is left. 
* No message is send to `Room2`.

### Actual behaviour
* No message is send to `Room1`
* There is a `startedTyping`(!) message send to `Room2`

Could be related to #9604 

## Talk app

**Talk app version:** Sermo -> I don't think #9603 fixes these cases

### LINKED ISSUE #9624: Alignment of typing indicator behaviour
Currently the behaviour especially of the web heavily diverges from the mobile clients

## Before

* Android:
  * Start typing on first typing
  * Stop on send message
  * Stop after 5 sec of no change
* iOS:
  * Start typing on first typing
    * Or when a new person joins
  * Stop on leave room
  * Stop on send message
  * Stop after 5 sec of no change
* Web/Desktop:
  * Start typing on key stroke when not sent in the last 5 seconds
  * Stop after 5sec timeout is reached
  * Stop after clearing input (sent message or ctrl+a ctrl+x)

## Improved / Aligned

So we plan to align the behaviour of all clients for a consistent and better to handle result

- [ ] As typing person
  - [ ] Send "Typing" every 10 sec when there was a change
  - [ ] Stop on leave room
  - [ ] Stop on send message
- [ ] As receiver
  - [ ] Hide user from indicator after not receive "Typing" in the last 15 sec
  - [ ] Group sessions by actor type + actor id
  - [ ] Ignore self

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #9589 
* Fix #9604
* Fix #9615
* Fix #9624

🏚️ Before | 🏡 After
---|---
image | image

---

After the first key stroke, we send first `true` signal start to watching after input value, if it was changed within intervals:
* 0-10s: if something else was typed, after 10s from the start we send another `true` signal;
* 10-20s: if still typing, after 20s from the start we send another`true` signal;
* ... and repeat for each 10s interval.

In that case, first possible `true` signal will be received in 0s + delay after actor started typing;
consequent signals will come every 10s + delay.

---

`false` signal will be received:
* after actor sent message: in 0s + delay;
`false` signal will be set locally by client:
* after actor left chat: in 0s;
* after actor stopped typing (input value wasn't changed in 10s interval): in 15-24s;

As typing person
  - [x] Send "Typing" every 10 sec when there was a change - done with interval
  - [x] Stop on leave room - already done on receiving end
  - [x] Stop on send message - the only stop-signal to be sent

As receiver
  - [x] Hide user from indicator after not receive "Typing" in the last 15 sec - done with store
  - [x] Group sessions by actor type + actor id - should work as-is
  - [x] Ignore self - done with store, adjusted in tests

---

### 🚧 Tasks

- [ ] Code review
- [ ] Behaviour check

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
✅ Looks gokd from the screenshot but didnt review the code and didnt test

File: src/components/NewMessage/NewMessageTypingIndicator.vue [hunk 1]
```diff
@@ -121,6 +127,27 @@ export default {
...
+						typing: false,
+					})
+				}
+			})
+		}, 5000)
+	},
+
+	beforeDestroy() {
+		clearInterval(this.observationInterval)
+	},
```
[the remark this answers is not in the document]
Comment (ShGKme) [reply src/components/NewMessage/NewMessageTypingIndicator.vue:149]: Current solution with setInterval 5s and checking the timestamp if close to the required behavior of 15s indicator lifetime but not equal to.

Stopping time is not connected to the start time, for example
- interval is started on moment `0s`
- `start` is received at `1s` (supposed to be invalidated at `16s`)
- At `15s` interval is checking for invalid typings -> nothing has been found (start was `14s` ago)
- At `30s` interval is checking again -> typing has been found -> removed

Instead of 15 seconds is was removed after 29 seconds.

[the remark this answers is not in the document]
Comment (ShGKme) [reply src/components/NewMessage/NewMessageTypingIndicator.vue:149]: Also, it is not good for performance. Most likely, especially on a small server, most of the time there are no typings. But we have an interval that checks every 5 seconds even if the browser is not active.

[the remark this answers is not in the document]
Comment (ShGKme) [reply src/components/NewMessage/NewMessageTypingIndicator.vue:149]: In any solution, I think all those logic should not be a part of typing indicator UI element. Who is typing is a global state, typings are added in the store, and the store is responsible for inserting indicators and can control when it should be removed after inserting.

While `NewMessageTypingIndicator` is a UI element showing 

With this solution, state will be not correct without rendering UI component, the component's remounting will break this process and it is not reusable.

File: src/store/participantsStore.js [hunk 2]
```diff
@@ -85,16 +85,14 @@ const getters = {
...
 	 * @return {Array} the typing session IDs array.
 	 */
-	externalTypingSignals: (state, rootState) => (token) => {
-		if (state.typing[token]) {
-			return Object.values(state.typing[token]).filter(id => {
-				return rootState.getSessionId() !== id
-			})
+	externalTypingSignals: (state) => (token) => {
+		if (!state.typing[token]) {
+			return []
```
Comment (ShGKme) [inline src/store/participantsStore.js:92]: Isn't it an object now, not an array?

File: src/store/participantsStore.js [hunk 3]
```diff
@@ -85,16 +85,14 @@ const getters = {
...
 		}
-		return []
+
+		return Object.entries(state.typing[token])
 	},
```
Comment (ShGKme) [inline src/store/participantsStore.js:96]: I'm not sure how we should divide external and internal typings (we do it in the component as well).

but the issue in the previous solution is that `rootState` is the 3rd getter's params, not 2nd.

File: src/store/participantsStore.js [hunk 4]
```diff
@@ -107,19 +105,17 @@ const getters = {
...
-
-			return false
-		})
+		return getters.participantsList(token)
+			// Check if participant's sessionId matches with any of sessionIds from signaling
+			.filter(attendee => {
+				return getters.externalTypingSignals(token).some(([sessionId, _timestamp]) => {
+					return attendee.sessionIds.includes(sessionId)
+				})
+			})
```
Comment (ShGKme) [inline src/store/participantsStore.js:118]:
```suggestion
			.filter(attendee =>
				getters.externalTypingSignals(token).some(([sessionId, _timestamp]) => attendee.sessionIds.includes(sessionId))
			)
```

File: src/components/NewMessage/NewMessage.vue [hunk 5]
```diff
@@ -380,23 +382,46 @@ export default {
...
+
+					// Continuously send signals with 10s interval if still typing
+					this.typingInterval = setInterval(() => {
+						if (this.typingLastActivity - this.typingPrevActivity > 0) {
+							this.$store.dispatch('setTyping', { typing: true })
+							this.typingPrevActivity = new Date().getTime()
+						} else {
+							this.resetTypingIndicator()
+						}
+					}, 10000)
```
Comment (ShGKme) [inline src/components/NewMessage/NewMessage.vue:420]: In which case do we have `this.typingLastActivity - this.typingPrevActivity <= 0`?

**Review by ShGKme — CHANGES_REQUESTED** [review]
I haven't tested yet and haven't checked changes in `webrtc` and tests but there are some blocking comments.

File: src/store/participantsStore.js (hunk 2 above)
Comment (Antreesy) [reply src/store/participantsStore.js:92]: state.typing[token] is object: {
  [key: sessionId] : { expirationTimeout }
}

getter returns an array of other participants sessionIds (or empty array), because we don't need to expose expirationTimeout somewhere

File: src/components/NewMessage/NewMessageTypingIndicator.vue (hunk 1 above)
[the remark this answers is not in the document]
Comment (Antreesy) [reply src/components/NewMessage/NewMessageTypingIndicator.vue:149]: Moved expiration logic to participantsStore. Other comments are based on the new logic

File: src/components/NewMessage/NewMessageTypingIndicator.vue [hunk 6]
```diff
@@ -59,6 +59,12 @@ export default {
 		},
 	},
 
+	data() {
+		return {
+			observationInterval: null,
+		}
+	},
+
```
Comment (ShGKme) [inline src/components/NewMessage/NewMessageTypingIndicator.vue:67]:
```suggestion
```

File: src/store/participantsStore.js [hunk 7]
```diff
@@ -288,20 +284,19 @@ const mutations = {
...
+			clearTimeout(state.typing[token][sessionId].expirationTimeout)
 		}
-		if (!state.typing[token].includes(sessionId)) {
-			state.typing[token].push(sessionId)
+
+		if (typing) {
+			Vue.set(state.typing[token], sessionId, { expirationTimeout })
+		} else {
+			Vue.delete(state.typing[token], sessionId)
 		}
```
Comment (ShGKme) [inline src/store/participantsStore.js:300]: It seems to me, that the problem here was only with `if (!typing)` condition.

The "this.typing" state in signaling is inconsistent with store state. This state should be only in the store state.

File: src/utils/SignalingTypingHandler.js [hunk 8]
```diff
@@ -124,29 +119,16 @@ SignalingTypingHandler.prototype = {
...
-			return
-		}
-
-		for (const participant of participants) {
-			this._signaling.emit('message', {
-				type: 'startedTyping',
-				to: participant.signalingSessionId,
-			})
-		}
-	},
```
Comment (ShGKme) [inline src/utils/SignalingTypingHandler.js:145]: It seems to me, that the problem here was only with `if (!typing)` condition.

The "this.typing" state in signaling is inconsistent with store state. This state should be only in the store state.

File: src/utils/SignalingTypingHandler.spec.js [hunk 9]
```diff
@@ -487,65 +487,6 @@ describe('SignalingTypingHandler', () => {
...
-		signalingTypingHandler._signalingParticipantList._trigger('participantsJoined', [[
-			user1ParticipantInSignalingParticipantList,
-		]])
-
-		expect(store.getters.participantsListTyping('theToken')).toEqual([])
-		expect(signaling.emit).toHaveBeenCalledTimes(2)
-		expect(signaling.emit).toHaveBeenNthCalledWith(1, 'message', { type: 'startedTyping', to: 'guest1SignalingSessionId' })
-		expect(signaling.emit).toHaveBeenNthCalledWith(2, 'message', { type: 'stoppedTyping', to: 'guest1SignalingSessionId' })
-	})
-
```
Comment (ShGKme) [inline src/utils/SignalingTypingHandler.spec.js:548]: Then we also won't need to remove all this functionality

File: src/utils/webrtc/index.js [hunk 10]
```diff
@@ -432,6 +432,9 @@ async function signalingLeaveCall(token, all = false) {
  */
 async function signalingLeaveConversation(token) {
 	if (tokensInSignaling[token]) {
+		// TODO it's not possible at the moment to send a signal
+		// to previously joined conversation (see issue #9615)
+		// signalingSetTyping(false, token)
```
[the remark this answers is not in the document]
Comment (Antreesy) [reply src/utils/webrtc/index.js:437]: Don't need to. Receivers set this locally if sender left the room

File: src/utils/SignalingTypingHandler.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (Antreesy) [reply src/utils/SignalingTypingHandler.js:145]: replace with participantsStore getter

File: src/utils/webrtc/index.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (ShGKme) [reply src/utils/webrtc/index.js:437]: So, as we also resetTypingIndicator on token change, we don't need this todo and this PR also fixes https://github.com/nextcloud/spreed/issues/9615, right?

File: src/store/participantsStore.js [hunk 11]
```diff
@@ -85,16 +85,34 @@ const getters = {
...
+	/**
+	 * Gets the array of external session ids.
+	 *
+	 * @param {object} state - the state object.
+	 * @param {object} getters - the getters object.
+	 * @param {object} rootState - the rootState object.
+	 * @param {object} rootGetters - the rootGetters object.
+	 * @return {Array} the typing session IDs array.
+	 */
+	actorIsTyping: (state, getters, rootState, rootGetters) => () => {
```
Comment (ShGKme) [inline src/store/participantsStore.js:110]: JSDoc is not correct

File: src/store/quoteReplyStore.js [hunk 12]
```diff
@@ -39,9 +39,7 @@ const getters = {
 	},
 
 	currentMessageInput: (state) => (token) => {
-		if (state.currentMessageInput[token]) {
-			return state.currentMessageInput[token]
-		}
+		return state.currentMessageInput[token] ?? ''
 	},
```
Comment (ShGKme) [inline src/store/quoteReplyStore.js:43]: It doesn't break anything, but we should update also `currentMessageInput` usages

**Review by SystemKeeper — APPROVED** [review]
Tested locally and works as described. 
Personally it feels a bit long until the indicator disappears, because when you type 2 characters, we are always sending the second "startedTyping" after 10 seconds.

**Comment by ShGKme** [comment]
> Personally it feels a bit long until the indicator disappears, because when you type 2 characters, we are always sending the second "startedTyping" after 10 seconds.

Yes, but this respects https://github.com/nextcloud/spreed/issues/9624

**Comment by ShGKme** [comment]
For the record: my force push was with dummy commit and its drop.

GitHub had weird behavior, the new Maksim's commits appeared in the branch but not in the PR o_O

**Review by ShGKme — APPROVED** [review]
Thank you for your great work!

**Comment by DorraJaouad** [comment]
I checked the behavior:
When deleting, the typing indicator appears and disappears after a +10s delay. I also think that having a delay of >10s is a bit long. Maybe we should consider reducing it. 

https://github.com/nextcloud/spreed/assets/84044328/2485ceac-3f5d-4bf5-ab70-1b4a0fa5a67b

**Comment by ShGKme** [comment]
> I checked the behavior:
> When deleting, the typing indicator appears and disappears after a +10s delay. I also think that having a delay of >10s is a bit long. Maybe we should consider reducing it.

I think, users usually type for a longer time, so 10-25s doesn't usually looks as long as in this video.

Thought, it would be good if we have some way to change those values: https://github.com/nextcloud/spreed/issues/9717

Adding a small delay may also help with the situation on the video, then a user suddenly typed some symbols for a second: https://github.com/nextcloud/spreed/issues/9718

**Comment by DorraJaouad** [comment]
> > I checked the behavior:
> > When deleting, the typing indicator appears and disappears after a +10s delay. I also think that having a delay of >10s is a bit long. Maybe we should consider reducing it.
> 
> I think, users usually type for a longer time, so 10-25s doesn't usually looks as long as in this video.
> 
> Thought, it would be good if we have some way to change those values: #9717
> 
> Adding a small delay may also help with the situation on the video, then a user suddenly typed some symbols for a second: #9718

What about the typing indicator when the user is deleting the text, is it considered accurate?

**Comment by ShGKme** [comment]
> What about the typing indicator when the user is deleting the text, is it considered accurate?

Yes, erasing a text is also considered as typing
