### PR TITLE
fix(chat): Prevent empty chat messages

### LINKED ISSUE #9507: Empty messages should not be possible to send
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Press spacebar 
3. Press return

### Expected behaviour
Nothing should happen, because the message is empty (after trim).

### Actual behaviour
The message is actually send as an empty message. This happens since switching to `NCRichContentEditable` (I think). Corresponding issue of the vue-lib https://github.com/nextcloud/nextcloud-vue/issues/4068.
Not sure if we should prevent this on frontend or backend.

## Talk app

Master, stable26

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #9507

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
With only new lines the submit button is active | With only new lines the submit button is inactive
Bildschirmfoto vom 2023-05-10 07-17-54 | Bildschirmfoto vom 2023-05-10 07-17-35

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by vitormattos — APPROVED** [review]

File: src/components/NewMessageForm/NewMessageForm.vue [hunk 1]
```diff
@@ -592,7 +592,7 @@ export default {
 				}
 			}
 
-			if (this.text !== '') {
+			if (this.hasText) {
 				// FIXME: remove after issue is resolved: https://github.com/nextcloud/nextcloud-vue/issues/3264
 				const temp = document.createElement('textarea')
 				temp.innerHTML = this.text
```
Comment (Antreesy) [inline src/components/NewMessageForm/NewMessageForm.vue:598]:
```suggestion
				temp.innerHTML = this.text.trim()
```
We trim messages at server, probably, so temporary message could be aligned to it as well

Comment (nickvergessen) [reply src/components/NewMessageForm/NewMessageForm.vue:598]: Fixed

**Review by Antreesy — APPROVED** [review]
