### PR TITLE
Use an OCS controller and long polling instead of event sources

### LINKED ISSUE #225: spreed hangs with http2
## Steps to reproduce
1. click on the spreed tab
2. it loads for ever on firefox an chrome showing spinnig wheel while trying to load Names
3. Clicking on an other Icon p.e. for Notes or Files leeds into spinning thi icon
4. You hafe to close the browser..

### Expected behaviour
Spreed should load as before 1.2

### Actual behaviour
see above

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Win 10 Pro
**Browser name:** Firefox/Chrome/...
firefox and chrome
**Browser version:** 50.1/55/...
newest
### Browser log
jquery-migrate.min.js?v=4d43c3a…:2 JQMIGRATE: Migrate is installed, version 1.4.0
app.js?v=4d43c3a…:356 Starting spreed …
jquery.min.js?v=4d43c3a…:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js?v=4d43c3a…:4
simplewebrtc.js?v=4d43c3a…:13898 CONNECTED
(anonymous) @ simplewebrtc.js?v=4d43c3a…:13898
webrtc.js?v=4d43c3a…:457 local speaking

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
NO
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
stun.nextcloud.com:443
### Server configuration
**Operating system**: Linux OdOc 3.10.96 #1 SMP PREEMPT Mon May 23 01:50:06 BRT 2016 armv7l

**Web server:**  apache2handler

**Database:** mysql

**PHP version:** 7.0.13-0ubuntu0.16.04.1

**Nextcloud version:** 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

	```
	Array	```
</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

	```
	Enabled:
	 - activity: 2.4.1
	 - admin_audit: 1.1.0
	 - announcementcenter: 3.0.0
	 - bookmarks: 0.9.1
	 - calendar: 1.5.0
	 - comments: 1.1.0
	 - contacts: 1.5.2
	 - dav: 1.1.1
	 - direct_menu: 0.10.0
	 - federatedfilesharing: 1.1.1
	 - files: 1.6.1
	 - files_automatedtagging: 1.1.1
	 - files_downloadactivity: 1.0.0
	 - files_pdfviewer: 1.0.1
	 - files_sharing: 1.1.1
	 - files_texteditor: 2.2
	 - files_trashbin: 1.1.0
	 - files_versions: 1.4.0
	 - files_videoplayer: 1.0.0
	 - flowupload: 0.4
	 - html5_videoplayer: 1.0
	 - issuetemplate: 0.0.1
	 - keeweb: 0.3.0
	 - logreader: 2.0.0
	 - lookup_server_connector: 1.0.0
	 - news: 10.1.0
	 - nextcloud_announcements: 1.0
	 - nextnotes: 0.9.1
	 - notes: 2.2.0
	 - notifications: 1.0.1
	 - ocsms: 1.11.4
	 - ownbackup: 16.11.0
	 - password_policy: 1.1.0
	 - provisioning_api: 1.1.0
	 - serverinfo: 1.1.1
	 - sharebymail: 1.0.1
	 - shorten: 0.0.15
	 - spreed: 1.2.0
	 - spreedme: 0.3.6
	 - survey_client: 0.1.5
	 - systemtags: 1.1.3
	 - tasks: 0.9.4
	 - templateeditor: 0.2
	 - theming: 1.1.1
	 - twofactor_backupcodes: 1.0.0
	 - updatenotification: 1.1.1
	 - workflowengine: 1.1.1

	Disabled:
	 - encryption
	 - external
	 - federation
	 - files_accesscontrol
	 - files_external
	 - files_retention
	 - firstrunwizard
	 - flowupload.old
	 - gallery
	 - qownnotesapi
	 - user_external
	 - user_ldap
	 - user_saml
	```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/cloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "integrity.check.disabled": false,
    "dbname": "nextcloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### PR DESCRIPTION
**Pull request by nickvergessen**
Based on:
- [x] #406 
- [x] #405 
- [x] #404 
- [ ] #423 

Fix #225

### CODE REVIEW

File: appinfo/routes.php [hunk 1]
```diff
@@ -29,23 +29,29 @@
...
+			'url' => '/api/{apiVersion}/signalling',
 			'verb' => 'POST',
+			'requirements' => [
+				'apiVersion' => 'v1',
+			],
 		],
 		[
 			'name' => 'Signalling#pullMessages',
-			'url' => '/messages',
+			'url' => '/api/{apiVersion}/messages',
```
Comment (nickvergessen) [inline appinfo/routes.php]: should those both be on signalling? one POST and one GET?

Comment (fancycode) [inline appinfo/routes.php]: Fine with me to have both at the same endpoint / URL.

**Comment by fancycode** [comment]
Probably would be a good idea to merge #351 first as this also changes some JS for the signaling stuff.

**Comment by nickvergessen** [comment]
@fancycode yes already discussed with ivan that we should merge your PR first

File: js/signaling.js [hunk 2]
```diff
@@ -186,9 +201,15 @@
 			return;
 		}
 
-		$.post(OC.generateUrl('/apps/spreed/signalling'), {
-			messages: JSON.stringify(this.spreedArrayConnection)
+		$.ajax({
```
Comment (fancycode) [inline js/signaling.js]: Could you please avoid code duplication (here and `_sendMessageWithCallback`) and move all code that sends messages to the server into one method?

File: js/signaling.js [hunk 3]
```diff
@@ -155,27 +162,35 @@
...
-		}.bind(this));
-		this.source.listen('__internal__', function(data) {
-			if (data === 'close') {
-				console.log('signaling connection closed - will reopen');
-				setTimeout(function() {
-					this._openEventSource();
-				}.bind(this), 0);
-			}
-		}.bind(this));
+		$.ajax({
```
Comment (fancycode) [inline js/signaling.js]: You should also handle errors here and start again if a request failed. Probably should use increasing delays if lots of requests fail in a short time (e.g. if your network connection is interrupted).

File: js/signaling.js [hunk 4]
```diff
@@ -186,9 +201,15 @@
...
+			url: OC.linkToOCS('apps/spreed/api/v1', 2) + 'signalling',
+			type: 'POST',
+			data: {messages: JSON.stringify(this.spreedArrayConnection)},
+			beforeSend: function (request) {
+				request.setRequestHeader('Accept', 'application/json');
+			}
 		});
+
 		this.spreedArrayConnection = [];
```
Comment (fancycode) [inline js/signaling.js]: I know that also was not handled before, but maybe we should only clear the list of pending messages if it could be sent, i.e. if an error occurred it should be retried on the next iteration.

**Comment by nickvergessen** [comment]
@Ivansss whats the status with this?

**Comment by Ivansss** [comment]
@nickvergessen It works and I'm currently using it (rebased with master). 
But maybe we should do more testing regarding performance.

File: js/signaling.js (hunk 3 above)
Comment (nickvergessen) [reply js/signaling.js]: @Ivansss can you fix this?

Comment (Ivansss) [reply js/signaling.js]: Fixed! Retry after 5 seconds if pull messages fails.

**Comment by nickvergessen** [comment]
Should be ready for testing, now without DDOS against the server 💃

**Comment by nickvergessen** [comment]
Based on #423 now the "stuck when user leaves room" should be gone
