### PR TITLE
Fix `Reply` and `Private reply` buttons show conditions

### LINKED ISSUE #8447: Deleting chat messages from a locked conversation fails without any error message
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a talk room
2. write some chat messages
3. Go to the conversation settings and lock the room
4. Go to the conversation settings and try to delete the chat history

### Expected behaviour

Either I can delete the chat message also for a locked conversations or if this shouldn't be the case I see two options:

1. the "delete chat messages" button should be grayed out with a mouse over notification like "this room is locked, unlock the room to delete the chat messages"
2. if the user clicks the button a notification like "this room is locked, unlock the room to delete the chat messages" should pop up.

### Actual behaviour

I can click the "delete chat message" button, confirm the operation but nothing happens. This looks like a broken "delete chat message" operation to the user.

## Talk app

**Talk app version:** 15.0.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** cloud.nextcloud.com (Nextcloud 25.0.2. but can also be reproduced with Nextcloud 24)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
Fix #8447

image
image

### 🚧 TODO

- [ ] Code review
- [ ] Visual check

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue [hunk 1]
```diff
@@ -33,7 +33,8 @@
 					<EmoticonOutline :size="20" />
 				</template>
 			</NcButton>
-			<NcActions v-show="isReplyable">
+			<!-- TODO change with NcButton and adjust tests-->
+			<NcActions v-show="!isConversationReadOnly && isReplyable">
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue:37]: https://github.com/nextcloud/spreed/blob/master/lib/Model/Message.php#L159

hmm should already be the case?

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue [hunk 2]
```diff
@@ -385,8 +386,7 @@ export default {
 		},
 
 		isPrivateReplyable() {
-			return this.isReplyable
```
[the remark this answers is not in the document]
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue:388]: In that case it could be better to not change the behavior, but to refetch messages again
Cause I fixed a button after locking conv., but it still not working after UNlocking

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue:37]: They come from different store, and only one of them changes when toggling lock/unlock.
One more reason to refetch...

File: src/components/MessagesList/MessagesGroup/Message/Message.spec.js [hunk 3]
```diff
@@ -95,7 +95,6 @@ describe('Message.vue', () => {
 			id: 123,
 			isTemporary: false,
 			isFirstMessage: true,
-			isReplyable: true,
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/Message.spec.js:98]: Please keep using this.

**Review by nickvergessen — CHANGES_REQUESTED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
