### PR TITLE
fix(conversation): adjust broadcasted data between tabs

### LINKED ISSUE #12548: Conversation list not updated when not joined a room
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open `/apps/spreed/` in two pages
2. See the conversation list on the left sidebar (from the browser cache)
3. Wait

### Expected behaviour
You should see a request to `ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true` in the second page

### Actual behaviour
No request is ever done

## Talk app

**Talk app version:** 19.0.3 on c.nc.c

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

Fix #12548

- pass `options: { all }` to leader tab, when force refresh;
- do not fetch anything on secondary tabs, pass message to force refresh via broadcast channel;
- do not fetch anything on leaving conversation;
- broadcast federation invites count to secondary tabs;

### 🖼️ Screenshots / Screencasts

🏡 After

[Screencast from 21.06.2024 15:58:27.webm](https://github.com/nextcloud/spreed/assets/93392545/95a7d3e8-26d8-406f-9bce-5b7244f2ab9f)

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/LeftSidebar/LeftSidebar.vue [hunk 1]
```diff
@@ -839,23 +842,22 @@ export default {
...
 
-			this.debounceFetchConversations()
+			if (this.isCurrentTabLeader) {
+				if (options?.all === true) {
+					this.roomListModifiedBefore = 0
+					this.forceFullRoomListRefreshAfterXLoops = 10
+				}
+				this.debounceFetchConversations()
+			} else {
+				talkBroadcastChannel.postMessage({ message: 'force-fetch-all-conversations', options })
```
Comment (DorraJaouad) [inline src/components/LeftSidebar/LeftSidebar.vue:859]: The signaling message is always received by one tab, right ? 
Because otherwise, there is a risk that tabs will resend the channel message multiple times and leader tab will receive all of them.

**Review by DorraJaouad — COMMENTED** [review]
Solution looks good

File: src/components/LeftSidebar/LeftSidebar.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/LeftSidebar/LeftSidebar.vue:859]: Yes, as every tab counts as a different signaling session.
Only the tab that switches to conversation and receives that message from signaling, will post a broadcast message. Every other will receive it, but only leader tab will fetch the changes

**Review by DorraJaouad — APPROVED** [review]
Tested

**Review by danxuliu — CHANGES_REQUESTED** [review]
A `room` signaling message with `roomid: ""` is sent by the signaling server when the current participant leaves a room (as [a response to the message sent by the client](https://github.com/strukturag/nextcloud-spreed-signaling/blob/918b10a7a708c86c632df9c2a30b4e71031bfb56/hub.go#L1486), note that `should-refresh-conversations` is not directly triggered by `_doLeaveRoom` as seems to be implied from the second commit message, it is indirectly triggered). However, that message can be sent by the signaling server too to the active participants of a room [if that room is deleted](https://github.com/strukturag/nextcloud-spreed-signaling/blob/918b10a7a708c86c632df9c2a30b4e71031bfb56/hub.go#L2516).

If the participant is a registered user the client will also receive a [`roomlist` signaling message with `type: "disinvite"`](https://github.com/nextcloud/spreed/blob/e9b9cf49022521291fce0386c78f6df1e70fb731/src/utils/signaling.js#L1458-L1467), which will cause [a redirection to `spreed/not-found`](https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/src/composables/useSessionIssueHandler.js#L56). However, if the particiant is a guest no other signaling message will be received to notify the client about the current room being deleted.

Due to that, if `should-refresh-conversations` is not emitted when a `room` signaling message with `roomid: ""` is sent by the signaling server the UI is not immediately updated for guests when [public conversations](https://github.com/nextcloud/spreed/blob/e9b9cf49022521291fce0386c78f6df1e70fb731/src/App.vue#L268) are deleted (although it will be updated at most [after 30 seconds](https://github.com/nextcloud/spreed/blob/e9b9cf49022521291fce0386c78f6df1e70fb731/src/App.vue#L617-L619), but that smells like legacy code that might be cleaned at some point).

Similarly, if a [video verification conversation](https://github.com/nextcloud/spreed/blob/e9b9cf49022521291fce0386c78f6df1e70fb731/src/PublicShareAuthSidebar.vue#L151) is deleted by the moderator without even joining the conversation the UI for the guest will never reflect that the conversation is deleted. If the moderator joins the conversation and then leaves (which automatically deletes the conversation) it will, but only because when the moderator leaves a `roomlist` message with `type: "update"` will be sent, which will also cause [the conversation to be fetched again](https://github.com/nextcloud/spreed/blob/e9b9cf49022521291fce0386c78f6df1e70fb731/src/PublicShareAuthSidebar.vue#L152) (and as the conversation is automatically deleted it will no longer exist once the request reaches the server, so the UI will be properly updated on the response).

Would it be possible to emit `should-refresh-conversations` even when `roomid: ""` but ignore the event in those places in which an update is not needed in that case? Or maybe emit a different event when `roomid: ""` that could be explicitly listened to if needed?

**Comment by Antreesy** [comment]
Thanks for the review, @danxuliu ! It is indeed more complex problem than it was expected by me 👀

We have 4 emiiters of `emit('should-refresh-conversations'` event in total (all in signaling.js), so I assume we can provide each emit with a meaningful payload to distinct it on frontend.
My suggestion is to handle it separately. I'll drop the blocking commit for now and open an issue
