### PR TITLE
Replace NcMultiselect with NcSelect

### LINKED ISSUE #10087: Strange border around "No camera available" media setting multiselect
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have no camera
2. Create a conversation
3. Start a call

### Expected behaviour

Flawless media selection

### Actual behaviour

Strange border around the disabled camera dropdown:
Bildschirmfoto vom 2023-08-01 16-08-27

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10087 
* Full migration to NcSelect

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🚧 Tasks

- [ ] Code review
- [ ] Visual review

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue [hunk 1]
```diff
@@ -36,22 +36,19 @@
...
 					<Plus class="icon" :size="20" />
-					<NcMultiselect ref="partNcMultiselect"
-						v-model="selectedType"
+					<NcSelect v-model="selectedType"
 						label="displayName"
-						track-by="type"
 						:placeholder="newPartPlaceholder"
 						:options="formatedTypes"
-						:user-select="true"
 						:internal-search="true"
```
Comment (Antreesy) [inline src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue:43]:
```suggestion
```

`searchable` now, which is true by default

File: src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue [hunk 2]
```diff
@@ -724,6 +721,8 @@ export default {
 		.enable-switch-line {
 			display: flex;
 			height: 44px;
+			margin-top: 5px;
+			padding-left: 10px;
```
Comment (Antreesy) [inline src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue:725]:
```suggestion
```
Switch won't be aligned with other switches in this modal

File: src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue:43]: Apart from that, everything is fine, component is working, though it's intended to clear itself after picking

**Review by Antreesy — CHANGES_REQUESTED** [review]
2/4 are working good, ExpirationSettings require a fix, and FlowPost.. should work, judging by the code

**Review by Antreesy — APPROVED** [review]
