### PR TITLE
Change display_name size

### LINKED ISSUE #7071: display_name field of attendees table is too short
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a User LDAP setup with 255 chars
2. Add them to a talk room
3. Error because the name does not fit into the 64 chars display name column

### PR DESCRIPTION
**Pull request by vitormattos**
close #7071

### CODE REVIEW

File: lib/Migration/Version14000Date20220328153054.php [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
+		/** @var ISchemaWrapper */
+		$schema = $schemaClosure();
+
+		$table = $schema->getTable('talk_attendees');
+		$displayName = $table->getColumn('display_name');
+		if ($displayName->getLength() === 64) {
```
Comment (nickvergessen) [inline lib/Migration/Version14000Date20220328153054.php:47]:
```suggestion
		if ($displayName->getLength() !== 255) {
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Missing version change in appinfo/info.xml

**Review by nickvergessen — APPROVED** [review]
