### PR TITLE
Fix(MessageForwarder + NewGroupConversation) - The confirmation page enhancement

### LINKED ISSUE #10630: follow-up(Forwarder) - minor enhancements:
follow-up from #10603:
- rename component to MessageForwarder
- fix `<div class="forwarder">` style, as it's breaking MessageButtonBar appearance
- get rid of doubled usage of NcEmptyContent (was added here: 45cb031bb619fc0b935694bd7a4bf16889f1eafd)
- check how openConversation method closes modal
- rework code, rename and cleanup methods and computed props
- make backportable changes

See screenshot attached:
image

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/pull/10603#discussion_r1345428202_

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10630

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image |image|
| image | image|
| image | image|
|image | image|

### 🚧 Tasks

- [x] Component renaming ( MessageForwarder)
- [x] Fixing the UI ( NcEmptyContent duplication and the buttons bar )
- [x] Replacing the new conversation page confirmation with NcEmptyContent
- [x] Show loading status before the confirmation page.

To do:
- [ ] Visual review
- [ ] Code review

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 1]
```diff
@@ -145,23 +114,58 @@
...
+
+		<!-- Third page : this is the confirmation page-->
+		<NcModal v-else-if="page === 2"
+			:container="container"
+			@close="closeModal">
+			<NcEmptyContent>
+				<template #icon>
+					<Check v-if="!error && success && isPublic" :size="64" />
+					<div v-if="isLoading && !error && !success" class="icon-loading spinner" />
+					<AlertCircle v-if="error" :size="64" />
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:128]:
```suggestion
					<LoadingComponent v-if="isLoading" />
					<AlertCircle v-else-if="error" :size="64" />
					<Check v-else-if="success && isPublic" :size="64" />
```
If you're going to change it, handleCreateConversation() method is missing final this.isLoading = false

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 2]
```diff
@@ -145,23 +114,58 @@
...
+				</template>
+
+				<template #description>
+					<p v-if="isLoading && !error && !success" class="confirmation__warning">
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:132]: Same v-if/v-else-if as with icons, to avoid accidental render of two icons/messages

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 3]
```diff
@@ -171,6 +175,7 @@ import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
 
 import ConversationAvatarEditor from '../../ConversationSettings/ConversationAvatarEditor.vue'
 import ListableSettings from '../../ConversationSettings/ListableSettings.vue'
+import NcEmptyContent from '@nextcloud/vue/dist/Components/NcEmptyContent.js'
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:178]: import/order is disabled atm, please do it yourself :smiling_face_with_tear:

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 4]
```diff
@@ -263,6 +271,9 @@ export default {
 		selectedParticipants() {
 			return this.$store.getters.selectedParticipants
 		},
+		getSize() {
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:274]: Not used, I suppose?

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 5]
```diff
@@ -527,12 +538,13 @@ export default {
 		margin-left: auto;
 	}
 }
-
-:deep(.modal-wrapper .modal-container) {
+.conversation-form{
+	:deep(.modal-wrapper .modal-container) {
```
Comment (Antreesy) [inline src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:542]:
```suggestion
.conversation-form :deep(.modal-wrapper .modal-container) {
```

**Review by Antreesy — COMMENTED** [review]
Left some comments for improvement

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 6]
```diff
@@ -22,9 +22,9 @@
 <template>
 	<div class="wrapper">
 		<!-- New group form -->
-		<NcModal v-if="modal"
+		<NcModal v-if="modal && page !== 2"
+			class="conversation-form"
 			:container="container"
-			size="normal"
```
[the remark this answers is not in the document]
Comment (Antreesy) [reply src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:27]: It's a default size value for NcModal, so could be safely omitted, and probably not related to your case

File: src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue [hunk 7]
```diff
@@ -145,23 +114,58 @@
...
+					</p>
+					<p v-if="error" class="confirmation__warning">
+						{{ t('spreed', 'Error while creating the conversation') }}
+					</p>
+				</template>
+
+				<template #action>
+					<NcButton v-if="error || isPublic"
+						ref="closeButton"
+						type="primary"
```
[the remark this answers is not in the document]
Comment (DorraJaouad) [reply src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:146]: I chose them differently because : 
- `primary` : because it will change the route and redirect you to another conversation : seems like a big action , no ? 
- `tertiary `: because it will only copy a link to clipboard.

[the remark this answers is not in the document]
Comment (Antreesy) [reply src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:146]: No, I meant "Close" button =)

Secondary for "Copy link" seems fine, as well as primary for "Go to conversation"

[the remark this answers is not in the document]
Comment (DorraJaouad) [reply src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue:146]: aaa oops, I misread which button you are referring to .

**Review by Antreesy — APPROVED** [review]
Looks nice, thanks for handling!
