### PR TITLE
Extend the signaling setting API to allow somewhat clustering

### LINKED ISSUE #2591: Switching to another conversation is sluggish
## Steps to reproduce
1. Click on any conversation

### Expected behaviour
A UI and route change is triggered immediately, regardless of the requests that are being made under the hood.

### Actual behaviour
There's a pretty significant lag between the click and anything happening

### LINKED ISSUE #3463: As guest or un-invited user, the room load all the messages
## Steps to reproduce
1. Join a room as guest or as a logeed user not part of a public room
2. See 30s of loading of all messages
3. Log in as a user belonging to a room
4. See the last 10 messages being loaded ONLY

### Expected behaviour
Same as logged participants, should only load the last xx, not the full list

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Improve "random empty default picking"
- [x] Add token when requesting signaling information
- [x] Make sure the UI uses the correct signaling server per conversation

Fix #2591
Fix #3463

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should be functional now.

We still pick a random one for the first participant, but that is hard to make right without a real usecase in hand. But adjusting that should be rather easy in the end, so testing it for now should be fine.

Most effects should be noticable without the clustering.
But real clustering is skipped unless there is more then one signaling server defined and the config is set. Can be hacked in Config.php by adding `return self::SIGNALING_CLUSTER_CONVERSATION;` in `getSignalingMode()`.

By replacing: `currentSignalingServer = settings.url` with `currentSignalingServer = settings.url + 'different'` iin `src/utils/webrtc/index.js` you can also fake a different signalign server being used all the time, making you close and open the connection on every conversation change.

**Comment by nickvergessen** [comment]
Would be nice if you can have a quick look and spill your opinion @danxuliu

**Comment by nickvergessen** [comment]
Added a commit to check the config.php for a hardcoded list to allow overwriting the random for some known big conversations which can then be assigned specifically to always end up on the set machines

File: lib/TInitialState.php [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+		// Needed to enable the screensharing extension in Chromium < 72.
+		Util::addHeader('meta', ['id' => 'app', 'class' => 'nc-enable-screensharing-extension']);
+
+		$this->initialStateService->provideInitialState(
+			'talk', 'prefer_h264',
+			$this->serverConfig->getAppValue('spreed', 'prefer_h264', 'no') === 'yes'
+		);
+
+		$signalingMode = $this->talkConfig->getSignalingMode();
+		if ($signalingMode !== 'internal' && !$this->memcacheFactory->isAvailable()) {
```
Comment (danxuliu) [inline lib/TInitialState.php:58]: Is a distributed cache always needed for external signaling, or only for clustered external signaling?

In any case, I think this is too agressive. If an admin sets two external signaling servers and then happily navigates away from the settings to the Files app the admin will be greeted with that message. But then it will not be possible to open again the settings (at least, without using the direct URL) as trying to open the root Nextcloud URL will redirect to the Files app and the message will be shown again.

On the other hand, if setting several external signaling servers were prevented in the settings if a distributed cache is not set that would work when setting the servers, but if the distributed cache is then removed... That would be a problem. I am not sure how to handle that. So... I guess that the `HintException` is OKish :shrug: Yes, I am thinking out loud :-P

Comment (nickvergessen) [reply lib/TInitialState.php]: > Is a distributed cache always needed for external signaling, or only for clustered external signaling?

So it's not needed for the normal external signaling, but I wouldn't run a Nextcloud without it anyway if I need the HPB. But I added an appconfig now `signaling_dev` to not overwrite the signaling mode and not require the memcache

File: lib/Signaling/Manager.php [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+
+	public function getSignalingServerConversationCluster(Room $room): array {
+		$serverId = $room->getAssignedSignalingServer();
+		$servers = $this->talkConfig->getSignalingServers();
+
+		if ($serverId !== null && isset($servers[$serverId])) {
+			return $servers[$serverId];
+		}
+
+		$serverIdToAssign = random_int(0, count($servers) - 1);
```
Comment (danxuliu) [inline lib/Signaling/Manager.php:89]: Missing try/catch.

File: lib/TInitialState.php [hunk 3]
```diff
@@ -50,6 +54,15 @@ protected function publishInitialStateShared(): void {
 			$this->serverConfig->getAppValue('spreed', 'prefer_h264', 'no') === 'yes'
 		);
 
+		$signalingMode = $this->talkConfig->getSignalingMode();
+		if ($signalingMode !== 'internal'
```
Comment (danxuliu) [inline lib/TInitialState.php:58]: Use `Config::SIGNALING_INTERNAL` instead.

File: lib/Signaling/Manager.php (hunk 2 above)
Comment (nickvergessen) [reply lib/Signaling/Manager.php:89]: Well yes, but actually if random_int fails with the HPB you have a sever problem anyway

**Comment by nickvergessen** [comment]
> * Guests do not work (missing session ID from Make the signaling based on conversations)

Fixed

> * Forced reconnections do not work, at least with guests (it should not reload the page)

And fixed

> * Calls do not work in clustering mode (as they are initialized just once with the signaling server being used at that time and not changed later even if a different signaling connection/object is used)

I'm not sure what that is supposed to mean, care to explain?

**Comment by nickvergessen** [comment]
Okay figured it, I had to actually join the calls.
Also fixed now.

And I will rebase once more due to #3495

**Comment by danxuliu** [comment]
`webRtc.disconnect()` is not async, so it was not needed to use `await`. Besides that, `SimpleWebRTC.connection` is the signaling object, so calling `webRtc.disconnect()` and then `signaling.disconnect()` was redundant. However, although it should not be needed due to how the variables at the top of _webrtc.js_ are used, I modified `SimpleWebRTC.disconnect` to emit and event and reset those variables instead when disconnecting the SimpleWebRTC object.

**Comment by nickvergessen** [comment]
> Independently of all that, when a participant leaves a call the participant is not removed from the call view of the rest of participants, but that is not related to this pull request.

That is only the last participant btw.

**Comment by nickvergessen** [comment]
Ran unit tests locally, they pass and random integration tests also still worked, so merging

**Comment by morph027** [comment]
Jumping in here...Running latest version of NC and Talk (19 + 9) and Redis but i can't find a possibilty to add more than one signaling server in talk settings. Do i miss something?

**Comment by nickvergessen** [comment]
The HPB can handle a few hundred users by default without any bigger problems. If you need the clustering you should get in contact with our sales team for a Nextcloud Talk Enterprise Subscription:

https://nextcloud.com/talk#pricing

**Comment by morph027** [comment]
Ah, well, not really necessary, just stumbled upon this in the release notes and wanted to try to satisfy my curiosity and improve knowledge about everything ;)
