### PR TITLE
fix(call): temporary disable a call button if ended by moderator

### LINKED ISSUE #8148: Disable "Start call button" when moderator ends a meeting
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a company call
2. Moderator ends the call for everyone
3. Person trying to click the button right before still clicks and restarts the call

### Expected behaviour
☮️

### Actual behaviour
📲

### Possible solution

Temporarily disable the "Start call" button for some seconds after a meeting was ended by a moderator.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #8148
* DIsable CallButton for `10` seconds, when `call_ended_everyone` system message is received
	* Longer time picked for longer disconnection period

### 🖼️ Screenshots / Screencasts

| 🏡 After
| --
| image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [x] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/store/messagesStore.js [hunk 1]
```diff
@@ -1180,6 +1180,9 @@ const actions = {
 						lastActivity: message.timestamp,
 					})
 				}
+				if (message.systemMessage === 'call_ended_everyone') {
+					context.dispatch('setCallHasJustEnded')
```
Comment (nickvergessen) [inline src/store/messagesStore.js:1184]: Just to be save, this is only when pulling new messages? And when they are timely near? So not preventing a call when coming back from vacation and scrolling to the end?😅

Comment (Antreesy) [reply src/store/messagesStore.js:1184]: Need to be thoroughly checked now

Comment (DorraJaouad) [reply src/store/messagesStore.js:1184]: Let's check if current timestamp is within 10 sec after `message.systemMessage` timestamp, we set the flag and timeout duration is `(system message timestamp + 10) - current timestamp` to be precise :p

Comment (Antreesy) [reply src/store/messagesStore.js]: Takes effect only from messages newer than known lastMessageId, so coming back from vacation shouldn't be a problem

**Comment by Antreesy** [comment]
- add a watcher to reset flag on conversation switch
- add a timediff calculation (proof from old messages as well)

File: src/components/TopBar/CallButton.vue [hunk 2]
```diff
@@ -352,6 +357,12 @@ export default {
 		},
 	},
 
+	watch: {
+		token() {
+			this.$store.dispatch('resetCallHasJustEnded')
+		}
```
Comment (DorraJaouad) [inline src/components/TopBar/CallButton.vue:363]: User can just go to another conversation and come back to start a call :p 
Breaking the flag by token in store should solve this

File: src/components/TopBar/CallButton.vue [hunk 3]
```diff
@@ -253,6 +253,7 @@ export default {
 
 		startCallButtonDisabled() {
 			return this.disabled
+				|| this.$store.getters.callHasJustEnded
```
Comment (DorraJaouad) [inline src/components/TopBar/CallButton.vue:256]: I think it should be disabled to everyone except the actor (in case they closed by accident or there was an error)

File: src/store/callViewStore.js [hunk 4]
```diff
@@ -240,6 +245,23 @@ const actions = {
 	isEmptyCallView(context, value) {
 		context.commit('isEmptyCallView', value)
 	},
+
+	setCallHasJustEnded(context, timestamp) {
+		// Check the time difference between the current time and the call end time
+		// If lesser than 10 seconds, disable the callButton for that amount of time
```
Comment (DorraJaouad) [inline src/store/callViewStore.js:251]:
```suggestion
		// If it is less than 10 seconds, disable the callButton for the remaining amount of time until 10 sec after call end time
```

File: src/components/TopBar/CallButton.vue (hunk 2 above)
Comment (Antreesy) [reply src/components/TopBar/CallButton.vue:363]: I don't think that's a problem, as a goal is to prevent accidental click. If user switch back and forth, he probably knows what he's doing

Comment (nickvergessen) [reply src/components/TopBar/CallButton.vue:363]: I wouldn't really care about that. I think the biggest usecase of the whole thing is that people don't accidentally restart a call by clicking the "Start call" button which just now replaced "Leave call", when a moderator already made them leave by using "End call for everyone".
So changing the room back and forth is totally fine to call again.

**Review by DorraJaouad — APPROVED** [review]
Tested, good to go

File: src/store/messagesStore.js [hunk 5]
```diff
@@ -1180,6 +1180,11 @@ const actions = {
 						lastActivity: message.timestamp,
 					})
 				}
+				if (message.systemMessage === 'call_ended_everyone'
+					&& !(message.actorId === context.getters.getActorId()
+					&& message.actorType === context.getters.getActorType())) {
```
Comment (nickvergessen) [inline src/store/messagesStore.js:1185]:
```suggestion
						&& message.actorType === context.getters.getActorType())) {
```

**Review by DorraJaouad — APPROVED** [review]
New changes 👍🏻 
Tested
