### PR TITLE
fix(outOfOffice): show expand button during call

### LINKED ISSUE #14457: can not expand out-of-office notice
Hi all

I just noticed that I can't expand the out-of-office notice on the desktop client, the arrow at the top right is missing:

Desktop Client

Image

Web:

Image

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #14457

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/NewMessage/NewMessageAbsenceInfo.vue [hunk 1]
```diff
@@ -128,6 +132,14 @@ export default {
...
 			})
 		},
+
+		isVisible(value) {
+			if (value) {
+				this.$nextTick(() => {
+					this.setIsTextMoreThanOneLine()
+				})
+			}
+		},
```
Comment (ShGKme) [inline src/components/NewMessage/NewMessageAbsenceInfo.vue:142]: If I understand it correctly, the same problem happens if a user resizes the window...
So that the source of the problem is changed width, not visibility.

Comment (DorraJaouad) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:142]: hmmm you are not wrong

File: src/components/ChatView.vue [hunk 2]
```diff
@@ -107,7 +109,8 @@ export default {
 		},
 	},
 
-	setup() {
+	setup(props) {
+		provide('isVisible', computed(() => props.isVisible))
```
[the remark this answers is not in the document]
Comment (DorraJaouad) [reply src/components/ChatView.vue]: Noted for future use ;)

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
A complex solution - render it twise - once hidden for scrollHeight check and once for the user

File: src/components/NewMessage/NewMessageAbsenceInfo.vue [hunk 3]
```diff
@@ -122,16 +123,16 @@ export default {
...
 	mounted() {
 		this.setIsTextMoreThanOneLine()
+		this.resizeObserver = new ResizeObserver(this.setIsTextMoreThanOneLine)
+		this.resizeObserver.observe(this.$refs.absenceMessage)
+	},
+
+	beforeDestroy() {
+		if (this.resizeObserver) {
+			this.resizeObserver.disconnect()
+		}
```
Comment (Antreesy) [inline src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: you don't have conditions for starting observer, so no need to check when destroying?
```suggestion
		this.resizeObserver.disconnect()
```

File: src/components/NewMessage/NewMessageAbsenceInfo.vue [hunk 4]
```diff
@@ -122,16 +123,16 @@ export default {
 		},
 	},
 
-	watch: {
-		userAbsenceMessage() {
-			this.$nextTick(() => {
-				this.setIsTextMoreThanOneLine()
```
Comment (Antreesy) [inline src/components/NewMessage/NewMessageAbsenceInfo.vue:128]: When switching between two one-to-ones conversations, component is not unmounted, only updated:
- `resize` event is triggered, because `userAbsenceMessage` is changed and therefore a width of DOM element might have changed. 
- if same person has changed absense message in the meantime fo something longer, value of this computed will change, but not the element. Then you will miss the button again.

Let's keep the watcher?
Should width be always 100%, maybe, to cause less resize emits?

File: src/components/NewMessage/NewMessageAbsenceInfo.vue (hunk 3 above)
Comment (ShGKme) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: Or use `useResizeObserver` from vueuse :D

File: src/components/NewMessage/NewMessageAbsenceInfo.vue (hunk 4 above)
Comment (DorraJaouad) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:128]: > if same person has changed absense message in the meantime fo something longer, value of this computed will change, but not the element. Then you will miss the button again.

this will trigger the resize event

File: src/components/NewMessage/NewMessageAbsenceInfo.vue (hunk 3 above)
Comment (Antreesy) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: It's not used anywhere in project yet.. but we can keep it in mind for ts migration in each case

File: src/components/NewMessage/NewMessageAbsenceInfo.vue (hunk 4 above)
Comment (Antreesy) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:128]: Ok, can't reproduce it anymore

**Review by Antreesy — APPROVED** [review]

File: src/components/NewMessage/NewMessageAbsenceInfo.vue (hunk 3 above)
Comment (ShGKme) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: TS?

Comment (Antreesy) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: I meant `script setup` 👀. But we do it together usually

Comment (ShGKme) [reply src/components/NewMessage/NewMessageAbsenceInfo.vue:135]: We can use composables in Options API, even mixing with properties from Options API.
