### PR TITLE
fix(chat): show spinner for temporary / edited messages

### LINKED ISSUE #12454: It is unclear when voice message is sent or not - quiting the page leads to lost voice message
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. record a 2 minute voice message
2. attach a message
3. hit send

image

4. after a while (~1min), you see the circle filling with blue
image

5. after another while (~2min) the upload is complete and the display change
image

### Expected behaviour
The voice message should be sent with the description and something should REALLY indicate that the voice message is uploading. e.g. a spinning wheel, incrementing dots...

### Actual behaviour
The voice message is displayed in the chat area, but the icon next to it is idle for the first one minute or so :/ so I though message had been sent and quit the page :/

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #12454
  * Reserve space for time element for all processed messages:
    * file uploads
    * edited messages
    * new messages
  * Show spinner for:
    * file uploads
    * edited messages

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
image | image

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 1]
```diff
@@ -401,7 +409,13 @@ export default {
...
 				showError(t('spreed', 'Could not update the message'))
 			}
-		}
+		},
+
+		setIsEditing({ messageId, value }) {
+			if (messageId === this.message.id) {
+				this.isEditing = value
+			}
+		},
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:418]: Maybe use store  to store the id that is being processed instead and put computed in this component here ?

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:418]: There could be several 'processing' messages at the time, so store soultion could get complicated. I think, it's easier to send a signal twice.

Comment (DorraJaouad) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:418]: fiine

**Review by DorraJaouad — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
We didn't do this to make it more obvious that the messages was not sent (yet).

So blocking for design feedback

**Review by marcoambrosini — COMMENTED** [review]
I find it problematic because the actual date of the messages come from the server (once it's actually uploaded), so we would have to update it afterwards? 
I think that the biggest problem is that we upload huge wav files when recording audio (mea culpa), but back then I didn't find a better format/codec that was "open source enough"

**Comment by Antreesy** [comment]
> find it problematic because the actual date of the messages come from the server (once it's actually uploaded), so we would have to update it afterwards?

I don't see the areas it would be critical, if visible date (in most cases time) will change affter finishing the upload. Not a problem for:

Telegram | WhatsApp | Discord
-- | -- | --
image | image | image

It's not only about voicce messages, rather than all file uplaods and freshly posted / edited messages.
Though if we won't come to an agreement upon a date showing, at least spinner should be there, what do you all think?

**Comment by Antreesy** [comment]
Dropped showing a date for temporary messages, but reserve a place for it (otherwise message width might jump)

File: src/store/messagesStore.js [hunk 2]
```diff
@@ -651,10 +652,12 @@ const actions = {
 				updatedMessage,
 			})
 			context.dispatch('processMessage', { token, message: response.data.ocs.data })
+			EventBus.emit('editing-message-processing', { messageId, value: false })
 		} catch (error) {
 			console.error(error)
 			// Restore the previous message state
 			context.commit('addMessage', { token, message })
+			EventBus.emit('editing-message-processing', { messageId, value: false })
```
Comment (DorraJaouad) [inline src/store/messagesStore.js:660]: ` finally {...}`

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 3]
```diff
@@ -66,7 +66,7 @@
 
 		<!-- Additional message info-->
 		<div v-if="!isDeletedMessage" class="message-main__info">
-			<span v-if="!hideDate" class="date" :title="messageDate">{{ messageTime }}</span>
+			<span :class="['date', { 'date--hidden': hideDate }]" :title="messageDate">{{ messageTime }}</span>
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:69]:
```suggestion
			<span :class="['date', { 'hidden-visually': hideDate }]" :title="messageDate">{{ messageTime }}</span>
```

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue [hunk 4]
```diff
@@ -481,8 +483,15 @@ export default {
...
-			margin-right: var(--default-clickable-area);
+		.date {
+			&--hidden {
+				pointer-events: none;
+				opacity: 0;
+			}
+
+			&:last-child {
+				margin-right: var(--default-clickable-area);
+			}
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:494]: There is only one date for each message?

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:494]: We reserve a place for read marker
But that's up to different discussion

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue (hunk 3 above)
Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue:69]: What would kick element out of render flow. I keep it like this specifically to reserve a certain amount of space for the date

File: src/store/messagesStore.js (hunk 2 above)
Comment (Antreesy) [reply src/store/messagesStore.js:660]: error thrown in catch block doesn't allow to do that

**Review by DorraJaouad — APPROVED** [review]
All good
