### PR TITLE
fix(UI): Only show breakout rooms option when it's usable

### LINKED ISSUE #8865: Breakout room option is shown for public conversations
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

1. Should either show a dedicated error that public rooms are currently not supported, or
2. Hide the option

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #8865 

### 🖼️ Screenshots

Type | 🏚️ Before | 🏡 After
---|---|---
Public | Bildschirmfoto vom 2023-02-27 15-57-28| Bildschirmfoto vom 2023-02-27 15-55-55
1-1 | Bildschirmfoto vom 2023-02-27 15-57-24 | Bildschirmfoto vom 2023-02-27 15-55-59
Group | Bildschirmfoto vom 2023-02-27 15-57-18| Bildschirmfoto vom 2023-02-27 15-56-05

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/components/TopBar/TopBarMenu.vue [hunk 1]
```diff
@@ -367,6 +368,13 @@ export default {
 			return this.canFullModerate && recordingEnabled
 		},
 
+		canConfigureBreakoutRooms() {
+			const breakoutRoomsEnabled = getCapabilities()?.spreed?.config?.call?.['breakout-rooms'] || false
+			return this.canFullModerate
+				&& breakoutRoomsEnabled
+				&& this.conversation.type === CONVERSATION.TYPE.GROUP
+		},
```
Comment (Antreesy) [inline src/components/TopBar/TopBarMenu.vue:376]:
```suggestion
		canConfigureBreakoutRooms() {
		  if (!this.conversation.type === CONVERSATION.TYPE.GROUP || !this.canFullModerate) {
		    return false
		  }
		  
			const breakoutRoomsEnabled = getCapabilities()?.spreed?.config?.call?.['breakout-rooms']
			return !!breakoutRoomsEnabled
		},
```

I'd prefer mentioned above order of checks, to reduce number of requests

Comment (nickvergessen) [reply src/components/TopBar/TopBarMenu.vue:376]: > to reduce number of requests

`getCapabilities` is not doing a request but reading from a local variable of the lib, but fine by me either way

**Review by Antreesy — APPROVED** [review]

**Comment by nickvergessen** [comment]
### CI replacement

Compiling | Lint | Tests
---|---|---
grafik | grafik | grafik
