### PR TITLE
Fix messagebuttonsbar position for last read messages

### LINKED ISSUE #7219: Reactions bubble should overlay the unread messages horrizontal line
## Steps to reproduce
1. Open a conversation with unread messages
2. Hover over the message just above the unread messages indicator line
3. Watch the reactions bubble. It's *under* the unread messages indicator line

### Screenshot

talk-unread-reactions

### Expected behaviour
I guess it would look cleaner if the reactions bubble would overlay the unread messages indicator line.

## Talk app

cloud.nc.c instance

## Browser

**Operating system:** Linux

**Browser name:** Firefox

**Browser version:** 99

### PR DESCRIPTION
**Pull request by marcoambrosini**
If the MessageButtonsBar belongs to the last read message, we need
to raise it to compensate for the shift in position brought by the
last read marker that's added to the message component.

fixes #7219 

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue [hunk 1]
```diff
@@ -22,7 +22,8 @@
 <template>
 	<!-- Message Actions -->
 	<div v-click-outside="handleClickOutside"
-		class="message-buttons-bar">
+		class="message-buttons-bar"
+		:class="{ 'message-buttons-bar--last' : isLastRead }">
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue]:
```suggestion
		:class="{ 'message-buttons-bar--last-read' : isLastRead }">
```

Just to avoid confusion with it being the last message, CSS block also needs adjusting

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue [hunk 2]
```diff
@@ -489,10 +500,15 @@ export default {
...
 	border-radius: calc($clickable-area / 2);
 	box-shadow: 0 0 4px 0 var(--color-box-shadow);
+	height: 44px;
 
 	& h6 {
 		margin-left: auto;
 	}
+
+	&--last {
+		bottom: 36px;
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue:510]: This feels very weird if for one message the buttons are at another position. Can't we instead add more offset or something?

I replaced it therefor with 36px from bottom and now it looks/overlaps like with any other message
Bildschirmfoto vom 2022-08-02 15-48-20

**Review by nickvergessen — APPROVED** [review]
