### PR TITLE
Stop refreshing participant list when a guest is chatting

### LINKED ISSUE #865: Chatting as guest calls "GuestManager::updateName" for every message
## Steps to reproduce
1. Connect as guest user to a room.
2. Send chat messages.

### Expected behaviour
The name of the user should not be updated if it didn't change.

### Actual behaviour
`GuestController::updateName` is called for every message:
https://github.com/nextcloud/spreed/blob/4c9d7e749c375bdca56b4aef4fc0bd4299497e9e/lib/Controller/ChatController.php#L191
This should either only be done if the name has changed, or `updateName` should detect the same name internally and perform a no-op in such cases.

Updating the name causes unnecessary database updates and unnecessarily reloads of the participant list by all clients.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #865

### CODE REVIEW

File: lib/GuestManager.php [hunk 1]
```diff
@@ -48,23 +49,55 @@ public function __construct(IDBConnection $connection, EventDispatcherInterface
...
-			'display_name' => $displayName,
-		], ['session_hash']);
-
-		if ($result === 0) {
-			$query = $this->connection->getQueryBuilder();
-			$query->update('talk_guests')
-				->set('display_name', $query->createNamedParameter($displayName))
-				->where($query->expr()->eq('session_hash', $query->createNamedParameter($sessionHash)));
-			$query->execute();
+		$dispatchEvent = true;
```
Comment (fancycode) [inline lib/GuestManager.php]: This is never set to `false`.

File: lib/GuestManager.php [hunk 2]
```diff
@@ -48,23 +49,55 @@ public function __construct(IDBConnection $connection, EventDispatcherInterface
...
+			if ($oldName !== $displayName) {
+				$query = $this->connection->getQueryBuilder();
+				$query->update('talk_guests')
+					->set('display_name', $query->createNamedParameter($displayName))
+					->where($query->expr()->eq('session_hash', $query->createNamedParameter($sessionHash)));
+				$query->execute();
+				$dispatchEvent = true;
+			}
+		} catch (ParticipantNotFoundException $e) {
+			$this->connection->insertIfNotExist('*PREFIX*talk_guests', [
```
Comment (fancycode) [inline lib/GuestManager.php]: IMHO inserting an initial name should also dispatch an event.

File: lib/GuestManager.php [hunk 3]
```diff
@@ -48,23 +49,55 @@ public function __construct(IDBConnection $connection, EventDispatcherInterface
...
-			$query = $this->connection->getQueryBuilder();
-			$query->update('talk_guests')
-				->set('display_name', $query->createNamedParameter($displayName))
-				->where($query->expr()->eq('session_hash', $query->createNamedParameter($sessionHash)));
-			$query->execute();
+		$dispatchEvent = true;
+
+		try {
+			$oldName = $this->getNameBySessionHash($sessionHash);
+			$dispatchEvent = $oldName !== $displayName;
```
Comment (fancycode) [inline lib/GuestManager.php]: Better, though I would rather write it like this to save the redundant comparison:
```php
if ($oldName !== $displayName) {
   ...
} else {
    $dispatchEvent = false;
}
```

But that's just my personal taste :wink:
