### PR TITLE
Fix(ParticipantsStore): Purge the store so it deletes the removed conversation

### LINKED ISSUE #11101: Quirks joining an open conversation
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Search for an open group conversation
2. Join it

### Expected behaviour

See participants

### Actual behaviour

See myself twice (once as guest) and nobody else. The list never finishes loading:

Bildschirmfoto vom 2023-12-04 09-25-18
Bildschirmfoto vom 2023-12-04 09-24-57
image

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** 28.0.0 RC2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #11101

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image    | image     |

### 🚧 Tasks

- [ ] Code review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by Antreesy** [comment]
Half of the problem solved =)

If open conversation was cached, then you left and reload a page, BrowserStorage still keeps it for you, and on reload populates participantsStore again.

File: src/store/participantsStore.js [hunk 1]
```diff
@@ -860,6 +860,8 @@ const actions = {
 		await removeCurrentUserFromConversation(token)
 		// If successful, deletes the conversation from the store
 		await context.dispatch('deleteConversation', token)
+		context.dispatch('purgeParticipantsStore', token)
+		context.dispatch('cacheConversations')
```
Comment (Antreesy) [inline src/store/participantsStore.js:864]: This action `removeCurrentUserFromConversation` is being called only when you leave the covnersation (either from settings or LeftSidebar)

Action `'deleteConversation'`, in opposite, is called, when we:
- leaving conversation
- deleting conversation
- handling error with joining

So, my opinion, should belong there, in conversationsStore

**Review by Antreesy — APPROVED** [review]
Tested when leaving conversation, deleting self, and deleted by moderator. Purged and cached correctly
