### PR TITLE
[stable17] Do not load Talk sidebar in public share page of folder shares

### LINKED ISSUE #2282: Breadcrumb menu is misaligned on share links
### Steps to reproduce
1. Upgrade to NC 17.0
2. Share a link to a folder
3. Observe breadcrumb menu

### Expected behaviour
Menu should be aligned to top, not overlaying header from files app. Grid view toggle should also be aligned to breadcrumb and scroll.

### Actual behaviour

This is a regression from 16.0.4.

### Server configuration

**Operating system**: Debian stretch
**Web server:** Apache 2.4
**Database:** MariaDB 
**PHP version:** 7.2
**Nextcloud version:** 17.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 16.0.4
**Where did you install Nextcloud from:** Tarball
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.7.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.4
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - music: 0.10.1
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - richdocuments: 3.4.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.1.1
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "config_is_read_only": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "loglevel": 2,
        "appstoreenabled": true,
        "mail_smtpmode": "smtp",
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": false,
        "assetdirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "preview_max_filesize_image": 50,
        "preview_max_x": 16384,
        "preview_max_y": 16384,
        "simpleSignUpLink.shown": false,
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FF 69
**Operating system:** Ubuntu

### Logs
n/a

### LINKED ISSUE #2293: NC 17 Not all files are shown on public shared folders when Talk is activated
<p>Share a public folder with 24+ files when Talk is activated. Only 23 Files/folders are shown. Deactivate Talk and all files are shown...</p>
<h3>Expected behaviour</h3>
<p>All files and folders should be shown for the public user.</p>
<h3>Actual behaviour</h3>
<p>Only 23 Files / Folders are shown<br>
In the Browserconsole:<br>
/ocs/v2.php/apps/spreed/api/v1/publicshare/2jHAL9bHZypxAgP:1 Failed to load resource: the server responded with a status of 404 (Not Found)<br>
/apps/files_sharing/publicpreview/2jHAL9bHZypxAgP?fileId=4745956&amp;file=%2F2.md&amp;c=f2d51b9f2cbf86b3a96048ad7e8efdd8&amp;x=326&amp;y=326:1 Failed to load resource: the server responded with a status of 404 (Not Found)<br>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/5583290/66564061-70e53200-eb5f-11e9-9707-482007b887bb.png">grafik</a></p>
<h2>Server configuration detail</h2>
<p><strong>Operating system:</strong> Linux 4.15.0-64-generic <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="159976462" data-permission-text="Issue title is private" data-url="https://github.com/nextcloud/server/issues/73" data-hovercard-type="issue" data-hovercard-url="/nextcloud/server/issues/73/hovercard" href="https://github.com/nextcloud/server/issues/73">#73</a>-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64</p>
<p><strong>Webserver:</strong> Apache/2.4.29 (Ubuntu) (apache2handler)</p>
<p><strong>Database:</strong> mysql 10.2.16</p>
<p><strong>PHP version:</strong></p>
<p>7.2.19-0ubuntu0.18.04.2<br>
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache</p>
<p><strong>Nextcloud version:</strong> 17.0.0 - 17.0.0.9</p>
<p><strong>Updated from an older Nextcloud</strong></p>
<p><strong>Nextcloud VM</strong></p>
<details><summary>Signing status</summary>
<p>Array<br>
(<br>
)</p>
</details>
<details><summary>List of activated apps</summary>
<pre><code>Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.8.0
 - audioplayer: 2.8.4
 - bookmarks: 2.2.0
 - calendar: 1.7.1
 - carnet: 0.18.4
 - cloud_federation_api: 1.0.0
 - cms_pico: 0.9.8
 - comments: 1.7.0
 - contacts: 3.1.6
 - data_request: 1.4.0
 - dav: 1.13.0
 - deck: 0.7.0
 - drop_account: 0.1.0
 - event_update_notification: 1.0.0
 - external: 3.4.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_downloadactivity: 1.6.0
 - files_fulltextsearch_tesseract: 1.3.1
 - files_linkeditor: 1.0.10
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.6.0
 - files_readmemd: 1.1.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trackdownloads: 1.6.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - gallery: 18.4.0
 - impersonate: 1.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - music: 0.10.1
 - news: 14.0.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.0.3
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - ocsms: 2.1.3
 - ownbackup: 19.9.0
 - password_policy: 1.7.0
 - piwik: 0.5.3
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - quickaccesssorting: 1.0.2
 - quota_warning: 1.6.0
 - recommendations: 0.5.0
 - richdocuments: 3.4.2
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.2
 - spreed: 7.0.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - telephoneprovider: 1.0.2
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - uploaddetails: 0.1.2
 - user_external: 0.7.0
 - user_usage_report: 1.1.2
 - viewer: 1.1.0
 - w2g2: 3.0.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard
 - ransomware_detection
 - socialsharing_email
 - suspicious_login
 - user_ldap

</code></pre>
</details>
<details><summary>Configuration (config/config.php)</summary>
<pre><code>{
    "loglevel": 2,
    "maintenance": false,
    "theme": "",
    "integrity.check.disabled": false,
    "overwrite.cli.url": "https:\/\/of99.net\/",
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "simpleSignUpLink.shown": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "log_rotate_size": "10485760",
    "activity_expire_days": 33,
    "trusted_domains": [
        "localhost",
        "192.168.1.234",
        "***REMOVED SENSITIVE VALUE***.net",
        "of***REMOVED SENSITIVE VALUE***t"
    ],
    "htaccess.RewriteBase": "\/",
    "trashbin_retention_obligation": "auto, 10",
    "versions_retention_obligation": "auto, 21",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": 500,
    "preview_max_y": 500,
    "preview_max_scale_factor": 10,
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "tasks",
        "w2g2",
        "apporder",
        "piwik",
        "ownbackup",
        "radio",
        "carnet",
        "theming",
        "workin2gether",
        "files_linkeditor",
        "socialsharing_email",
        "files_readmemd",
        "spreed",
        "telephoneprovider",
        "drop_account",
        "issuetemplate",
        "polls",
        "ocsms",
        "quickaccesssorting",
        "cms_pico",
        "ransomware_detection"
    ],
    "has_rebuilt_cache": true
}
</code></pre>
</details>
<p><strong>Are you using external storage, if yes which one:</strong> no</p>
<p><strong>Are you using encryption:</strong> no</p>
<p><strong>Are you using an external user-backend, if yes which one:</strong> no</p>
<h2>Client configuration</h2>
<p><strong>Browser:</strong> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36</p>
<p><strong>Operating system:</strong></p>
<h2>Logs</h2>
<details><summary>Nextcloud log</summary>
<pre><code>Nothing related
</code></pre>
</details>
<details><summary>Browser log</summary>
<p>Insert your browser log here, this could for example include:</p>
<pre><code>a) The javascript console log
</code></pre>
<p>JQMIGRATE: Migrate is installed, version 1.4.1<br>
2globals.js:26 oc_requesttoken is deprecated: use OC.requestToken instead<br>
je @ globals.js:26<br>
38globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.<br>
je @ globals.js:26<br>
24globals.js:26 The humanFileSize library is deprecated! It will be removed in nextcloud 19.<br>
je @ globals.js:26<br>
/ocs/v2.php/apps/spreed/api/v1/publicshare/2jHAL9bHZypxAgP:1 Failed to load resource: the server responded with a status of 404 (Not Found)<br>
/apps/files_sharing/publicpreview/2jHAL9bHZypxAgP?fileId=4745956&amp;file=%2F2.md&amp;c=f2d51b9f2cbf86b3a96048ad7e8efdd8&amp;x=326&amp;y=326:1 Failed to load resource: the server responded with a status of 404 (Not Found)</p>

### PR DESCRIPTION
**Pull request by danxuliu**
Backport of #2339 

Requires nextcloud/server#17597

Fixes #2282 
Fixes #2293

Note that the `Files_Sharing::loadAdditionalScripts` event only includes the share since Nextcloud 17.0.1, so it is needed to handle the event without parameters to keep compatibility with Nextcloud 17.0.0 (in that case the Talk sidebar will still be loaded for folder shares).

### CODE REVIEW

File: lib/PublicShare/TemplateLoader.php [hunk 1]
```diff
@@ -48,8 +57,14 @@ public static function register(EventDispatcherInterface $dispatcher): void {
 	 *
 	 * This method should be called when loading additional scripts for the
 	 * public share page of the server.
+	 *
+	 * @param IShare $share
 	 */
-	public static function loadTalkSidebarUi() {
+	public static function loadTalkSidebarUi(?IShare $share) {
+		if ($share && $share->getNodeType() !== FileInfo::TYPE_FILE) {
```
Comment (nickvergessen) [inline lib/PublicShare/TemplateLoader.php]: Would it make sense to switch to "hide by default".
This way we can help people to update their Nextcloud, as well as not allow to load the app on folders while the owner can not load the conversation in his file list?
```suggestion
		if (!$share || $share->getNodeType() !== FileInfo::TYPE_FILE) {
```

Comment (danxuliu) [reply lib/PublicShare/TemplateLoader.php]: The Talk sidebar was loaded on folders, but it was not shown, so that was not a problem. Anyway, if you want to _help_ people to update their Nextcloud, fine by me.

**Comment by nickvergessen** [comment]
> Conflicting files
lib/PublicShare/TemplateLoader.php

**Comment by danxuliu** [comment]
Rebased due to conflicts with #2342.

**Comment by FrankMaute** [comment]
Well, we use talk everyday. Please list it as a bug in order to get it solved. It was not addressed in RC1 of 17 which is a bit annoying.

**Comment by nickvergessen** [comment]
Hi @FrankMaute It is not fixed in RC1, because Talk is not bundled with the server package.
But we will release a new version for Talk as well this week which should then come with this fix.

**Comment by FrankMaute** [comment]
Sounds really great. Thanks for the support.
