### PR TITLE
fix(MessagesList): fix fetching messages completion when there is no …

### LINKED ISSUE #13820: Chat UI can "hang" when the chat is completely empty
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create conversation
2. Enable expiration
3. Clear chat history
4. Wait until expiration time is over (or delete directly in the database)

### Expected behaviour
Chat shows that it is empty

### Actual behaviour
Image

## Talk app

**Talk app version:** main

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #13820 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
chat-before | chat-after

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesList.vue [hunk 1]
```diff
@@ -670,9 +670,10 @@ export default {
 						}
 						this.$store.dispatch('setFirstKnownMessageId', { token, id: startingMessageId })
 						this.$store.dispatch('setLastKnownMessageId', { token, id: startingMessageId })
-
+						// If -2, it means it's the beginning of the chat, so we need to get the context 
+						// using 0
 						// Get chat messages before last read message and after it
-						await this.getMessageContext(token, startingMessageId)
+						await this.getMessageContext(token, startingMessageId !== -2 ? startingMessageId : 0)
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:676]: https://github.com/nextcloud/spreed/blob/3071d4dab62ebc974b296197bc68e84a0ed5100f/src/store/messagesStore.js#L982

should respect -2

File: src/components/MessagesList/MessagesList.vue [hunk 2]
```diff
@@ -670,9 +670,10 @@ export default {
 						}
 						this.$store.dispatch('setFirstKnownMessageId', { token, id: startingMessageId })
 						this.$store.dispatch('setLastKnownMessageId', { token, id: startingMessageId })
-
+						// If MESSAGE.CHAT_BEGIN_ID we need to get the context
+						// using 0 as the API does not support '-' character
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesList.vue:674]:
```suggestion
						// If MESSAGE.CHAT_BEGIN_ID we need to get the context from the beginning
						// using 0 as the API does not support negative values
```

File: src/constants.js [hunk 3]
```diff
@@ -129,6 +129,10 @@ export const ATTENDEE = {
 	CHANGELOG_BOT_ID: 'changelog',
 }
 
+export const MESSAGE = {
+	CHAT_BEGIN_ID: -2,
```
Comment (Antreesy) [inline src/constants.js:133]:
```suggestion
	CHAT_BEGIN_ID: -2,
	CHAT_MIGRATION_ID: -1,
```

File: src/store/messagesStore.js [hunk 4]
```diff
@@ -12,6 +12,7 @@ import {
 	ATTENDEE,
 	CHAT,
 	CONVERSATION,
+	MESSAGE
```
Comment (Antreesy) [inline src/store/messagesStore.js:15]:
```suggestion
	MESSAGE,
```

File: src/store/messagesStore.js [hunk 5]
```diff
@@ -979,11 +980,15 @@ const actions = {
...
+		if (!context.getters.getFirstKnownMessageId(token) || oldestKnownMessageId < context.getters.getFirstKnownMessageId(token)
+			|| context.getters.getFirstKnownMessageId(token) === MESSAGE.CHAT_BEGIN_ID) {
 			context.dispatch('setFirstKnownMessageId', {
 				token,
 				id: oldestKnownMessageId,
 			})
+			if (context.getters.getVisualLastReadMessageId(token) === MESSAGE.CHAT_BEGIN_ID) {
+				context.dispatch('setVisualLastReadMessageId', { token, id: oldestKnownMessageId })
+			}
 		}
```
Comment (Antreesy) [inline src/store/messagesStore.js:992]: Could be done before cycle and checked once: oldestKnownMessageId should be positive
```suggestion
		if (context.getters.getVisualLastReadMessageId(token) === MESSAGE.CHAT_BEGIN_ID) {
			do both
		}
```

File: src/store/messagesStore.js [hunk 6]
```diff
@@ -967,7 +968,7 @@ const actions = {
 			}
 			context.dispatch('processMessage', { token, message })
 			newestKnownMessageId = Math.max(newestKnownMessageId, message.id)
-			oldestKnownMessageId = Math.min(oldestKnownMessageId, message.id)
+			oldestKnownMessageId = oldestKnownMessageId === 0 ? message.id : Math.min(oldestKnownMessageId, message.id)
```
Comment (Antreesy) [inline src/store/messagesStore.js:971]: `Math.min(0, message.id) === message.id`

**Review by Antreesy — APPROVED** [review]
