### PR TITLE
Show "Guest" instead of session hash for guests

### LINKED ISSUE #5109: Guests without displayname show actor ID in call view
## Steps to reproduce
1. Have a call
2. Join as a guest without setting a name ever
3. Others see you as `123456ACTOR_ID1243456` in the call view

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5109 

The idea of this was to show the email address of invited SIP users, but in case of normal guests it's a bigger harm, so for now let's not do this.
In the future we might instead save the email address also as a display name for SIP invites.

### CODE REVIEW

File: src/components/CallView/shared/Video.vue [hunk 1]
```diff
@@ -279,6 +279,9 @@ export default {
 
 			if (!participantName) {
 				participantName = this.peerData.displayName
+				if (!participantName && this.peerData.actorType === 'guests') {
```
Comment (PVince81) [inline src/components/CallView/shared/Video.vue:282]: :bulb: Did you know: there is now a new constant `ATTENDEE.ACTOR_TYPE.GUESTS`

**Review by PVince81 — APPROVED** [review]
:+1: looks fine. Tested, works.

Seems sharing integration tests have failed

**Comment by PVince81** [comment]
rebase needed to make tests pass

**Comment by nickvergessen** [comment]
Yeah, also a potential rebase after #5119 (CallController touches two lines apart) so will wait until that one is merged
