### PR TITLE
Fix flow and chat permissions

### LINKED ISSUE #7476: Flow should not write messages when the user has no chat permission
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Configure a flow with a room where you are not the owner
2. As the owner remove chat permission for the user or make the room read only

### Expected behaviour
Flow does not post anymore

### Actual behaviour
From reading the code the flow would still post, e.g. allowing pupils to spam a class room

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7476

### CODE REVIEW

File: lib/Flow/Operation.php [hunk 1]
```diff
@@ -116,7 +117,17 @@ public function onEvent(string $eventName, Event $event, IRuleMatcher $ruleMatch
 				}
 
 				$room = $this->getRoom($token, $uid);
+				if (!($room->getReadOnly() !== Room::READ_WRITE)) {
```
Comment (come-nc) [inline lib/Flow/Operation.php:120]:
```suggestion
				if ($room->getReadOnly() === Room::READ_WRITE) {
```

**Review by come-nc — CHANGES_REQUESTED** [review]

File: lib/Flow/Operation.php (hunk 1 above)
Comment (nickvergessen) [reply lib/Flow/Operation.php]: yeah, it was a bug before. Didn't mean to invert it. read-write is okay, read-only is what we want to filter out.

**Review by AndyScherzinger — APPROVED** [review]
🐘

**Review by come-nc — APPROVED** [review]
