### PR TITLE
Remove poll data when deleting the message

### LINKED ISSUE #8342: do not show results of deleted polls
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a poll in talk
2. End the poll ==> Results-button is shown in chat
3. delete the message that had the poll in it

### Expected behaviour
Poll and results get deleted.

### Actual behaviour
poll is deleted
results-button is still shown.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #8342 

### 🚧 Todo list

- [x] Remove all data
- [x] Make sure the "Create" message is neutralized
- [x] Make sure the "Close" message is neutralized
- [x] UI "Show result" button on deleted polls is not removed and title of the poll is still leaked in the "result message"

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Chat/ChatManager.php [hunk 1]
```diff
@@ -357,6 +358,60 @@ public function unshareFileOnMessageDelete(Room $room, Participant $participant,
...
+			foreach ($closingMessages as $closingMessage) {
+				$this->deleteMessage($room, $closingMessage, $participant, $deletionTime);
+			}
+		}
+
+		if (!$participant->hasModeratorPermissions(false)
+			&& !($attendee->getActorType() === $poll->getActorType()
+				&& $attendee->getActorId() === $poll->getActorId())) {
+			// Only moderators or the poll creator can delete it
+			return;
```
Comment (vitormattos) [inline lib/Chat/ChatManager.php:409]:
```suggestion
		if (!$participant->hasModeratorPermissions(false)) {
			$attendee = $participant->getAttendee();
			if (!($attendee->getActorType() === $poll->getActorType()
				&& $attendee->getActorId() === $poll->getActorId())) {
				// Only moderators or the poll creator can delete it
				return;
			}
```
