### PR TITLE
fix(federation): Sync room properties on join

### LINKED ISSUE #13045: Recording consent not offered by the frontend if local server doesn't have it
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have ServerA host a federated call
2. On ServerA enable Recording consent as "optional"
3. In RoomA enforce Recording consent
4. As userB from ServerB that does not have recording backend and therefore neither recording consent
5. Join the CallA

### Expected behaviour
Positive experience:
- Message about recording consent missing
- Optional to set the recording consent

### Actual behaviour
"Leave page" warning

### LINKED ISSUE #13060: Initial state of federated room may not match the current state of the remote room
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Once a participant has been invited the federated server [will receive the relevant updates about the room state from the host server](https://github.com/nextcloud/spreed/blob/6c5f9a9991434cc440e118fe8144d23e6fdce5cb/lib/Federation/CloudFederationProviderTalk.php#L310-L333). However, when the federated room is created its initial state only reflects [the current name and type](https://github.com/nextcloud/spreed/blob/b2d9bf1fa9c11fd57da9ea874f2653085862f948/lib/Federation/FederationManager.php#L90). The room avatar will be correctly shown as well even if not set, as [it is proxied from the host server](https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Controller/AvatarController.php#L135-L139) (so it could be removed from the notified changes?).

## How to reproduce (scenario 1)

- Setup Nextcloud server A and B and enable Talk federation
- In server A, create a conversation
- Set the description
- Add a federated user
- In a tab or private window, log in server B
- Accept the invitation
- Join the conversation

### Expected result

The description of the federated conversation matches the host conversation

### Actual result

The description of the federated conversation does not match the host conversation

## How to reproduce (scenario 2)

- Setup Nextcloud server A and B and enable Talk federation
- In server A, create a conversation
- Set the conversation as read-only
- Add a federated user
- In a tab or private window, log in server B
- Accept the invitation
- Join the conversation

### Expected result

The federated conversation is read-only

### Actual result

The federated conversation is not read-only

## How to reproduce (scenario 3)

- Setup Nextcloud server A and B and enable Talk federation
- In server A, create a conversation
- Enable the lobby
- Add a federated user
- In a tab or private window, log in server B
- Accept the invitation
- Join the conversation

### Expected result

The lobby is shown to the federated user

### Actual result

The lobby is not shown to the federated user, but the user can not join the conversation

## How to reproduce (scenario 4)

- Setup Nextcloud server A and B and enable Talk federation
- In server A, create a conversation
- Start a call
- Add a federated user
- In a tab or private window, log in server B
- Accept the invitation
- Join the conversation

### Expected result

The federated user sees that a call is in progress

### Actual result

The federated user sees "Start call" instead of "Join call"

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #13045
* Fix #13060
* Ref #12953 (fixes room permissions, but individual participant permissions still need manual syncing like attempted in #12979 )

### Follow-up ideas
- Track a "property-version" so that recipients know if the just now received data is newer or older https://github.com/nextcloud/spreed/issues/13079
- Always send the full room object when the room was modified, so the sync can heal other properties as well https://github.com/nextcloud/spreed/issues/13079

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: lib/Service/RoomService.php [hunk 1]
```diff
@@ -993,6 +999,127 @@ public function setLastActivity(Room $room, \DateTime $now): void {
...
+				// Add a fake suffix as we explode by the dot in the AvatarService, but the version doesn't have one.
+				$hostAvatar .= '.fed';
+			}
+			if ($hostAvatar !== $local->getAvatar()) {
+				$local->setAvatar($hostAvatar);
+				$update->set('avatar', $update->createNamedParameter($hostAvatar));
+				$changed[] = ARoomModifiedEvent::PROPERTY_AVATAR;
+			}
+		}
+		if (isset($host['lastActivity']) && $host['lastActivity'] !== ((int) $local->getLobbyTimer(false)?->getTimestamp())) {
```
Comment (danxuliu) [inline lib/Service/RoomService.php:1049]: `$local->getLobbyTimer(false)?->getTimestamp()`-> `$local->getLastActivity()`?

File: lib/Service/RoomService.php [hunk 2]
```diff
@@ -993,6 +999,127 @@ public function setLastActivity(Room $room, \DateTime $now): void {
...
+			$lastActivity = $host['lastActivity'] === 0 ? null : $this->timeFactory->getDateTime('@' . $host['lastActivity']);
+			$local->setLobbyTimer($lastActivity);
```
Comment (danxuliu) [inline lib/Service/RoomService.php:1051]: `$local->setLobbyTimer($lastActivity);` -> `$local->setLastActivity($lastActivity);`?

**Review by danxuliu — COMMENTED** [review]
I am not fully convinced on adding a specific method to update the database in a single query. While saving database queries is of course good, not many queries might be saved with that, so the standard `RoomService` methods could be used instead. In [the initial sync](https://github.com/nextcloud/spreed/issues/13060) it may help, but after that it would only help if [some cloud notification is missed](https://github.com/nextcloud/spreed/issues/13079), as right now it syncs more properties than [what is explicitly propagated](https://github.com/nextcloud/spreed/blob/83ad733fd9461c628d3c55a8e21d8acbf63fde64/lib/Federation/CloudFederationProviderTalk.php#L316-L340) (for example, the call recording state), but those missing properties should be propagated anyway; otherwise a federated user already in the room would not receive the change until another federated user joins again.

Syncing all the properties in one go in general seems to have the same effect as using the standard `RoomService` methods, but not sending the individual modification events could also miss some behaviours (like [invalidating the reference cache](https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Collaboration/Reference/ReferenceInvalidationListener.php#L33)), and there could be also missing behaviours on some specific methods (like [resetting the participant permissions when the room permissions are modified](https://github.com/nextcloud/spreed/blob/1779aeeb31d202b3936b6b637f49d083dfbede3c/lib/Service/RoomService.php#L207-L208)). So I am not sure if the few saved database queries are worth the trouble of handling those things :thinking:

Independently of that, CI does not seem to be happy.

**Comment by nickvergessen** [comment]
> I am not fully convinced on adding a specific method to update the database in a single query.

my main intention was to avoid certain reactions of other components listening to the hooks
e.g. I don't know what happens if clients receive 10 room-modified signaling messages in few milliseconds and some of them with potential wrong/old data on other props
but I will just add a "before" event and make that one disable the normal RoomModified listener for signaling. Other listeners can decide themselves whether they should "pause" and conclude with a summary.
Should work just as fine

**Comment by nickvergessen** [comment]
Most of red CI is due to https://github.com/nextcloud/server/pull/46991

**Comment by nickvergessen** [comment]
Changed it to the RoomService methods now, made the SignalingListener pause on BeforeRoomSync and send a single signaling messages afterwards.
Some other listeners were modified to not trigger on federated conversations (we don't need to check/stop a recording, etc.)

**Comment by nickvergessen** [comment]
- Just for the record, permissions are not handled in this PR, I will do that in https://github.com/nextcloud/spreed/pull/12979 after rebasing it on this one

File: lib/Service/RoomService.php [hunk 3]
```diff
@@ -993,6 +1003,154 @@ public function setLastActivity(Room $room, \DateTime $now): void {
...
+			$hostTimer = $host['lobbyTimer'] === 0 ? null : $this->timeFactory->getDateTime('@' . $host['lobbyTimer']);
+			$success = $this->setLobby($local, $host['lobbyState'], $hostTimer);
+			if (!$success) {
+				$this->logger->error('An error occurred while trying to sync lobby of ' . $local->getId() . ' to ' . $host['lobbyState'] . ' with timer to ' . $host['lobbyTimer']);
+			} else {
+				$changed[] = ARoomModifiedEvent::PROPERTY_LOBBY;
+			}
+		}
+		if (isset($host['callStartTime'], $host['callFlag'])) {
+			if ($host['callStartTime'] === 0 || $host['callFlag'] === Participant::FLAG_DISCONNECTED) {
```
Comment (danxuliu) [inline lib/Service/RoomService.php:1093]: The `callFlag` and `callStartTime` are always set when joining the conversation even if there was no call before, as the current value is not taken into account, only if the values are provided in the data, which always are.

But this may be a bit tricky to properly update, it seems that when joining again `$local->getCallFlag` is always disconnected :thinking:

**Review by danxuliu — APPROVED** [review]
Force pushed to fix the [check against the last activity](https://github.com/nextcloud/spreed/pull/13072/commits/ceb41f6cad04ce611df8f28d42994617a84fb259#diff-4aead6c21ae2c0406fa5152f0e22c47036cf0e7a2d23c88ef25d65bda4d829e1R1072).

I have also added a fixup, but not applied it yet, to update the lobby. Before only the lobby state was checked, but not the timer. Therefore, if the lobby was previously set but only the timer changed when the data was synchronized again it was not updated. But given that there was a condition inside the external if that took into account the timer maybe I am missing something, so I prefered not to apply it without a review from @nickvergessen 

Other than that and the comment, tested and works :+1:

File: lib/Service/RoomService.php (hunk 3 above)
Comment (nickvergessen) [reply lib/Service/RoomService.php]: I think my brain had too much boolean logic... Fixed now
