### PR TITLE
fix(Dashboard): adjust list height

### LINKED ISSUE #15856: Home page unread chats not using full space in box
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. open home page

### Expected behaviour
The list with unread chats spans over the full height of the box.

### Actual behaviour

Image

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Linux Mint

**Browser name:** Zen (based on Firefox)

**Browser version:** 1.14.10b (Firefox 141.0.2) (64-Bit)

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #15856

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/Dashboard/TalkDashboard.vue [hunk 1]
```diff
@@ -524,7 +524,7 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
 	flex-grow: 1;
 
 	&> div {
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:526]: _Nit:_ should be `& > div` with whitespace, weird that stylelint doesn't pick it up

File: src/components/Dashboard/TalkDashboard.vue [hunk 2]
```diff
@@ -524,7 +524,7 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
-		max-height: 360px;
+		max-height: 320px;
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:527]: Personally not sure about this one. It's not showing exactly 5 items, I think we're tend to go with 4.5 or 5.5, if there is a scrolling needed

**Review by Antreesy — APPROVED** [review]
Otherwise fine

File: src/components/Dashboard/TalkDashboard.vue (hunk 2 above)
Comment (DorraJaouad) [reply src/components/Dashboard/TalkDashboard.vue:527]: But that way, it will exceed max height of wrapper, this the max height where other items in dashbaord are at their min
