### PR TITLE
Change to border in focus

### LINKED ISSUE #10443: Conversation item border is cut of when tabbing
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Click into the search and tab into the conversation list

### Expected behaviour
Border around the conversation

### Actual behaviour
is cut off:
grafik

## Talk app

**Talk app version:**stable27

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10443

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🚧 Tasks

- [ ] visual review
- [ ] code review

### CODE REVIEW

File: src/components/LeftSidebar/ConversationsList/Conversation.vue [hunk 1]
```diff
@@ -447,6 +447,13 @@ export default {
 .conversation-item {
 	padding-left: 2px;
 	padding-right: 2px;
+
+	:deep(.list-item:focus, .list-item:focus-visible) {
+	z-index: 1;
+	border: 2px solid var(--color-primary-element);
+	padding : 6px;
+	outline: none; // remove the default outline
+	}
```
Comment (ShGKme) [inline src/components/LeftSidebar/ConversationsList/Conversation.vue:456]: > Stylelint: Expected indentation of 2 tabs (indentation)

```suggestion
	:deep(.list-item:focus, .list-item:focus-visible) {
		z-index: 1;
		border: 2px solid var(--color-primary-element);
		padding : 6px;
		outline: none; // remove the default outline
	}
```

**Review by ShGKme — CHANGES_REQUESTED** [review]
Moving styles to `Conversation.vue` breaks some items, because, unfortunately, we use just `NcListItem` sometimes.

Either all styles should be kept in `LeftSidebar` or all `NcListItem`s should be replace with `Conversation.vue`.

bug
