### PR TITLE
Fix hover effects for buttons in TopBar

### LINKED ISSUE #8766: Leave call button menu is not red on hover/click anymore
> > Don't we want to apply a red color to this button?
> 
> Be my guest, it's a regression from
> https://github.com/nextcloud/spreed/blob/4e82455f49bbd7a772d3e9f37a1172d26fadbe39/src/components/TopBar/TopBar.vue#L407-L413

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/8763#issuecomment-1434422079_

### PR DESCRIPTION
**Pull request by Antreesy**
Fix #8766 

### 🚧 TODO

- [X] Move `BreakoutRoomsEditor` to parent component to get rid of `Fragment` in TopBarMenu
- [ ] Code review

### 🏁 Checklist

- [X] 📘 API documentation in `docs/` has been updated or is not required
- [X] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [X] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/components/TopBar/TopBarMenu.vue [hunk 1]
```diff
@@ -251,10 +239,11 @@ export default {
 		},
 	},
 
+	emits: ['open'],
+
```
Comment (ShGKme) [inline src/components/TopBar/TopBarMenu.vue:243]: In my opinion, the name `open` of `TopBarMenu` doesn't describe what exactly happened, what was supposed to open (or was opened) in the menu with many actions. I'd name it `open-breakout-rooms-editor` or `edit-breakout-rooms`.

**Review by ShGKme — CHANGES_REQUESTED** [review]
Works:






But I'd rename `open` event of `TopBarMenu`. Everything else looks good to me.

**Review by ShGKme — APPROVED** [review]
Thanks 🌞
