### PR TITLE
Fix dark/light theme in `LoadingPlaceholder` and refactor dark theme detection

### LINKED ISSUE #9720: The loading animation should not be as dark. Please use a brighter color for it.
As discussed with @jancborchardt and @nimishavijay, the loading animation should not be as dark. Please use a brighter color for it.

See the following screenshot:
image

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix #9720
* Fix https://github.com/nextcloud/talk-desktop/issues/45

### 🖼️ Screenshots

🏚️ Before LoadingPlaceholder | 🏡 After LoadingPlaceholder
---|---
Default on 🌑 Dark system |
image | image
🌑 Dark theme with 🌑 Dark system |
image | image
🌕 Light theme with 🌑 Dark system |
image | image 
Default on 🌕 Light system  |
image | image
🌕 Light theme with 🌕 Light system |
image | image
🌑 Dark theme with 🌕 Light system |
image | image

### Fix dark/light theme in `LoadingPlaceholder`

In Nextcloud we have CSS variables for themes:
1. `:root` - default values based on system `preferred-color-scheme`
2. On `<body>` - set by current theme if not "System default theme" is used in settings. These styles override defaults.

The `LoadingPlaceholder` used variables from `documentElement` (`:root`) instead of `body`. It caused a problem when the system-preferred theme was not equal to the selected in Nextcloud settings.

- [x] Use styles from `body` instead of `documentElement` in `LoadingPlaceholder`
- [x] Move styles getting from instance's `mounted` to component's ES module
  - Render the component right away with the styles instead of useless re-render after mount.
  - Do not get the value from DOM API for each instance, get only once.

### Refactor dark theme detection

- [x] Add `isDarkTheme` util

In some components, we checked if a dark theme is enabled by this line:
```js
const isDarkTheme = window.getComputedStyle(document.body)
  .getPropertyValue('--background-invert-if-dark') === 'invert(100%)'
```

Problems:
- Duplication
- It is evaluated for each instance again using DOM API to get the same value

New `isDarkTheme` util checks if the dark theme is enabled only once and then exports the result.

It assumes that the dark/light theme is not been changing without page reload. But this case didn't fully work early anyway...

No changes after the refactoring

image | image
---|---

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

File: src/utils/isDarkTheme.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ * Check if dark theme is used
+ *
+ * @return {boolean}
+ */
+function checkIfDarkTheme() {
+	// Nextcloud uses --background-invert-if-dark for dark theme filters in CSS
+	// Values:
+	// - 'invert(100%)' for dark theme
+	// - 'no' for light theme
+	return window.getComputedStyle(document.body).getPropertyValue('--background-invert-if-dark') === 'invert(100%)'
```
Comment (szaimen) [inline src/utils/isDarkTheme.js:32]: @skjnldsv isnt there a better way to get the setting in the frontend?

**Comment by szaimen** [comment]
> @szaimen Do you think, we should backport it to 27?

If this is only happening since 27 I would say yes since it is a bug :)

**Comment by ShGKme** [comment]
> If this is only happening since 27 I would say yes since it is a bug :)

No, it is an old bug

**Comment by szaimen** [comment]
> > If this is only happening since 27 I would say yes since it is a bug :)
> 
> No, it is an old bug

Then I'd say definitely backport to 27 and maybe even further?

**Review by szaimen — COMMENTED** [review]
✅ LGTM from the screenshots. Thanks for tackling this! :)

File: src/utils/isDarkTheme.js (hunk 1 above)
Comment (ShGKme) [reply src/utils/isDarkTheme.js:32]: In theory, we can use data theme(s) attributes, but I'm not sure, if it works with custom themes from appstore

Comment (skjnldsv) [reply src/utils/isDarkTheme.js:32]: No idea tbh :/
We should most likely provide an official way for this

Ideally it's
1. has the user picked a custom theme
2. is the system asking for dark mode

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue [hunk 2]
```diff
@@ -96,12 +98,8 @@ export default {
 			return this.isGroupMention
 				&& loadState('spreed', 'user_group_ids', []).includes(this.id)
 		},
-		isDarkTheme() {
-			return window.getComputedStyle(document.body)
-				.getPropertyValue('--background-invert-if-dark') === 'invert(100%)'
-		},
 		avatarUrl() {
-			return generateOcsUrl('apps/spreed/api/v1/room/{token}/avatar' + (this.darkTheme ? '/dark' : ''), {
+			return generateOcsUrl('apps/spreed/api/v1/room/{token}/avatar' + (isDarkTheme ? '/dark' : ''), {
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue:102]: Fixed this file for chat mentions:
image

Because of the wrong naming, it wasn't working before, so not your fault to miss it =)

**Review by Antreesy — APPROVED** [review]
Everything else os working good, thanks for handling this!
Tested on Ubuntu + Chrome for all 6 variations

File: src/utils/isDarkTheme.js (hunk 1 above)
Comment (szaimen) [reply src/utils/isDarkTheme.js:32]: That sounds good!

**Comment by Antreesy** [comment]
FYI: removed label as non-blocking for 27 release
