### PR TITLE
fix: manage existing breakout rooms from conversation settings

### LINKED ISSUE #16726: Add additional breakout rooms
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. In a conversation click on the button [...] Conversation action
2. Click on _"Setup a breakout rooms"_
3. Create one breakout room by clicking on the _"Create rooms"_ button
4. Click once again on the button [...] Conversation action
5. Click on _"Conversation settings"_
6. Click on _"Breakout rooms"_ section
7. Click on _"Setup breakout rooms for this conversation"_
8. Sometimes the _"Configure breakout rooms"_ does not appear because it's under the _"Conversation settings"_ windows
9. If the _"Configure breakout rooms"_ appear when you click on the _"Create rooms"_ button there is an error _"An error occurred while creating breakout rooms"_ and the breakout rooms are not created.

### Expected behaviour
Add breakout rooms when there is already one.

### Actual behaviour
The additional breakout rooms are not created

## Talk app

**Talk app version:** 21.1 and newer

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser
All
**Operating system:** Windows/Ubuntu/Mac/...
All
**Browser name:** Firefox/Chrome/Safari/...
All
**Browser version:** 124/125/...
Firefox 147
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian
**Web server:** Apache/Nginx
Apache
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB
**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #16726
  * Already configured rooms should show the participants editor / manager to move them across rooms, or delete all rooms
  * Logic, styles and strings copied from Right sidebar > Breakout rooms action
  * Modals are now mounted inside the conversation settings dialog - so should not be behind

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image

### 🏁 Checklist

- [x] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [x] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by Antreesy** [comment]
Great, I misclicked on PR creation and it's still following me 🙈

File: src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue [hunk 1]
```diff
@@ -6,6 +6,7 @@
 <template>
 	<NcModal
 		:class="{ 'modal-mask__participants-step': isEditingParticipants }"
+		:container="container"
```
Comment (DorraJaouad) [inline src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:9]: Screenshot 2026-02-02 at 11 03 22

It needs a container for the one in Topbar

Comment (DorraJaouad) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:9]: Yeah, also this
image

Comment (Antreesy) [reply src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue:9]: See fixup. TopBar is behind RightSidebar, so dialog should be mounted to body

**Review by DorraJaouad — APPROVED** [review]
Now all good
