### PR TITLE
fix(Dashboard): add harmonized layout

### LINKED ISSUE #15514: Dashboard / Home view is not balanced / harmonic with few conversations
It was mentioned that when a user has very few, no or only the default conversations, the dashboard is very empty and confusing.

Image

First step now would be to find what we could do to improve the situation.

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #15514

### 🖼️ Screenshots / Screencasts

Dark mode | Light mode
-- | --
image | image
Filled state | image

- [ ] There is a text under Welcome to Nextcloud Talk´, it was not finalized in design so I didn't add it
- [ ] Dark mode svgs?

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [ ] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by Antreesy** [comment]
Can we go a bit more aligned-centered-rounded with Welcome column?
image

But honestly, I still don't see the purpose of Talk 'welcome' icon there 🙈

**Comment by nimishavijay** [comment]
Edit: added event card updates and confirmed single column layout

Looks really good! some comments regarding the filled states:

- [x] We can add a shadow to the "Start meeting" button too
- [x] when the unread mentions/reminders are filled, instead of the image itself we can have a fade. With the image in such a small height it looks like something is cut off. A fade would look more intentional
- [ ] When there are scheduled events the height of each event card can be reduced. I also think they look a bit flat atm against the other elements having a shadow ~so I will experiment a bit with how they can look~
  - [ ] The height can be reduced to 200px
  - [x] We can add a border of --color-primary-element-light-hover 
  - [x] reduce the border of all the cards to 2px from 3px 

image

Got confirmation that we can go ahead with the single column layout with unread mentions and message reminders for now and add threads if we get there. So we don't need the "welcome to nextcloud talk" column. 

Also when I try to test it this is happening? The unread mentions/reminder should definitely be taller

image

**Comment by DorraJaouad** [comment]
> when the unread mentions/reminders are filled, instead of the image itself we can have a fade. With the image in such a small height it looks like something is cut off. A fade would look more intentional

Note that the fade will adjust to theming but icons won't

image

> The height can be reduced to 200px

It is not possible because it is the least height that can accomodate the case when all elements are present (date, description, attachment etc)

> Got confirmation that we can go ahead with the single column layout with unread mentions and message reminders for now and add threads if we get there. So we don't need the "welcome to nextcloud talk" column.

Which mockup is it?

**Comment by nimishavijay** [comment]
> Note that the fade will adjust to theming but icons won't

When there is a themed instance we don't need to use the icons for now, just the fade is enough. @Antreesy there was some discussion about this in the chat 

> Which mockup is it?

The first one in https://github.com/nextcloud/spreed/issues/15514#issuecomment-3112779037

Only change would be filled state where the width of the fade will be lesser 

So this:

image

image

File: src/components/Dashboard/TalkDashboard.vue [hunk 1]
```diff
@@ -43,6 +42,7 @@ const canModerateSipDialOut = hasTalkFeature('local', 'sip-support-dialout')
 	&& getTalkConfig('local', 'call', 'can-enable-sip')
 const canStartConversations = getTalkConfig('local', 'conversations', 'can-create')
 const isDirectionRTL = isRTL()
+const isMobile = useIsMobile()
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:45]: We should treat differently all three cases:
< 512px - single column interface
512 < '|' < 1024px - LS is positioned absolutely, no point in stealing 300px
> 1024px - good idea to reserve space for LS
```suggestion
const isMobile = useIsMobile()
const isSmallMobile = useIsSmallMobile()
```

File: src/components/Dashboard/TalkDashboard.vue [hunk 2]
```diff
@@ -177,171 +177,187 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
-			</NcPopover>
-			<NcButton v-if="canStartConversations"
-				@click="EventBus.emit('new-conversation-dialog:show')">
-				<template #icon>
-					<IconPlus :size="20" />
-				</template>
-				{{ t('spreed', 'Create a new conversation') }}
-			</NcButton>
+	<div class="talk-dashboard-wrapper"
+		:class="{ 'talk-dashboard-wrapper--mobile': isMobile }">
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]:
```suggestion
		:class="{
			'talk-dashboard-wrapper--mobile': isMobile,
			'talk-dashboard-wrapper--small-mobile': isSmallMobile,
		}">
```

File: src/components/Dashboard/TalkDashboard.vue [hunk 3]
```diff
@@ -351,21 +367,37 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
+	padding: calc(var(--default-grid-baseline) * 2) calc(var(--default-grid-baseline) * 3);
+	width: calc(100vw - 300px - var(--body-container-margin) * 2); // 300px for the left sidebar and body container margins
 	margin: 0 auto;
+	display: flex;
+	flex-direction: column;
+	height: 100%;
+	max-height: 800px;
+	max-width: 1200px;
+
+	&--mobile {
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:383]:
```suggestion
	&--mobile {
		max-width: calc(100vw - var(--body-container-margin) * 2); // 300px for the left sidebar and body container margins
	}

	&--small-mobile {
```

File: src/components/Dashboard/TalkDashboard.vue [hunk 4]
```diff
@@ -351,21 +367,37 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
 
 .talk-dashboard-wrapper {
-	--title-height: calc(var(--default-clickable-area) + var(--default-grid-baseline) * 3); // '.title' height
-	--section-width: 300px;
-	--section-height: 300px;
-	--content-height: calc(100% - var(--title-height));
-	padding: 0 calc(var(--default-grid-baseline) * 3);
-	max-width: calc($messages-list-max-width + 400px); // FIXME: to change to a readable value
+	padding: calc(var(--default-grid-baseline) * 2) calc(var(--default-grid-baseline) * 3);
+	width: calc(100vw - 300px - var(--body-container-margin) * 2); // 300px for the left sidebar and body container margins
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:375]:
```suggestion
	max-width: calc(100vw - 300px - var(--body-container-margin) * 2); // 300px for the left sidebar and body container margins
```

File: src/components/Dashboard/Section.vue [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+const isMobile = useIsMobile()
+</script>
+
+<template>
+	<div class="dashboard-section"
+		:class="{
+			'dashboard-section--wide': wide,
+			'dashboard-section--list': $slots.list,
+		}">
+		<div v-if="!isMobile"
```
Comment (Antreesy) [inline src/components/Dashboard/Section.vue]: 512-1024px still has enough space to show narrow bar (but we can set it to do so without image)
```suggestion
		<div v-if="!isSmallMobile"
```

Image

File: src/components/Dashboard/TalkDashboard.vue [hunk 6]
```diff
@@ -351,21 +367,37 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
 	margin: 0 auto;
+	display: flex;
+	flex-direction: column;
+	height: 100%;
+	max-height: 800px;
+	max-width: 1200px;
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:381]: do not see this affects something. Section component is limited horizontally already

```suggestion
```

File: src/components/Dashboard/TalkDashboard.vue [hunk 7]
```diff
@@ -351,21 +367,37 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
+		width: 100%;
+		grid-template-columns: 1fr;
+
+		.talk-dashboard__chats {
+			grid-template-columns: 1fr;
+			gap: 0;
+		}
+
+		.event-section {
+			width: 350px;
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: I'd remove this style, looks better without limitation on both filled and empty section
a | b
-- | --
Image | Image

File: src/components/Dashboard/TalkDashboard.vue [hunk 8]
```diff
@@ -374,13 +406,30 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
+	justify-content: space-evenly;
 
-	:deep(.button-vue) {
+	:deep(.button-vue),
+	:deep(.v-popper--theme-dropdown) {
+		box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.2);
 		height: var(--header-menu-item-height);
+		border-radius: var(--border-radius-large);
+		flex: 1;
+		width: 100%;
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue:421]: This breaks wrapping on mobile

File: src/components/Dashboard/Section.vue [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+		font-weight: bold;
+	}
+
+	&__subtitle {
+		font-weight: bold;
+	}
+
+	&__action {
+		margin-block: auto;
+		padding-inline: calc(var(--default-grid-baseline) * 2);
```
Comment (Antreesy) [inline src/components/Dashboard/Section.vue]: It's asking for a bit more padding from the side. Maybe *6 or *8?

File: src/components/Dashboard/TalkDashboard.vue [hunk 10]
```diff
@@ -177,171 +177,187 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
-					<template #icon>
-						<IconAt :size="40" />
+				<LoadingPlaceholder v-else-if="!eventsInitialised"
+					type="event-cards" />
+				<Section v-else
+					class="event-section--empty"
+					wide
+					:title="t('spreed', 'Schedule meetings')"
+					:subtitle="t('spreed', 'You don\'t have any upcoming meetings')"
+					:description="t('spreed', 'Schedule a meeting with a colleague from your calendar')">
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: We should avoid using 'with a colleague' here, as NC can be used for other purposes. `Schedule a meeting from your calendar` looks good enough to me.

It's also worth to mention in documentation, that:
- in Calendar, location should be set to Talk conversation;
- in Talk, there's a shortcut for it in every conversation.

File: src/components/Dashboard/TalkDashboard.vue [hunk 11]
```diff
@@ -177,171 +177,187 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
+						<template #list>
+							<ConversationsListVirtual
+								class="talk-dashboard__conversations-list"
+								:conversations="filteredConversations"
+								:loading="!conversationsInitialised" />
+						</template>
+					</Section>
+					<Section v-else
+						:title="t('spreed', 'Mention colleagues')"
+						:description="t('spreed', 'Mention your colleagues with @ followed by their name')">
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: Same here with colleagues, but I don't have a clear idea. cc @nimishavijay @nickvergessen 

Also this is not about 'mentioning someone', it's about 'someone mentioning you'. Maybe smth like:

### Stay connected / Get in touch / Do not miss anything / _or keep it as-is 'Unread mentions'_

> When people message you directly or mention you in group conversations, they'll show up here / Direct messages and mentions from other people will appear here

File: src/components/Dashboard/TalkDashboard.vue (hunk 3 above)
Comment (DorraJaouad) [reply src/components/Dashboard/TalkDashboard.vue:383]: Please note that width is only applied on >1024px already, otherwise it is 100%

File: src/components/Dashboard/TalkDashboard.vue (hunk 4 above)
Comment (DorraJaouad) [reply src/components/Dashboard/TalkDashboard.vue:375]: I want it a fixed width

File: src/components/Dashboard/TalkDashboard.vue (hunk 3 above)
Comment (Antreesy) [reply src/components/Dashboard/TalkDashboard.vue:383]: 100% is also good

File: src/components/Dashboard/TalkDashboard.vue (hunk 6 above)
Comment (DorraJaouad) [reply src/components/Dashboard/TalkDashboard.vue:381]: > Section component is limited horizontally already

Limitation is relative (100vw) but it should be statically limited
image

> height: 100%;

Needed for filling the full space

> max-height: 800px;

Needed to not to look like this when we add a section that is not height limited

image

File: src/components/Dashboard/TalkDashboard.vue (hunk 4 above)
Comment (Antreesy) [reply src/components/Dashboard/TalkDashboard.vue:375]: It shouldn't be, you will get a horizontal scroll

File: src/components/Dashboard/Section.vue (hunk 9 above)
Comment (DorraJaouad) [reply src/components/Dashboard/Section.vue]: I am worried about mobile view, maybe it should be like this then ?
image

Comment (Antreesy) [reply src/components/Dashboard/Section.vue]: Let's discuss tomorrow in call. I don't like it on the right either way

File: src/components/Dashboard/TalkDashboard.vue [hunk 12]
```diff
@@ -28,6 +26,7 @@ import ConversationsListVirtual from '../LeftSidebar/ConversationsList/Conversat
 import SearchMessageItem from '../RightSidebar/SearchMessages/SearchMessageItem.vue'
 import LoadingPlaceholder from '../UIShared/LoadingPlaceholder.vue'
 import EventCard from './EventCard.vue'
+import Section from './Section.vue'
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: Let's call it DashboardSection? We currently disable the eslint rule, that Vue component name should be multi-word. Also there is valid HTML tag `<section>`

File: src/components/Dashboard/TalkDashboard.vue [hunk 13]
```diff
@@ -177,171 +178,190 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
+										hash: `#message_${reminder.messageId}`,
+									}"
+									:actor-id="reminder.actorId"
+									:actor-type="reminder.actorType"
+									:timestamp="reminder.reminderTimestamp"
+									is-reminder />
+							</ul>
+						</template>
+					</Section>
+					<LoadingPlaceholder v-else-if="!remindersInitialised"
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: Mentions/Reminders placeholders should be inside of template#list, looks ugly otherwise:

Image

File: src/components/Dashboard/TalkDashboard.vue [hunk 14]
```diff
@@ -305,33 +305,33 @@ function scrollEventCards({ direction }: { direction: 'backward' | 'forward' })
...
 								:loading="!conversationsInitialised" />
 						</template>
-					</Section>
-					<Section v-else
-						:title="t('spreed', 'Mention colleagues')"
-						:description="t('spreed', 'Mention your colleagues with @ followed by their name')">
+					</DashboardSection>
+					<DashboardSection v-else
+						:title="t('spreed', 'Unread mentions')"
+						:description="t('spreed', 'Messages where you were mentioned will show up here \. You can mention people by typing @ followed by their name')">
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: `will show up here.` maybe, without extra characters?

**Review by Antreesy — APPROVED** [review]
Otherwise good
