### PR TITLE
Fix poll voter details

### LINKED ISSUE #7836: Only 8 voters are shown per option even when "expanding" the list
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Similar issue as with reactions back then. Because a tooltip alike popover is used, it is not possible to see the full result list and who voted for what.
* Currently only 8 avatars are shown 🆗 
* When expanding by clicking them you can see 8 avatars and displaynames 🚯 

In order to use it for recorded votings in bigger rooms there needs to be a way to see the full list of who voted what.

### PR DESCRIPTION
**Pull request by marcoambrosini**
Signed-off-by: Marco <marcoambrosini@icloud.com>

fix #7836 

Screenshot 2022-09-16 at 09 40 06

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue [hunk 1]
```diff
@@ -24,7 +24,7 @@
 		<button slot="trigger"
 			tabindex="0"
 			class="poll-voters-details">
-			<AvatarWrapperSmall v-for="(item, index) in details"
+			<AvatarWrapperSmall v-for="(item, index) in details.slice(0, 8)"
```
Comment (nickvergessen) [inline src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue:27]: Should we have a guest avatar with `…` in case there where more than the slice?

Comment (marcoambrosini) [reply src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue:27]: yes we should, separate issue tho

**Review by nickvergessen — APPROVED** [review]
