### PR TITLE
fix(groupware): omit duplicate upcoming events

### LINKED ISSUE #14496: Merge "next meeting" from different calendars
I have access to multiple calendars. Each of them has the same weekly call in their calendar.

If I open the "next meeting" drop-down I see the same meeting multiple time:

Image

Would be great if they get merged in one list. Otherwise it can be quite confusing and you risk to miss another meeting between the duplicates.

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #14496 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
2025-05-29_15h24_20 | 2025-05-29_15h19_40

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/stores/groupware.ts [hunk 1]
```diff
@@ -100,7 +100,12 @@ export const useGroupwareStore = defineStore('groupware', {
 			const location = generateUrl('call/{token}', { token }, { baseURL: getBaseUrl() })
 			try {
 				const response = await getUpcomingEvents(location)
-				Vue.set(this.upcomingEvents, token, response.data.ocs.data.events)
+				const uniqueEvents = response.data.ocs.data.events.filter((event, index, array) => {
+					// Keep only first meeting with the same location and start time
+					return index === array.findIndex((item) => item.start === event.start)
+				})
```
Comment (ShGKme) [inline src/stores/groupware.ts:106]: Do we always have only a small number of events here?

Comment (Antreesy) [reply src/stores/groupware.ts:106]: Yes, it's limited to 10 by dav endpoint
