### PR TITLE
Fix room renaming event

### LINKED ISSUE #369: Renaming a room multiple times causes increasing number of requests to the server
## Steps to reproduce
1. Create a room
2. Rename it a couple of times

### Expected behaviour
Each rename should cause only one request to the server.

### Actual behaviour
The number of requests to the server is increasing with each rename. Looks like a new handled is registered every time while the old ones are still active (and also get executed).

@Ivansss we were talking about this recently.

### PR DESCRIPTION
**Pull request by Ivansss**
- Fix #369

### CODE REVIEW

File: js/views/roomlistview.js [hunk 1]
```diff
@@ -272,6 +265,14 @@
 				this.renameRoom(newRoomName);
 			}
 		},
+		renameKeyUp: function(e) {
+			if (e.keyCode === 13) {
+				this.confirmRoomRename();
+			} else if (e.keyCode === 27) {
+				this.$el.find('.rename-element').addClass('hidden-important');
```
Comment (fancycode) [inline js/views/roomlistview.js]: lgtm with a small change: can you move these two lines in a separate function like `showRenameInput`? Call from here as `showRenameInput(false)` to hide the input and show the button and adjust the other places that do the same?

**Comment by fancycode** [comment]
:+1:
