### PR TITLE
fix(call): resume input device track after change

### LINKED ISSUE #15614: Device selection mutes the microphone
These actions mute the microphone:
- MediaSettings in call: changing the camera/mic hardware
- BottomBar in call: changing the camera/mic hardware

Most likely comes from assumption, that when we're in the call opening device checker, microphone and camera should be disabled on change, as you might want to try different devices before applying settings. That shouldn't work the same way in BottomBar

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/pull/15583#discussion_r2248391154_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #15614
  * with BottomBar and one-click selection, devices should not be muted anymore from uset dropdown click, as they directly trying them during the call.
  * add `resume*AfterChange` to set back enabled state

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
2025-08-18_13h17_08 | 2025-08-18_13h19_12
b | 2025-12-29_12h54_10

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] ⛑️ Tests are included or not possible

### CODE REVIEW

File: src/utils/webrtc/models/LocalMediaModel.js [hunk 1]
```diff
@@ -199,6 +201,10 @@ LocalMediaModel.prototype = {
 	_updateMediaAvailability(localStream) {
 		if (localStream && localStream.getAudioTracks().length > 0) {
 			this.set('audioAvailable', true)
+			if (this.get('audioEnabled') === false && this.get('resumeAudioAfterChange')) {
+				localStream.getAudioTracks()[0].enabled = true
+				this.set('resumeAudioAfterChange', false)
+			}
```
Comment (DorraJaouad) [inline src/utils/webrtc/models/LocalMediaModel.js]: It should not enable stream when it was disabled 🫨 
We should stop disabling it in the first place and not forcibly enable it here

Comment (Antreesy) [reply src/utils/webrtc/models/LocalMediaModel.js]: Unless @danxuliu has an idea, I don't see how it's possible without reworking the whole codebase.

See `_updateMediaAvailability` fired two times at the function call:
1. with no audio tracks -> `this.set('audioEnabled', false)`
2. with a new track -> already disabled, new track is disabled too

image

as we switching tracks, it also recorded in `TrackEnabler#._handleInputTrack`:
1. track: null -> this._enabled = false
2. track Track (enabled: true) -> but track.enabled = this._enabled from null

by `resumeAudioAfterChange` we can at least manually define the moment of when it should be enabled back

**Comment by DorraJaouad** [comment]
https://github.com/user-attachments/assets/1fa3ad30-41b8-4f51-905a-5d6aaf0fc2cb

I am not sure about the glitchy disabling when mic is on.

File: src/utils/webrtc/models/LocalMediaModel.js (hunk 1 above)
Comment (Antreesy) [reply src/utils/webrtc/models/LocalMediaModel.js]: After the second check, confirming this. Track based on previous inputId is stopped and removed, for a brief second when `_updateMediaAvailability` is called, local media does not have any tracks, therefore it is disabled. That might still be a limitation for browsers to maintain only single track simultaneously, so we can't easily avoid interruption.

In a background, output track is getting replaced for peer connections, so once it's ready, track can be enabled again by user or by client (we do second in this case)

**Comment by Antreesy** [comment]
Rewrote the solution to keep it in component only and not introduce any changes within the localModel
