### PR TITLE
fix(Translation): adjust unfocusing hack

### LINKED ISSUE #16061: Translation feature for messages shows empty modal
1. Open a conversation with a message
2. Click "Translate" in three- dot menu (on web and Desktop client, Mobile works according to @Ivansss )

The request (`languages`) is done and the response is there, but it's not rendered.

### Expected behaviour
The modal has content

### Actual behaviour
The modal doesn't have content

## Talk app

On c.nc.com

**Talk app version:** 22.0.0
**Custom Signaling server configured:** yes
**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Browser

**Browser name:** Firefox, Chrome

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #16061

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Screenshot before | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue [hunk 1]
```diff
@@ -110,6 +111,13 @@ export default {
 
 	emits: ['close'],
 
+	setup() {
+		const translateDialog = useTemplateRef('translate-dialog')
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue]: As we do in nextcloud-vue
```suggestion
		const translateDialogElement = useTemplateRef('translateDialog')
```

File: src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue [hunk 2]
```diff
@@ -205,7 +213,8 @@ export default {
 
 		this.$nextTick(() => {
 			// FIXME trick to avoid focusTrap() from activating on NcSelect
-			this.isMounted = !!this.$refs.translateDialog.navigationId
+			this.translateDialog?.$el?.focus()
```
Comment (Antreesy) [inline src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue]: Not needed, focus is on 'close' button

**Review by Antreesy — APPROVED** [review]

**Review by Antreesy — APPROVED** [review]
