### PR TITLE
fix: provide media controls access for participants with no permissions

### LINKED ISSUE #16631: Being muted blocks access to audio output settings
When you're in a call where you don't have talk permissions, the audio settings menu (up arrow next to your mic button) is blocked.

While not having access to the microphone settings makes sense, that menu also contains the audio output settings which is still useful.

## Steps to reproduce
1. Join a call where you don't have talk permissions
2. Try to change your audio output

### Expected behaviour
You can still change your output settings even when muted

### Actual behaviour
Audio settings can't be accessed

## Talk app

**Talk app version:** 22.0.7

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #16631
  * Disabled state for toggle button should bring the device check dialog (as it was originally)
  * Imitate disabled appearance with no event prevention
  * In popover, hide input actions, if not allowed to enable in call, show only output

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
image | image
image | image

image

### 🚧 Tasks

- [x] Cases, when it's allowed, but not available? - navigator.mediaDevices.getUserMedia Promise is rejected, no output devices to show anyway

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/CallView/shared/LocalAudioControlButton.vue [hunk 1]
```diff
@@ -41,26 +41,31 @@
 
 		<NcActions
 			v-if="showDevices"
-			:disabled="!isAudioAvailable || !isAudioAllowed"
+			:disabled="!isAudioAllowed && !audioOutputSupported"
```
Comment (DorraJaouad) [inline src/components/CallView/shared/LocalAudioControlButton.vue]: Nein
image
```suggestion
			:disabled="!isAudioAvailable || (!isAudioAllowed && !audioOutputSupported)"
```

Comment (Antreesy) [reply src/components/CallView/shared/LocalAudioControlButton.vue]: Original behaviour was `:disabled="!isAudioAvailable || !isAudioAllowed"`, so it'll still be disabled and does not solve an issue.
How can I reproduce it?

Comment (DorraJaouad) [reply src/components/CallView/shared/LocalAudioControlButton.vue]: Disable access to devices from browser or simply with no https connection

Comment (Antreesy) [reply src/components/CallView/shared/LocalAudioControlButton.vue]: This is the wrong case for browser permissions, not Talk permissions; but it's captured separately by audioStreamError and videoStreamError

Adjusted conditions:
image

**Review by DorraJaouad — APPROVED** [review]
Looks good, also the error state addition

File: src/components/CallView/shared/LocalAudioControlButton.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/components/CallView/shared/LocalAudioControlButton.vue]: No, there is no error state

In media settings
image

In bottom bar:
image

**Comment by ShGKme** [comment]
Did I get it correctly that when there is no access, mic/video toggle (on/off) button opens the device picker?

**Comment by Antreesy** [comment]
> when there is no access, mic/video toggle (on/off) button opens the device picker?

Yes, that was the original behavior from the old times, but it was locked by 'disabled' attribute:
- if you don't have permissions in the room, you can still set up your mic and camera where, before permissions granted to you;
- if there's an access error... we may probably handle it better, to explain reasons to user
