### PR TITLE
fix(conversation): Fix string for automatic deletion

### LINKED ISSUE #17381: German Translation
I just stumbled over this weird sounding German translation while testing NextCloud Talk.

**Maybe someone more experienced could turn this into a appropriate pull request.** 

### The passage in question:

https://github.com/nextcloud/spreed/blob/d7f58c3ac7b00cca8147dedf0b420a132fd190bb/l10n/de.js#L1928

https://github.com/nextcloud/spreed/blob/d7f58c3ac7b00cca8147dedf0b420a132fd190bb/l10n/de_DE.js#L1928

https://github.com/nextcloud/spreed/blob/d7f58c3ac7b00cca8147dedf0b420a132fd190bb/l10n/de.json#L1926

https://github.com/nextcloud/spreed/blob/d7f58c3ac7b00cca8147dedf0b420a132fd190bb/l10n/de_DE.json#L1926

Resulting in sentences like: 

> Diese Unterhaltung wird für alle seit in 1 Tag Inaktiven automatisch gelöscht.

literally sounding a bit like: 
> This conversation will be automatically deleted for everyone since in 1 day of inactives

### Suggested change

```
    "This conversation will be automatically deleted for everyone {expirationDurationFormatted} of no activity." : "Diese Unterhaltung wird für alle {expirationDurationFormatted} Inaktivität automatisch gelöscht.",
```

Resulting in sentences like: 
> Diese Unterhaltung wird für alle in 1 Tag Inaktivität automatisch gelöscht.

### Considerations
This is still not sounding very pleasant in German. Even better would be 

> Diese Unterhaltung wird für alle **nach** 1 Tag Inaktivität automatisch gelöscht.

But I guess it's more error prone to change the behavior of `expirationDurationFormatted` than it's worth for this sentence.

### PR DESCRIPTION
**Pull request by nickvergessen**
## ☑️ Resolves

* Fix #17381 

### Before
This conversation will be automatically deleted for everyone in 28 days of no activity.

### After
This conversation will be automatically deleted for everyone, after 28 days of inactivity.

In German (and potentially other languages) the string made even less sense

### CODE REVIEW

File: src/components/UIShared/ConversationActionsShortcut.vue [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 <script setup lang="ts">
 import { showError } from '@nextcloud/dialogs'
-import { getLanguage, t } from '@nextcloud/l10n'
+import { getLanguage, t, n } from '@nextcloud/l10n'
```
Comment (Antreesy) [inline src/components/UIShared/ConversationActionsShortcut.vue]:
```suggestion
import { n, t } from '@nextcloud/l10n'
```

File: src/components/UIShared/ConversationActionsShortcut.vue [hunk 2]
```diff
@@ -52,8 +52,12 @@ const descriptionLabel = computed(() => {
 	if (expirationDuration.value === 0) {
 		return t('spreed', 'Would you like to delete this conversation?')
 	}
-	const expirationDurationFormatted = new Intl.RelativeTimeFormat(getLanguage(), { numeric: 'always' }).format(expirationDuration.value!, 'days')
-	return t('spreed', 'This conversation will be automatically deleted for everyone {expirationDurationFormatted} of no activity.', { expirationDurationFormatted })
+	return n(
+		'spreed',
+		'This conversation will be automatically deleted for everyone, after %n day of inactivity.',
+		'This conversation will be automatically deleted for everyone, after %n days of inactivity.',
```
Comment (Antreesy) [inline src/components/UIShared/ConversationActionsShortcut.vue]: Don't think we need a comma here
```suggestion
		'This conversation will be automatically deleted for everyone after %n day of inactivity.',
		'This conversation will be automatically deleted for everyone after %n days of inactivity.',
```
