### PR TITLE
Fix(call): hide call button in dashboard when calls are disabled

### LINKED ISSUE #17215: "Start meeting now" button is active when calls are disabled
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Disable Talk calls on your Nextcloud instances 
2. All buttons to start a call are disabled, but this one
3.

Image

### Expected behaviour
"Start meeting now" button should not be here

### Actual behaviour
"Start meeting now" button is still here. 

### Workaround
Disable the button using custom css
```
.talk-dashboard__actions div button:first-of-type {
  display: none;
}
```

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)
22.0.9 I have seen this problem appeared in earlier versions but haven't noted the exact version. I feel like it appeared when the new dashboard was introduced.

**Nextcloud Version:** (see administration page)
32.0.6

Best regards,

### LINKED ISSUE #17231: "Limit starting a call" cannot be saved - POST responds with Error 400
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Fresh nextcloud installation v32 -> upgrade to v33
2. Install Talk App
3. Change "Limit starting a call" to anything

### Expected behaviour
Setting should be saved

### Actual behaviour
AJAX POST responds with error 400 - setting is not saved
(All other settings can be saved without problems)

## Talk app

**Talk app version:** 23.0.1

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Mac

**Browser name:** Firefox

**Browser version:** 148

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:** 8.4

**Nextcloud Version:** 33.0.0

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #17215
* Fix #17231

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/Dashboard/TalkDashboard.vue [hunk 1]
```diff
@@ -40,6 +41,7 @@ const canModerateSipDialOut = hasTalkFeature('local', 'sip-support-dialout')
 	&& getTalkConfig('local', 'call', 'sip-enabled')
 	&& getTalkConfig('local', 'call', 'sip-dialout-enabled')
 	&& getTalkConfig('local', 'call', 'can-enable-sip')
+const isCallEnabled = loadState('spreed', 'call_enabled')
```
Comment (Antreesy) [inline src/components/Dashboard/TalkDashboard.vue]: What about
```suggestion
const isCallEnabled = getTalkConfig('local', 'call', 'enabled')
```

Comment (DorraJaouad) [reply src/components/Dashboard/TalkDashboard.vue]: I initially put it with talk config, but wanted to align with CallButton. Maybe change both

Comment (Antreesy) [reply src/components/Dashboard/TalkDashboard.vue]: CallButton should even check for federated capabilities

File: src/components/TopBar/CallButton.vue [hunk 2]
```diff
@@ -376,7 +376,7 @@ export default {
 	},
 
 	mounted() {
-		this.callEnabled = loadState('spreed', 'call_enabled')
+		this.callEnabled = getTalkConfig(this.token, 'call', 'enabled')
```
Comment (Antreesy) [inline src/components/TopBar/CallButton.vue]: This feels like it should be a computed property
