### PR TITLE
fix(AuthSidebar): Order popups

### LINKED ISSUE #10959: Video verification pops a dialog in the background
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Share a file as public link
2. Add a password
3. Enable video verification
4. As a guest in a private tab open the link:
Bildschirmfoto vom 2023-11-21 09-50-40
5. Click on "Request password" button:
Bildschirmfoto vom 2023-11-21 09-50-47
6. Close media settings and then see the guest name popup:
Bildschirmfoto vom 2023-11-21 09-50-52

Not sure which behaviour would be expected. Could be the current one or the guest name should be on top of it. But since the call is already ringing the video/mic options also seem important?

cc @DorraJaouad what do you think? Close or resort?

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10959

The condition in MediaSettings for displaying the display name input ( theoretically) should be valid only in `PublicShareAuthSidebar` when the user is a guest because in all other windows, the guest name pop up window is always shown first and cannot be bypassed. 

### 🖼️ Screenshots / Screencasts

🏚️ Before (opacity to show both) 
 image 

🏡 After

https://github.com/nextcloud/spreed/assets/84044328/60ca1239-f475-4eaa-832d-0b4231edfaf3

### 🚧 Tasks

TODO
- [x] fix style ( it feels like it is missing padding)
- [x] Double-check if `guestName` ( the removed computed prop) is not needed in MediaSettings

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/ChatView.vue [hunk 1]
```diff
@@ -23,7 +23,7 @@
 		@dragover.prevent="handleDragOver"
 		@dragleave.prevent="handleDragLeave"
 		@drop.prevent="handleDropFiles">
-		<GuestWelcomeWindow v-if="isGuestWithoutDisplayName" :token="token" />
+		<GuestWelcomeWindow v-if="showGuestNameWindow" :token="token" />
```
Comment (Antreesy) [inline src/components/ChatView.vue:26]:
```suggestion
		<GuestWelcomeWindow v-if="showGuestWelcomeWindow" :token="token" />
```

I'd name this computed (and prop) the same way we named a component, for consistensy

File: src/components/MediaSettings/MediaSettings.vue [hunk 2]
```diff
@@ -119,6 +119,14 @@
 				:token="token"
 				@update-background="handleUpdateVirtualBackground" />
 
+			<!-- Setting guest name -->
+			<div> {{ t('spreed','Please enter a display name') }} </div>
+			<NcTextField v-if="isUnknownGuest"
```
Comment (Antreesy) [inline src/components/MediaSettings/MediaSettings.vue:124]:
```suggestion
			<template v-if="isUnknownGuest">
				<p> {{ t('spreed','Please enter a display name') }} </p>
				<NcTextField 
```

**Review by Antreesy — COMMENTED** [review]
Looks OK, but haven't tested i yet. Ping me, if you want me to take it over

File: src/components/MediaSettings/MediaSettings.vue [hunk 3]
```diff
@@ -119,6 +119,17 @@
 				:token="token"
 				@update-background="handleUpdateVirtualBackground" />
 
+			<!-- Setting guest name -->
+			<template v-if="isUnknownGuest">
+				<label for="guestname-prompt" class="media-settings__guestname-label">
+					{{ t('spreed','Please enter a display name') }}
```
Comment (nickvergessen) [inline src/components/MediaSettings/MediaSettings.vue:125]:
```suggestion
					{{ t('spreed','Enter your name') }}
```

Same wording as in the normal dialog?

**Review by marcoambrosini — CHANGES_REQUESTED** [review]
I don't think we should add this in the media settings. Either we keep it in a separate dialog or we omit it imo

**Comment by Antreesy** [comment]
Another option would be to disable automatic call, so user has to
- enter guest name to "unlock" screen
- click "Start call" manually => MediaSettings won't pop up

**Comment by Antreesy** [comment]
Rebased onto main, split into two commits:
- First one is for omiting dialog for public share component
- Second one is for inserting input into the Media Settings (we could drop it, if come to an agreement)

**Comment by DorraJaouad** [comment]
> Either we keep it in a separate dialog or we omit it imo

I think it's too many popups if we keep them both. If adding the name input is not possible in MediaSettings, we have the following options suggested
A: Remove guest name pop up and guest will always have translatable "Guest" in public share.
B: Disable automatic call.

Which one to go with ?

**Comment by marcoambrosini** [comment]
Ideally we would use the same dialog but have two "pages", mre or less like we did in the first run wizard. If that's too tricky I think that 2 dialogs is the way to go.

**Comment by nickvergessen** [comment]
Could we then somehow change the order so guest name is first modal and then the media settings?

**Comment by Antreesy** [comment]
> so guest name is first modal and then the media settings?

Listen for a guest name to be set, then trigger this step:
https://github.com/nextcloud/spreed/blob/48df3840bb47edb8d227baa313727211aed3d343/src/PublicShareAuthSidebar.vue#L100-L104

**Comment by DorraJaouad** [comment]
The conversation needs to be joined to show the guest pop up. Event listening should happen between joining and fetching the conversation. So trigger the rest of the `joinConversation()` after listening to the guest name event.

File: src/PublicShareAuthSidebar.vue [hunk 4]
```diff
@@ -124,6 +124,14 @@ export default {
 		})
 	},
 
+	mounted() {
+		subscribe('guest-name-added', this.postJoinConversation)
```
Comment (nickvergessen) [inline src/PublicShareAuthSidebar.vue:128]: Every time a guest sets their name, they will now execute postJoin

Comment (DorraJaouad) [reply src/PublicShareAuthSidebar.vue:128]: The component is not mounted unless it is called which is with "request password" button click. It is not mounted with Talk app. 
or am I overlooking sthg ?

Comment (nickvergessen) [reply src/PublicShareAuthSidebar.vue:128]: yeah no that's all okay, but yeah I missed that guests don't have a rename option there.

Comment (Antreesy) [reply src/PublicShareAuthSidebar.vue:128]: event can be emitted only from two components:

image

Technically, there is only one way (and one chance) to submit a guest name from this sidebar. Although it's better to add some guard to it, to ensure we won't trigger it again

Also guest could submit his name earlier (in one of the public chats), so please check, if that name is available

File: src/PublicShareAuthSidebar.vue [hunk 5]
```diff
@@ -187,6 +174,36 @@ export default {
...
+			// joined the conversation (otherwise only limited data would be
+			// received if the user was not a participant of the conversation
+			// yet).
+			await this.fetchCurrentConversation()
+
+			// Joining the call needs to be done once the participant identifier
+			// has been set, which is done once the conversation has been
+			// fetched. MediaSettings are called to set up audio and video devices
+			// and also to give a consent to recording, if set up
+			emit('talk:media-settings:show')
```
Comment (Antreesy) [inline src/PublicShareAuthSidebar.vue:189]: everything apart from this line should be safe to keep in `joinConversation`, as it's only about fetching the conversation, that shouldn't be blocking for unknown guests (to let them know a moderator has started a call, for example)

**Comment by nickvergessen** [comment]
> /home/runner/work/spreed/spreed/src/PublicShareAuthSidebar.vue
Error:   59:34  error  Unable to resolve path to module '../services/participantsService.js'  import/no-unresolved
Error:   59:34  error  "../services/participantsService.js" is not found                      n/no-missing-import

**Review by Antreesy — APPROVED** [review]
Tested
