### PR TITLE
fix(LeftSidebar): revert temp styles and fix conversation styling

### LINKED ISSUE #10443: Conversation item border is cut of when tabbing
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Click into the search and tab into the conversation list

### Expected behaviour
Border around the conversation

### Actual behaviour
is cut off:
grafik

## Talk app

**Talk app version:**stable27

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

* Fix #10443 again :') ( changes of its PR were reverted [here](https://github.com/nextcloud/spreed/commit/948a640bcd7d60078269b19f5fa0d36b6d61f9fb#diff-7a1abf98ca549db81a418814a97629c796bc85dc32b40f9cffb65ce3ad40d555) ). Another workaround is now used which is basically moving the outline inside the element.
* Fix the unexpected outline on favorite conversations ( border radius is changing) . As I checked, there was no explicit style for the border radius coming from the favorite icon node. Setting `overflow: hidden` solved it though 
* Revert some changes after merging https://github.com/nextcloud-libraries/nextcloud-vue/pull/4628

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
| image       | image       |
| image |image 

### 🚧 Tasks

- [ ] Code review
- [ ] Visual review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/components/LeftSidebar/ConversationsListVirtual.vue [hunk 1]
```diff
@@ -151,6 +163,14 @@ export default {
...
 			}
 		},
+
+		adjustScrollerHeight() {
+			const scrollerContainer = this.$refs.scroller.$el.querySelector(
+				'.vue-recycle-scroller__item-wrapper'
+			)
+			const minHeight = this.conversations.length * this.CONVERSATION_ITEM_SIZE + 2
+			scrollerContainer.style.minHeight = minHeight + 'px'
+		},
```
Comment (ShGKme) [inline src/components/LeftSidebar/ConversationsListVirtual.vue:173]: We should not do this to fix the border...

1. It updates only on conversation list update, but it doesn't work on height change, e.g. window resize. It can be fixed by `window`'s `resize` event or resize observer, but it's not great for performance to do it just for a border.
2. It directly mutates DOM nodes that are rendered and managed by Vue with Virtual DOM. We should never mutate Vue's DOM. It has many ways to break.
3. It also searches for an element with a query selector, which is not a big issue but can be easily broken by a small layout change with a class rename.

Comment (ShGKme) [reply src/components/LeftSidebar/ConversationsListVirtual.vue:173]: Ferdinand just suggested an alternative solution for such issues in `NcCheckboxRadioSwitch`: using [`outline-offset`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset) `-2px`. Then the outline it inside the element, and there is no issue with overflow. Maybe try using it here? Or fix it on the nextcloud/vue side...

Comment (ShGKme) [reply src/components/LeftSidebar/ConversationsListVirtual.vue:173]: Or to try to add a 2px footer in the virtual scroller

Comment (DorraJaouad) [reply src/components/LeftSidebar/ConversationsListVirtual.vue:173]: The `outline-offset` is the optimal solution IMO but would rather change it in nextcloud/vue . If so, I will also add the `overflow: hidden` there too.

**Review by ShGKme — APPROVED** [review]
Works, but there is only a native web-browser's outline. Not sure if it is expected.

image

**Comment by nickvergessen** [comment]
Also the last item is cut off again?
Bildschirmfoto vom 2023-11-02 17-12-20

**Comment by DorraJaouad** [comment]
> Works, but there is only a native web-browser's outline. Not sure if it is expected.

image

Native outline seems to be on all elements not only list items. 

>Also the last item is cut off again?

That's the native outline being cut off (extra 1px I guess)
