### PR TITLE
fix: join call immediately with `#direct-call` param

### LINKED ISSUE #17471: [Bug]: `#direct-call` param does not respect 'Skip device preview before joining a call'
> [!TIP]
> ### How to use GitHub
>
> * Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> * Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a link with `<conversation-url>/{token}#direct-call`
2. Media settings should be opened prior to join the call
3. In app settings, toggle 'Skip device preview before joining a call'

### Expected behaviour
Call should be directly joined

### Actual behaviour
Media settings are opened

Responsible listener is here: https://github.com/nextcloud/spreed/blob/e006c8d9e0f12abe3f28eac7df438e8b5147811b/src/views/MainView.vue#L44-L46

Need a clever way to reuse the code from CallButton, where it is working correclty:
https://github.com/nextcloud/spreed/blob/dbc8b86814e2f35821d70866c924ef26e3f52742/src/components/TopBar/CallButton.vue#L461-L466

## Talk app

**Talk app version:** 21

### PR DESCRIPTION
**Pull request by Antreesy**
## ☑️ Resolves

* Fix #17471
  * Extract logic from CallButton to composable
  * Reuse same logic in MainView
* Fix #17574
  * join direct calls rooms with video off
  * join when 'Skip device preview' with video off

### AI (if applicable)

- [ ] The content of this PR was partly or fully generated using AI

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Screenshot before | image

### 🚧 Tasks

- [x] FIXME need to wait for join conversation

### 🏁 Checklist

- [x] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [x] Talk Desktop
  - [ ] Integrations with Files sidebar and other apps
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

File: src/views/MainView.vue [hunk 1]
```diff
@@ -42,7 +49,38 @@ watch(isInLobby, (isInLobby) => {
...
+				const currentJoinedToken = SessionStorage.getItem('joined_conversation')
+				if (currentJoinedToken === routeToken) {
+					joinCall(routeToken)
+				} else {
+					EventBus.once('joined-conversation', async ({ token }) => {
+						if (token !== routeToken) {
+							emit('talk:media-settings:show')
+						}
+						joinCall(routeToken)
+					})
```
Comment (DorraJaouad) [inline src/views/MainView.vue]: to be honest, I don't get the point of this handler. if we receive an event of joining another conversation, why do you need to show the media settings? and why there is a starting call in the first place?

Comment (DorraJaouad) [reply src/views/MainView.vue]: If you have made this as a guard for routeToken, the handler should re-register itself when the wrong token is called

Comment (DorraJaouad) [reply src/views/MainView.vue]: And needs event cleanup at some point before unmounting.

**Review by DorraJaouad — COMMENTED** [review]
Not bad

File: src/views/MainView.vue (hunk 1 above)
Comment (Antreesy) [reply src/views/MainView.vue]: > I don't get the point of this handler... why there is a starting call in the first place?

It's inside of `#direct-call` listener, so user intends to start or join the call. If on Desktop you click popup to 'Answer' call, this should open app first, then load the chat and conversation, and only after `joinConversation` we can call `joinCall`. Not the cleanest implementation here, I think maybe we can later migrate from eventbus to promise - so we're not waiting for some possible event, but initiate it, or if it's already, waiting for existing promise.

> if we receive an event of joining another conversation, why do you need to show the media settings?
> If you have made this as a guard for routeToken, the handler should re-register itself when the wrong token is called

I agree that this should simpy return instead of showing deice checker (or waiting for the correct joining). Too many can change in the meantime

> And needs event cleanup at some point before unmounting.

We do not unmount MainView, so I don't feel the need, but can add it. `.once` will be cleaned up as soon as any conversation is joined anyway.

**Comment by usselite** [comment]
Looking good @Antreesy. If I may suggest one thing, would it be possible to predefine the type of 'call' with #direct-call parameter? E.g. start audio only or with video etc?

**Comment by Antreesy** [comment]
> would it be possible to predefine the type of 'call' with #direct-call parameter? E.g. start audio only or with video etc?

That's not the goal of this PR, more like fitting under the follow-up https://github.com/nextcloud/spreed/issues/17574

File: src/views/MainView.vue (hunk 1 above)
Comment (DorraJaouad) [reply src/views/MainView.vue]: > .once will be cleaned up as soon as any conversation is joined anyway.

Here we can receive a wrong event from different conversation and our target conversation is not being listened to

**Review by DorraJaouad — APPROVED** [review]
Tested
One Note: can you please add skip the handling for non-callable rooms ( like note to self and changelog) ?

**Comment by nickvergessen** [comment]
Needs a rebase and then we merge it?

**Comment by Antreesy** [comment]
> can you please add skip the handling for note to self and changelog?

Addressed in separate commit. One-liner, so not waiting for re-review

> Needs a rebase and then we merge it?

Done, conflicts dropped as already modified in main, no other changes
