### PR TITLE
fix(shares): allow to retry failed uploads

### LINKED ISSUE #10768: Handle upload errors of files and allow to retry
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Upload a file to a conversation

### Expected behaviour
The file should be uploaded, shared and visible to all users

### Actual behaviour
In case the upload was not successful (e.g. erroring out at 503, bad gateway) the temporary placeholder of the file will stay visible to the user, but no file was actually uploaded/shared. It's not clearly visible to the user that the upload failed (you can notice it when looking for the checkmark for example) and there's no option to retry the upload.

This looks like a issue on Talk, while https://github.com/nextcloud/spreed/issues/9681 looks like a issue in Server.

## Talk app

**Talk app version:** 17.1.1 on c.nc.c

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #10768 
  * ATM allows to retry with files marked as 'failed-upload' (in case upload failed when putting on webdav step)

### 🖼️ Screenshots / Screencasts

[retry-upload.webm](https://github.com/nextcloud/spreed/assets/93392545/cc9fe7a8-e775-49f5-8acb-6d4f7b6312db)

> [!TIP]
> Add `if (Math.random() < 0.5) throw new Error()` to `performUpload` function to fail some uploads

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] ⛑️ Tests are included or not possible

### CODE REVIEW

File: src/components/MessagesList/MessagesGroup/Message/Message.vue [hunk 1]
```diff
@@ -810,8 +811,14 @@ export default {
 
 		handleRetry() {
 			if (this.sendingErrorCanRetry) {
-				EventBus.$emit('retry-message', this.id)
-				EventBus.$emit('focus-chat-input')
+				if (this.sendingFailure === 'failed-upload') {
+					const caption = this.renderedMessage !== this.message ? this.message : undefined
+					this.$store.dispatch('retryUploadFiles', { uploadId: this.messageObject.uploadId, caption })
+					this.$store.dispatch('removeTemporaryMessageFromStore', this.messageObject)
```
Comment (DorraJaouad) [inline src/components/MessagesList/MessagesGroup/Message/Message.vue:817]: It would be better if it is in `retryUploadFiles` action and also remove all files from that uploadId not only the one that has the button clicked.

Comment (Antreesy) [reply src/components/MessagesList/MessagesGroup/Message/Message.vue:817]: Yeah, I need to test it with multiple files upload

File: src/store/fileUploadStore.js [hunk 2]
```diff
@@ -66,6 +67,16 @@ const getters = {
 			.filter(([_index, uploadedFile]) => uploadedFile.status === 'initialised')
 	},
 
+	getFailedUploads: (state, getters) => (uploadId) => {
+		return getters.getUploadsArray(uploadId)
+			.filter(([_index, uploadedFile]) => uploadedFile.status === 'failedUpload')
```
Comment (DorraJaouad) [inline src/store/fileUploadStore.js:72]: As I see, you are not using index in any of `getUploadsArray` calls so maybe it's better to change the output format 
```
 return Object.values(state.uploads[uploadId].files)
```

Comment (Antreesy) [reply src/store/fileUploadStore.js:72]: `getUploadsArray` is acting as a middleware to check for existing of files. `index` is used in dependent functions:

```js
for (const [index, uploadedFile] of getters.getInitialisedUploads(uploadId)) {
context.getters.getFailedUploads(uploadId).forEach(([index, file]) => {
const uploads = getters.getUploadingFiles(uploadId)
const shares = getters.getShareableFiles(uploadId)
```

**Review by DorraJaouad — APPROVED** [review]
Tested 🦅

**Comment by DorraJaouad** [comment]
Rebased
